import type { ServicePageDefinition } from "@/lib/service-page-types";

export const administratifPage: ServicePageDefinition = {
  key: "administratif",
  index: "05",
  content: {
    fr: {
      slug: "droit-administratif",
      seo: {
        title: "Avocat en droit administratif au Maroc",
        description: "Avocat en droit administratif au Maroc : recours contre une décision, excès de pouvoir et litiges avec les administrations publiques.",
      },
      eyebrow: "Administration · Recours · Juridictions",
      h1: "Avocat en droit administratif au Maroc",
      lead: "Maître Abderrazak Errouissi accompagne particuliers, agriculteurs et entreprises dans leurs démarches, recours et litiges avec les administrations et organismes publics marocains.",
      summary: [
        "Une décision administrative peut produire des effets immédiats sur un terrain, une autorisation, une activité ou une situation personnelle. Avant d’agir, il faut identifier l’auteur de la décision, sa date de notification, ses motifs et la voie de recours applicable.",
        "Le cabinet intervient depuis Mohammedia pour des dossiers concernant notamment Casablanca, Benslimane, Rabat et d’autres régions du Maroc. Il examine les échanges avec l’administration, les demandes restées sans réponse et les pièces permettant d’établir le droit invoqué ou le préjudice subi.",
        "Selon le dossier, la démarche peut prendre la forme d’une demande motivée, d’un recours gracieux ou hiérarchique, d’un recours en annulation pour excès de pouvoir ou d’une action relevant du plein contentieux. Les délais et conditions de recevabilité doivent être vérifiés dès réception de la décision.",
      ],
      servicesTitle: "Faire valoir ses droits face à l’administration",
      servicesIntro: "La stratégie dépend de la nature de l’acte, de l’autorité concernée, de la preuve de notification et de l’objectif recherché par le client.",
      services: [
        { title: "Recours contre une décision administrative", text: "Analyse de la décision, de sa motivation et de ses effets, puis préparation du recours adapté à la situation et aux délais applicables." },
        { title: "Recours pour excès de pouvoir", text: "Étude de la compétence de l’auteur, de la forme, des motifs, du but poursuivi et du respect de la loi avant une demande d’annulation." },
        { title: "Autorisations, permis et urbanisme", text: "Litiges relatifs aux autorisations administratives, permis, refus, retraits, décisions d’urbanisme et difficultés affectant un projet immobilier ou rural." },
        { title: "Responsabilité de l’administration", text: "Examen d’une faute, d’un dommage et du lien entre les deux, puis étude d’une demande d’indemnisation lorsqu’elle est juridiquement fondée." },
        { title: "Domaine public et expropriation", text: "Analyse des décisions touchant l’occupation, les limites, l’utilité publique, l’expropriation et les droits attachés à un bien immobilier ou agricole." },
        { title: "Exécution et suivi des décisions", text: "Suivi des démarches après une décision administrative ou juridictionnelle et examen des difficultés rencontrées dans son application." },
      ],
      processTitle: "Identifier l’acte, le délai et la juridiction compétente",
      processIntro: "En droit administratif, une bonne argumentation ne suffit pas si le recours vise le mauvais acte, la mauvaise autorité ou intervient hors délai.",
      process: [
        { title: "Établir la chronologie", text: "Réunir la décision, sa preuve de notification, les demandes antérieures, les réponses et tous les documents justificatifs." },
        { title: "Qualifier le recours", text: "Identifier l’acte contestable, les moyens juridiques, la juridiction compétente et les conditions de recevabilité." },
        { title: "Engager la démarche utile", text: "Préparer le recours administratif ou juridictionnel et suivre les mesures nécessaires à la défense du dossier." },
      ],
      faqTitle: "Questions fréquentes sur les recours administratifs",
      faqIntro: "Une décision défavorable ou le silence d’une administration doit être analysé rapidement. Les règles changent selon l’acte, la matière et le recours envisagé.",
      faqs: [
        { question: "Comment contester une décision administrative au Maroc ?", answer: "Il faut obtenir la décision, vérifier sa notification, identifier l’autorité qui l’a prise et déterminer le recours ouvert. Selon le cas, un recours gracieux, hiérarchique ou contentieux peut être envisagé." },
        { question: "Quel est le délai pour former un recours en annulation ?", answer: "Le recours en annulation pour excès de pouvoir est en principe encadré par un délai de soixante jours, mais le point de départ et les règles particulières doivent être vérifiés pour chaque décision. Il est prudent de consulter dès la notification." },
        { question: "Peut-on agir lorsque l’administration ne répond pas ?", answer: "Le silence peut produire des effets juridiques qui varient selon la demande et le texte applicable. Il faut conserver la preuve du dépôt, calculer le délai et déterminer si une relance, un recours ou une saisine juridictionnelle est possible." },
        { question: "Quels documents fournir pour un recours administratif ?", answer: "Apportez la décision contestée, l’enveloppe ou preuve de notification, les demandes déposées, récépissés, réponses, autorisations, plans et tout document établissant votre droit et les conséquences de la décision." },
        { question: "Le tribunal administratif peut-il accorder une indemnisation ?", answer: "Une demande d’indemnisation peut être étudiée lorsqu’un dommage est imputé à l’administration. Il faut établir les faits, le préjudice, le lien de causalité et respecter la procédure correspondant à l’action envisagée." },
      ],
      related: [
        { key: "fiscal", label: "Contentieux fiscal" },
        { key: "foncierRural", label: "Foncier rural" },
      ],
      ctaTitle: "Une décision administrative affecte vos droits ?",
      ctaText: "Adressez au cabinet la décision, sa date de notification et vos échanges avec l’administration afin d’examiner rapidement les recours possibles.",
    },
    ar: {
      slug: "القانون-الإداري",
      seo: {
        title: "محامٍ في القضاء والمنازعات الإدارية بالمغرب | الأستاذ عبد الرزاق الرويسي",
        description: "محامٍ في المنازعات الإدارية وقضايا القضاء الإداري بالمغرب: دعاوى الإلغاء للشطط في استعمال السلطة، التعويض عن نزع الملكية، والاعتداء المادي بالمحمدية والدار البيضاء والرباط.",
      },
      eyebrow: "القضاء الإداري · دعاوى الإلغاء · المحاكم الإدارية",
      h1: "محامٍ في القضاء والمنازعات الإدارية بالمغرب",
      lead: "يؤازر مكتب الأستاذ عبد الرزاق الرويسي، محامٍ بهيئة الدار البيضاء مقبول لدى محكمة النقض، الخواص والشركات والفلاحين في مواجهة القرارات الإدارية المعيبة، دعاوى الإلغاء لتجاوز السلطة، والمسؤولية الإدارية والتعويض أمام المحاكم الإدارية ومحاكم الاستئناف الإدارية ومحكمة النقض.",
      summary: [
        "تخضع المنازعة الإدارية لمقتضيات القانون رقم 41.90 المحدث للمحاكم الإدارية؛ حيث يتعين رفع دعوى الإلغاء بسبب تجاوز السلطة داخل أجل 60 يوماً من تاريخ التبليغ أو النشر (الفصل 23)، أو بعد رفض التظلم الاستعطافي، مع تدقيق عيوب القرار الإداري (عيب الاختصاص، الشكل، انعدام التعليل، مخالفة القانون، والانحراف في استعمال السلطة).",
        "يترافع المكتب في قضايا القضاء الشامل والمسؤولية الإدارية عن أضرار المرافق العمومية، ومنازعات الاعتداء المادي على الملكيات الخاصة دون سلوك مسطرة نزع الملكية القانونية (القانون 7.81)، والمطالبة بالتعويضات العادلة وجبر الضرر الكامل.",
        "تشمل الممارسة معالجة نزاعات قرارات التعمير، رخص البناء والتجزئة، الطعن في قرارات سحب الرخص والقرارات الضبطية، ومنازعات صفقات وموظفي الإدارات والجماعات الترابية والمؤسسات العمومية.",
      ],
      servicesTitle: "الترافع أمام المحاكم الإدارية وحماية الحقوق ضد الشطط الإداري",
      servicesIntro: "ترتكز خطة الدفاع على التحقق الصارم من صفة القرار، احترام مواعيد الطعن، وتكييف أركان الشطط في استعمال السلطة أو الخطأ المرفقي.",
      services: [
        { title: "دعاوى الإلغاء لتجاوز السلطة (الشطط)", text: "رفع دعاوى إلغاء القرارات الإدارية الفردية والتنظيمية لمخالفة القانون، عيب الاختصاص، أو انعدام السبب أمام المحاكم الإدارية ومحكمة النقض." },
        { title: "الاعتداء المادي ونزع الملكية للمنفعة العامة", text: "مواجهة وضع يد الإدارة على العقارات خارج مسطرة القانون 7.81 (الاعتداء المادي)، والمطالبة بالتعويض عن فقدان الملكية والحرمان من الاستغلال." },
        { title: "منازعات التعمير ورخص البناء والتجزئة", text: "الطعن في قرارات رفض تسليم رخص البناء، السكن، قرارات الهدم، أو قرارات إيقاف الأوراش والتجزئات العقارية المخالفة للضوابط القانونية." },
        { title: "دعاوى القضاء الشامل والمسؤولية الإدارية", text: "المطالبة بالتعويض عن أضرار الأشغال والمرافق العمومية، الحوادث المرفقية، ومسؤولية الدولة والجماعات الترابية عن أعمالها الضارة." },
        { title: "المنازعات المتعلقة بالملك العام والخاص للدولة", text: "الترافع في نزاعات رخص الاحتلال المؤقت للملك العمومي، تحديد حدوده، وحماية المراكز القانونية للشركات والخواص إزاء الإدارة." },
        { title: "مساطر إيقاف التنفيذ والصعوبات الوقتية", text: "تقديم طلبات إيقاف تنفيذ القرارات الإدارية ذات الأثر الفوري الخطير أمام قضاء المستعجلات الإداري لدرء الأضرار التي يتعذر تداركها." },
      ],
      processTitle: "مراحل المسطرة الإدارية من التظلم إلى التنفيذ الجبري",
      processIntro: "لا يكفي ثبوت الضرر لكسب الدعوى الإدارية؛ بل يتوقف الأمر على احترام الآجال ومخاطبة الجهة الإدارية ذات الصفة القانونية.",
      process: [
        { title: "دراسة مشروعية القرار وتاريخ التبليغ", text: "فحص شهادة التبليغ، توجيه التظلم الاستعطافي أو الرئاسي داخل أجل 60 يوماً متى كان ذلك في مصلحة الموكل لقطع التقادم." },
        { title: "صياغة المقال الافتتاحي وتأسيس الدفوع", text: "تحرير المقال وتأسيسه على خروقات القانون 41.90 وقواعد الفقه الإداري، وإرفاق النسخ والوثائق والمستندات الإدارية." },
        { title: "الترافع ومتابعة تنفيذ الأحكام ضد الإدارة", text: "متابعة مساطر التحقيق والخبرة، وتنفيذ الأحكام القضائية الصادرة ضد أشخاص القانون العام ومواجهة الامتناع عن التنفيذ." },
      ],
      faqTitle: "أسئلة شائعة حول القضاء والمنازعات الإدارية بالمغرب",
      faqIntro: "تتضمن هذه التوضيحات مبادئ توجيهية عامة، وتظل دراسة القرار الإداري وتاريخ تبليغه حاسمة لاحترام أجل 60 يوماً المسقط للدعوى.",
      faqs: [
        { question: "ما هو الأجل القانوني لرفع دعوى الإلغاء لتجاوز السلطة بالمغرب؟", answer: "يحدد الفصل 23 من القانون رقم 41.90 أجلاً مدته 60 يوماً لرفع دعوى الإلغاء، ويبتدئ من تاريخ نشر القرار الإداري أو تبليغه إلى المعني بالأمر؛ وإذا قُدم تظلم إداري استعطافي داخل هذا الأجل، فإن سكوت الإدارة لمدة 60 يوماً يعتبر رفضاً ضمنياً يفتح أجلاً جديداً مدته 60 يوماً للطعن القضائي." },
        { question: "ما هو مفهوم 'الاعتداء المادي' وكيف تتم مقاضاة الإدارة بشأنه؟", answer: "الاعتداء المادي هو استيلاء الإدارة على ملك عقاري خاص أو الشروع في أشغال فوقه دون سند قانوني وبمعزل عن إجراءات نزع الملكية المحددة في القانون 7.81؛ ويختص القضاء الإداري بالبت فيه بالحكم بتعويض كامل وشامل يوازي القيمة الحقيقية للعقار وتاريخ الاستيلاء عليه، وتختص محاكم الموضوع بإرجاع الحالة إن أمكن." },
        { question: "كيف يتم إيقاف تنفيذ قرار إداري يلحق ضرراً فادحاً بالنشاط أو العقار؟", answer: "يحق للمعني تقديم طلب استعجالي لإيقاف تنفيذ القرار الإداري بالتزامن مع دعوى الإلغاء طبقاً للفصل 24 من القانون 41.90، شريطة إثبات قيام أسباب جدية ترجح إلغاء القرار وأن يؤدي تنفيذه إلى نتائج يتعذر تداركها." },
        { question: "هل يلزم توكيل محامٍ في الدعاوى المرفوعة أمام المحاكم الإدارية؟", answer: "نعم، طبقاً للمادة 3 من القانون 41.90 والمادة 31 من القانون المنظم لمهنة المحاماة، تُرفع الدعاوى وجوباً بمقال مكتوب وموقع من طرف محامٍ مسجل في جدول إحدى هيئات المحامين بالمغرب ومقبول للترافع أمامها." },
        { question: "ما الإجراءات المتبعة عند امتناع الإدارة عن تنفيذ حكم قضائي نهائي حائز لقوة الشيء المقضي به؟", answer: "يتم توجيه إعذار رسمي بالتنفيذ عبر كتابة الضبط، واستصدار أمر قضائي بالغرامة التهديدية ضد الإدارة الممتنعة أو فتح مسطرة الحجز لدى الغير على اعتماداتها المالية متى سمح القانون بذلك لضمان استيفاء الحقوق المحكوم بها." },
      ],
      related: [
        { key: "fiscal", label: "المنازعات والتحصيل الضريبي" },
        { key: "foncierRural", label: "العقار الفلاحي ونزع الملكية" },
      ],
      ctaTitle: "هل تضررتم من قرار إداري جائر أو اعتداء مادي على عقاركم؟",
      ctaText: "بادروا بعرض ملفكم على مكتب الأستاذ عبد الرزاق الرويسي بالمحمدية فور تسلم القرار لدراسة أوجه الطعن ومباشرة الإجراءات قبل فوات أجل 60 يوماً.",
    },
  },
};
