import type { ServicePageDefinition } from "@/lib/service-page-types";

export const fiscalPage: ServicePageDefinition = {
  key: "fiscal",
  index: "04",
  content: {
    fr: {
      slug: "droit-fiscal",
      seo: {
        title: "Avocat fiscaliste à Casablanca et au Maroc",
        description: "Avocat fiscaliste près de Casablanca : contrôle, redressement, réclamation et contentieux fiscal pour particuliers et entreprises au Maroc.",
      },
      eyebrow: "Fiscalité · Contrôle · Contentieux",
      h1: "Avocat fiscaliste à Casablanca et au Maroc",
      lead: "Maître Abderrazak Errouissi accompagne particuliers, entreprises et détenteurs de patrimoine lors des contrôles, redressements et litiges avec l’administration fiscale marocaine.",
      summary: [
        "Un dossier fiscal se joue souvent dès le premier avis ou la première notification. Les pièces comptables, actes, déclarations, échanges et délais doivent être examinés ensemble afin de comprendre la méthode retenue par l’administration et de préparer une réponse documentée.",
        "Depuis Mohammedia, à proximité de Casablanca, le cabinet intervient dans les différends relatifs à l’impôt sur le revenu, à l’impôt sur les sociétés, à la TVA, aux profits fonciers et aux impositions liées aux opérations immobilières ou successorales.",
        "L’analyse porte sur les faits, la procédure suivie, les éléments de preuve et les voies de recours réellement ouvertes. Le cabinet distingue la demande d’explication, la réponse à une rectification, la réclamation administrative et le contentieux devant la juridiction compétente.",
      ],
      servicesTitle: "Répondre au contrôle, défendre la position fiscale",
      servicesIntro: "Chaque intervention commence par la chronologie du dossier et la vérification des documents reçus, des bases d’imposition et des délais applicables.",
      services: [
        { title: "Contrôle fiscal", text: "Analyse de l’avis de vérification, préparation des justificatifs, suivi des échanges et assistance pendant les opérations de contrôle." },
        { title: "Redressement et notifications", text: "Étude des motifs, montants et méthodes de calcul, puis préparation d’une réponse argumentée à partir des pièces disponibles." },
        { title: "Réclamations et recours fiscaux", text: "Préparation des réclamations, suivi des réponses de l’administration et orientation vers la commission ou la juridiction compétente selon le dossier." },
        { title: "Contentieux fiscal", text: "Représentation dans les litiges portant sur l’assiette, le recouvrement, les pénalités ou la régularité de la procédure fiscale." },
        { title: "Fiscalité immobilière et successorale", text: "Analyse des impositions liées aux ventes, profits fonciers, transmissions, partages, régularisations et biens reçus par succession." },
        { title: "Sécurisation documentaire", text: "Examen juridique des actes, déclarations, contrats et justificatifs afin d’identifier les incohérences et les risques avant une opération ou un recours." },
      ],
      processTitle: "Une défense fiscale fondée sur les pièces et la procédure",
      processIntro: "Le montant contesté ne suffit pas à définir la stratégie : la notification, les délais, la preuve et l’étape exacte de la procédure sont déterminants.",
      process: [
        { title: "Reconstituer le dossier", text: "Classer les avis, notifications, déclarations, actes, justificatifs, échanges et paiements dans leur ordre chronologique." },
        { title: "Vérifier la procédure", text: "Examiner la base juridique, la méthode de calcul, les délais et les garanties dont dispose le contribuable." },
        { title: "Choisir le recours adapté", text: "Préparer une réponse, une réclamation, une saisine de commission ou une action contentieuse selon l’état du dossier." },
      ],
      faqTitle: "Questions fréquentes sur le contrôle et le contentieux fiscal",
      faqIntro: "Les délais et voies de recours varient selon l’impôt, la décision reçue et l’étape de la procédure. Une notification doit être examinée sans attendre.",
      faqs: [
        { question: "Que faire après réception d’un avis de contrôle fiscal ?", answer: "Il faut identifier la période et les impôts concernés, préserver les pièces demandées et vérifier le calendrier de la procédure. Une préparation anticipée permet de présenter des justificatifs cohérents et d’éviter des réponses contradictoires." },
        { question: "Comment contester un redressement fiscal au Maroc ?", answer: "La notification, ses motifs et les calculs doivent être analysés avec les déclarations et justificatifs. La réponse dépend du stade de la procédure et peut conduire à une réclamation, à une commission de recours ou à une action devant la juridiction compétente." },
        { question: "Quels documents apporter à un avocat fiscaliste ?", answer: "Apportez les avis, notifications, déclarations, contrats, factures, relevés utiles, actes immobiliers, réponses déjà envoyées et preuves de réception. Une chronologie des échanges aide également à repérer les délais." },
        { question: "Un particulier peut-il être concerné par un contentieux fiscal ?", answer: "Oui. Un litige peut notamment porter sur des revenus, un profit foncier, une cession immobilière, une succession ou une procédure de recouvrement. La situation doit être examinée à partir des documents effectivement reçus." },
        { question: "Combien coûte l’accompagnement d’un dossier fiscal ?", answer: "Les honoraires dépendent du stade de la procédure, du volume des pièces, des montants en jeu et des démarches nécessaires. Le périmètre de la mission est défini après une première étude du dossier." },
      ],
      related: [
        { key: "administratif", label: "Droit administratif" },
        { key: "immobilier", label: "Droit immobilier" },
      ],
      ctaTitle: "Vous avez reçu un avis ou une notification fiscale ?",
      ctaText: "Transmettez les documents reçus, leur date de notification et les justificatifs disponibles afin d’identifier rapidement les prochaines étapes.",
    },
    ar: {
      slug: "القانون-الضريبي",
      seo: {
        title: "محامٍ في المنازعات والتحصيل الضريبي بالمغرب | الأستاذ عبد الرزاق الرويسي",
        description: "محامٍ في القضايا والمنازعات الضريبية بالمغرب: المراقبة الجبائية، مساطر التصحيح التواجهية، الطعن أمام اللجان الضريبية والمحاكم الإدارية، وإيقاف إجراءات التحصيل الجبري.",
      },
      eyebrow: "القانون الضريبي · المراقبة الجبائية · القضاء الإداري",
      h1: "محامٍ في المنازعات والتحصيل الضريبي بالمغرب",
      lead: "يؤازر مكتب الأستاذ عبد الرزاق الرويسي، محامٍ بهيئة الدار البيضاء مقبول لدى محكمة النقض، المقاولات والأفراد في مساطر المراقبة الجبائية، التبليغات والتصحيحات الضريبية، ومنازعات الوعاء والتحصيل أمام اللجان المختصة والمحاكم الإدارية.",
      summary: [
        "تتسم المنازعة الجبائية بصرامة شكلية مطلقة تحت طائلة سقوط الحق؛ حيث يتعين التفاعل مع الإشعار بالتحقيق ورسائل التبليغ الأولى والثانية داخل أجل 30 يوماً الصارم طبقاً للمادتين 220 و221 من المدونة العامة للضرائب، والتدقيق في أسس الفحص المحاسبي وتقديرات الإدارة.",
        "يمثل المكتب الملزمين بالضريبة انطلاقاً من مقره بالمحمدية أمام المديريات الإقليمية والجهوية للضرائب بالدار البيضاء والرباط، وأمام اللجان المحلية لتقدير الضريبة (CLT) واللجنة الوطنية للنظر في الطعون المتعلقة بالضريبة (CNRF)، وصولاً إلى رفع دعاوى الإلغاء واسترداد المبالغ المؤداة بغير حق أمام المحاكم الإدارية ومحاكم الاستئناف الإدارية.",
        "تشمل الممارسة معالجة الضرائب العقارية ذات الأثر المالي البالغ (الضريبة على الأرباح العقارية TPI)، الرسوم المحلية للجماعات الترابية، ومنازعات قباضات الخزينة العامة للمملكة المتعلقة بالتحصيل الجبري (الإشعار للغير الحائز ATD والحجوزات البنكية والعقارية) استناداً إلى مدونة تحصيل الديون العمومية (القانون 15.97).",
      ],
      servicesTitle: "المؤازرة في الفحص الجبائي، مساطر اللجان ومنازعات التحصيل",
      servicesIntro: "ترتكز استراتيجية الدفاع الضريبي على تفكيك الأساس القانوني لفرض الضريبة، مراقبة احترام الضمانات المسطرية للملزم، والتقيد الحرفي بالآجال القانونية.",
      services: [
        { title: "المراقبة والفحص الجبائي للمقاولات", text: "مواكبة الملزم فور التوصل بالإشعار بالفحص، فحص الوثائق المحاسبية والدفاتر، وصياغة الملاحظات الأولية وتأطير نقاشات مفتشي الضرائب تجنباً للتقدير الجزافي." },
        { title: "الرد على رسائل التبليغ والتصحيح الضريبي", text: "صياغة المذكرات الجوابية القانونية والتقنية المفصلة على رسائل التبليغ الأولى والثانية داخل أجل 30 يوماً القانوني، وإثارة عيوب التعليل وبطلان المسطرة." },
        { title: "الطعون أمام اللجان المحلية واللجنة الوطنية (CNRF)", text: "تمثيل الملزم والترافع في جلسات اللجنة المحلية لتقدير الضريبة (CLT) واللجنة الوطنية للنظر في الطعون المتعلقة بالضريبة، وتقديم الحجج المحاسبية والوثائق الدامغة." },
        { title: "دعاوى القضاء الإداري والطعن في الإفراط الضريبي", text: "رفع دعاوى إلغاء المقررات الضريبية المعيبة للشطط في استعمال السلطة أو عيوب الشكل، ودعاوى إسقاط الضرائب واسترداد المبالغ المستخلصة دون سند قانوني أمام المحاكم الإدارية." },
        { title: "منازعات الضريبة على الأرباح العقارية (TPI)", text: "الطعن في إعادة تقدير ثمن البيع من طرف إدارة الضرائب في المعاملات العقارية، وإثبات الثمن الحقيقي عبر المقارنات والمراجع العقارية المعتمدة والمساطر التواجهية." },
        { title: "إيقاف إجراءات التحصيل الجبري والإشعار للغير الحائز (ATD)", text: "مواجهة إجراءات الحجز والتحصيل الجبري لمديني الدولة (القانون 15.97)، والطعن في الإنذارات القانونية، ورفع الحجوزات غير القانونية عبر مساطر استعجالية لوقف التنفيذ." },
      ],
      processTitle: "مراحل مباشرة المنازعة الجبائية من الإشعار إلى الحكم الإداري",
      processIntro: "كل مرحلة مسطرية تخضع لأجل سقوط صارم؛ ونبادر فور التوصل بالملف إلى تدقيق التواريخ والتأكد من عدم فوات مواعيد الرد أو الطعن.",
      process: [
        { title: "الفحص المسطري والتحقق من الآجال", text: "تدقيق تاريخ تبليغ الإشعار أو رسالة التصحيح (شهادة التسليم)، ومقارنة المبررات مع أحكام المدونة العامة للضرائب للتأكد من احترام أجل الرد (30 يوماً)." },
        { title: "بناء أوجه الدفاع والدفوع المحاسبية", text: "تفنيد أسباب إعادة التقدير، تدقيق القوائم التركيبية والفواتير والعقود، وصياغة الردود المستندة إلى عيوب المسطرة أو انعدام التعليل." },
        { title: "مباشرة مسطرة اللجان أو التقاضي الإداري", text: "إحالة النزاع إلى اللجنة الضريبية المختصة أو مباشرة دعوى الموضوع أمام المحكمة الإدارية مع تقديم طلبات إيقاف الأداء طبقاً للقانون." },
      ],
      faqTitle: "أسئلة شائعة حول المراقبة والمنازعات والتحصيل الضريبي",
      faqIntro: "تتضمن هذه التوضيحات مبادئ توجيهية عامة، وتظل دراسة رسائل التبليغ والتواريخ الفعلية للتسلم حاسمة لاتخاذ الإجراء القانوني في أجله المحدد.",
      faqs: [
        { question: "ما هو الأجل القانوني الواجب احترامه للرد على رسالة التصحيح الضريبي الأولى؟", answer: "يحدد المشرع في المادة 220 من المدونة العامة للضرائب أجلاً صارماً مدته 30 يوماً من تاريخ تسلم رسالة التبليغ الأولى للجواب؛ ويترتب على عدم الجواب داخل هذا الأجل فرض الضريبة تلقائياً وفقدان حق الطعن التوافقي أمام اللجان." },
        { question: "كيف تتم مواجهة فرض الضريبة على الأرباح العقارية (TPI) عند إعادة تقييم ثمن العقار المبيع؟", answer: "تتم المواجهة بإثبات عناصر الثمن المصرح به عبر المقارنة مع المعاملات المجاورة وحالة العقار الواقعية وتجهيزاته، والطعن في معايير المرجع العقاري (Référentiel) الذي تعتمده الإدارة إذا كان جزافياً، وإحالة الملف على اللجنة المحلية لتقدير الضريبة (CLT)." },
        { question: "ما هو السبيل القانوني لرفع الإشعار للغير الحائز (ATD) والحجوزات البنكية غير المشروعة؟", answer: "يتم رفع دعوى استعجالية أمام رئيس المحكمة الإدارية بصفته قاضياً للمستعجلات لإيقاف إجراءات التحصيل أو رفع الحجز، استناداً إلى خروقات مدونة تحصيل الديون العمومية (كعدم توجيه الإنذار القانوني، تقادم الدين الضريبي، أو تقديم ضمانات كافية طبقاً للمادة 117)." },
        { question: "هل يحق للأفراد والمقاولات اللجوء للمحكمة الإدارية مباشرة في النزاع الضريبي؟", answer: "يلزم القانون استنفاد المرحلة الإدارية التواجهية بتقديم تظلم استعطافي/نزاعي أمام مدير الضرائب داخل أجل 6 أشهر من تاريخ وضع جدول الضريبة موضع التحصيل (المادة 235 من CGI)؛ وفي حال الرفض الصريح أو الضمني (مرور 3 أشهر دون جواب) يحق للملزم رفع الدعوى أمام المحكمة الإدارية داخل أجل 30 يوماً." },
        { question: "كيف تُحدد أتعاب المحامي في القضايا والمنازعات الضريبية؟", answer: "تُحدد الأتعاب بالاتفاق وفقاً لأهمية المبالغ الضريبية المتنازع عليها، طبيعة المسطرة (مواكبة فحص، لجان طعن، أو تقاضٍ إداري)، ومدى تعقيد الدفوع المحاسبية، وتُثبت باتفاق شفاف ومكتوب." },
      ],
      related: [
        { key: "administratif", label: "القانون والقضاء الإداري" },
        { key: "immobilier", label: "القانون العقاري والتحفيظ" },
      ],
      ctaTitle: "هل توصلتم بتبليغ تصحيح ضريبي أو إنذار بالتحصيل الجبري؟",
      ctaText: "سارعوا بعرض رسائل التبليغ وتواريخ التسلم على مكتب الأستاذ عبد الرزاق الرويسي لدراسة أوجه البطلان المسطري وإعداد الردود القانونية قبل سقوط الآجال.",
    },
  },
};
