import type { ServicePageDefinition } from "@/lib/service-page-types";

export const foncierRuralPage: ServicePageDefinition = {
  key: "foncierRural",
  index: "03",
  content: {
    fr: {
      slug: "droit-foncier-rural",
      seo: {
        title: "Avocat terres agricoles et foncier rural au Maroc",
        description: "Avocat en foncier rural au Maroc : terres agricoles, terres des coopératives de la réforme agraire, indivision, bornage et expropriation à Benslimane, Chaouia et Mohammedia.",
      },
      eyebrow: "Foncier rural · Terres agricoles · Maroc",
      h1: "Avocat en terres agricoles et foncier rural au Maroc",
      lead: "Maître Abderrazak Errouissi accompagne familles, agriculteurs et exploitants dans les conflits de propriété, d’héritage, de bornage et d’usage touchant les terres rurales.",
      summary: [
        "Un terrain agricole ne peut pas être traité comme un simple bien urbain. Avant toute action, il faut identifier son statut, l’origine des droits, les actes disponibles, l’occupation réelle, les limites physiques et les éventuelles décisions administratives qui l’affectent.",
        "Le cabinet intervient depuis Mohammedia dans les dossiers situés notamment à Benslimane, dans la Chaouia et dans d’autres régions du Maroc. Son analyse relie droit foncier, succession et réalité de l’exploitation afin d’éviter qu’un conflit familial ou une limite incertaine ne bloque durablement la terre.",
        "Melkiya, titre foncier, terre de coopérative de la réforme agraire ou bien en indivision n’obéissent pas à la même logique de preuve et de procédure. La première étape consiste donc à qualifier précisément le terrain avant de choisir négociation, expertise, démarche administrative ou action judiciaire.",
      ],
      servicesTitle: "Défendre la terre, ses limites et sa transmission",
      servicesIntro: "Le cabinet rassemble les pièces, reconstitue l’origine des droits et confronte les documents à la situation effective du terrain agricole.",
      services: [
        { title: "Terres agricoles Melk et Melkiya", text: "Étude des actes de propriété non immatriculée, de la possession, des témoignages et des transmissions successives, puis articulation avec une éventuelle procédure d’immatriculation." },
        { title: "Terres des coopératives de la réforme agraire", text: "Accompagnement dans les affaires et litiges relatifs aux terres des coopératives de la réforme agraire, du vivant des bénéficiaires comme après leur décès, notamment en matière de succession et de transmission des droits, dans le respect du régime juridique particulier de ces terres." },
        { title: "Indivision et sortie d’indivision", text: "Partage amiable ou judiciaire des fermes et parcelles héritées, droits des cohéritiers, exploitation exclusive et blocage d’un bien rural détenu à plusieurs." },
        { title: "Bornage, limites et empiètement", text: "Conflits de limites entre parcelles, accès, chemins, occupation d’une bande de terrain et examen des plans, constats, expertises et repères matériels." },
        { title: "Expropriation et indemnisation", text: "Examen de la procédure, des notifications, de la consistance du bien et des éléments utiles à la discussion de l’indemnité, sans préjuger de l’évaluation retenue." },
        { title: "Vente, bail et exploitation agricole", text: "Vérification du statut du terrain, des pouvoirs du cédant ou bailleur et des risques liés à l’usage, à l’accès, à l’eau ou à l’indivision avant engagement." },
      ],
      processTitle: "Partir du statut réel de la terre",
      processIntro: "En matière rurale, une stratégie solide commence par la concordance entre l’acte, la parcelle, les limites et les personnes qui revendiquent ou exercent les droits.",
      process: [
        { title: "Qualifier le terrain", text: "Déterminer le statut foncier, l’origine de propriété, l’existence d’un titre et la situation d’occupation ou d’exploitation." },
        { title: "Reconstituer les droits", text: "Rassembler Melkiya, actes, certificats, plans, documents successoraux, décisions, constats et éléments de possession." },
        { title: "Choisir la voie utile", text: "Organiser une négociation, une expertise, une démarche administrative ou une procédure adaptée à la nature exacte du conflit." },
      ],
      faqTitle: "Questions fréquentes sur les terres agricoles",
      faqIntro: "Le statut foncier et les documents disponibles changent entièrement la solution. Ces repères généraux ne remplacent pas l’étude de la parcelle et de son historique.",
      faqs: [
        { question: "Quelle différence entre une Melkiya et un titre foncier ?", answer: "La Melkiya constitue un acte invoqué pour établir une propriété non immatriculée, tandis que le titre foncier résulte de l’immatriculation et retrace les droits inscrits sur l’immeuble. Leur force, leurs mentions et les voies de contestation ne s’analysent donc pas de la même manière." },
        { question: "Comment régler un conflit de bornage sur un terrain rural ?", answer: "Il faut comparer les actes, plans, limites matérielles, accès et occupations, puis apprécier l’utilité d’un constat ou d’une expertise. À Benslimane et dans la Chaouia, l’historique des parcelles et des transmissions est souvent déterminant." },
        { question: "Comment sortir de l’indivision d’une terre agricole ?", answer: "Les coindivisaires peuvent rechercher une répartition amiable si elle est juridiquement et matériellement possible. À défaut d’accord, une demande de partage peut être étudiée en tenant compte du statut de la terre, de sa divisibilité et des droits de chacun." },
        { question: "Peut-on partager une ferme entre plusieurs héritiers ?", answer: "Le partage dépend des titres, de la configuration de l’exploitation, des droits successoraux et de la possibilité réelle de diviser sans méconnaître le statut applicable. Une évaluation et une solution d’attribution ou de cession peuvent aussi être examinées." },
        { question: "Que faire en cas d’expropriation d’un terrain agricole ?", answer: "Il convient de vérifier les actes et notifications, d’identifier exactement la parcelle et de réunir les éléments concernant sa consistance et son exploitation. Les délais et voies de contestation doivent être examinés dès réception des documents." },
        { question: "Comment sont traitées les affaires relatives aux terres des coopératives de la réforme agraire ?", answer: "Ces terres obéissent à un régime juridique spécifique. Le cabinet intervient dans les litiges et démarches tant du vivant des bénéficiaires (conditions d’exploitation, respect des obligations coopératives, régularisation) qu’après leur décès, notamment pour les questions de succession, d’attribution et de transmission des droits." },
      ],
      related: [
        { key: "immobilier", label: "Droit immobilier" },
        { key: "succession", label: "Successions rurales" },
      ],
      ctaTitle: "Une terre agricole est bloquée ou contestée ?",
      ctaText: "Apportez Melkiya, titre, plan, documents successoraux et décisions reçues pour qualifier le terrain et identifier les premières mesures utiles.",
    },
    ar: {
      slug: "العقار-الفلاحي-وأراضي-تعاونيات-الإصلاح-الزراعي",
      seo: {
        title: "محامٍ في قضايا العقار الفلاحي وأراضي تعاونيات الإصلاح الزراعي بالمغرب",
        description: "محامٍ في منازعات العقار الفلاحي وأراضي تعاونيات الإصلاح الزراعي بالمغرب: تصفية الشياع، دعاوى التحديد والترامي، مساطر نزع الملكية، وقضايا انتقال الحقوق والإرث بالمحمدية وبنسليمان والشاوية.",
      },
      eyebrow: "العقار الفلاحي · أراضي تعاونيات الإصلاح الزراعي · المغرب",
      h1: "محامٍ في قضايا العقار الفلاحي وأراضي تعاونيات الإصلاح الزراعي بالمغرب",
      lead: "يؤازر الأستاذ عبد الرزاق الرويسي، محامٍ بهيئة الدار البيضاء مقبول لدى محكمة النقض، الفلاحين والمستغلين والورثة في قضايا الأراضي الفلاحية، منازعات أراضي تعاونيات الإصلاح الزراعي، تصفية الشياع، ومساطر نزع الملكية للمنفعة العامة بالمغرب.",
      summary: [
        "تخضع الأراضي الفلاحية في التشريع المغربي لمنظومة عقارية مركبة تجمع بين الملك الخاص، أراضي تعاونيات الإصلاح الزراعي الخاضعة لنظامها القانوني الخاص، والأراضي الفلاحية المسترجعة. ويتطلب تدبير هذه الأصول فحصاً دقيقاً للرسوم والضوابط العقارية، ومطابقة السندات مع واقع الاستغلال الميداني.",
        "يباشر المكتب، انطلاقاً من مقره بالمحمدية وفي دوائر بنسليمان، الشاوية، سطات، وسائر أرجاء المملكة، مساطر تسوية الوضعية العقارية، ودعاوى التحديد ومطابقة الرسوم، وقسمة العقارات الفلاحية المشاعة لتفادي تجزئة الاستغلاليات بما يتعارض مع النصوص القانونية المنظمة.",
        "تختلف وسائل الإثبات وقواعد الاختصاص جذرياً بين العقار المحفظ، والعقار الخاضع للملكية العدلية، وأراضي تعاونيات الإصلاح الزراعي؛ مما يقتضي تشخيصاً قانونياً استباقياً لصفة الأطراف وسندات التصرف قبل الشروع في أي نزاع قضائي أو مسطرة إدارية.",
      ],
      servicesTitle: "حماية الملكيات الفلاحية، تدبير الشياع ومنازعات أراضي تعاونيات الإصلاح الزراعي",
      servicesIntro: "يرتكز عمل المكتب على مقاربة وثائقية وميدانية صارمة تجمع بين تدقيق الرسوم العدلية ومطالب التحفيظ ومباشرة الإجراءات الإدارية والقضائية الملائمة.",
      services: [
        { title: "أراضي الملك الخاص والرسوم العدلية (الملكية)", text: "فحص وتدقيق رسوم الاستمرار والملكيات العدلية القديمة، شروط الحيازة المكسبة (المادة 239 وما بعدها من مدونة الحقوق العينية)، ومباشرة مساطر التحفيظ العقاري لتأمين الملكية الفلاحية." },
        { title: "أراضي تعاونيات الإصلاح الزراعي", text: "مواكبة القضايا والمنازعات المتعلقة بأراضي تعاونيات الإصلاح الزراعي، سواء خلال حياة المستفيدين أو بعد وفاتهم، بما يشمل قضايا الإرث وانتقال الحقوق، مع مراعاة النظام القانوني الخاص بهذه الأراضي." },
        { title: "تصفية الشياع وقسمة الاستغلاليات الفلاحية", text: "مباشرة دعاوى القسمة القضائية للضيعات الفلاحية أو قسمة المهايأة الزمنية والمكانية، ومراعاة المساحة الدنيا للاستغلال المانعة للتفتيت وفق التشريعات الفلاحية الخاصة." },
        { title: "دعاوى التحديد، الترامي ونزاعات الارتفاقات", text: "مباشرة دعاوى منع المعارضة واسترداد الحيازة ضد الترامي، نزاعات ممرات المرور ومجاري مياه السقي، ومطالبة المحكمة بإجراء خبرات طبوغرافية لتحديد المعالم المندثرة." },
        { title: "نزع الملكية للمنفعة العامة وتحديد التعويض", text: "مؤازرة المالكين والفلاحين المنزوعة ملكيتهم أمام المحاكم الإدارية لمناقشة مشروعية المسطرة والمطالبة بتعويض عادل يراعي القيمة الحقيقية للأرض والمغروسات وفقدان الاستغلال (القانون 7.81)." },
        { title: "عقود الأكرية الفلاحية والشراكة في الاستغلال", text: "صياغة وتدقيق عقود الكراء الفلاحي، عقود المغارسة (المادة 265 من مدونة الحقوق العينية)، عقود المزارعة والمساقاة، ومنازعات إنهاء الاستغلال واسترداد الحيازة." },
      ],
      processTitle: "مراحل المعالجة القانونية والميدانية للملف الفلاحي",
      processIntro: "تبدأ معالجة النزاع الفلاحي من الميدان بمطابقة الرسوم والحدود الطبيعية والتحقق من الطبيعة القانونية الصرفة للوعاء العقاري.",
      process: [
        { title: "التحديد القانوني للنظام العقاري", text: "تشخيص طبيعة الأرض (ملك خاص محفظ، في طور التحفيظ، ملكية عدلية غير محفظة، أرض تابعة لتعاونيات الإصلاح الزراعي، أو أرض مسترجعة) وفحص سندات الحيازة والاستغلال." },
        { title: "جمع المستندات ومطابقة الحدود", text: "دراسة الرسوم العدلية، شواهد الملكية، تقارير المعاينة الميدانية، والوثائق الإدارية الصادرة عن مصالح المحافظة العقارية والجهات المختصة." },
        { title: "اختيار المسار الإجرائي المناسب", text: "مباشرة مسطرة التسوية الإدارية، اللجوء إلى قضاء التحفيظ أو القضاء الإداري، أو رفع دعوى استحقاقية أو قسمة أمام القضاء العادي." },
      ],
      faqTitle: "أسئلة شائعة حول الأراضي الفلاحية وأراضي تعاونيات الإصلاح الزراعي",
      faqIntro: "تتضمن هذه التوضيحات مبادئ توجيهية عامة، ولا تغني عن استشارة قانونية مخصصة وفحص معمق لوثائق الملكية والسندات الخاصة بكل حالة.",
      faqs: [
        { question: "ما هي خصوصية النزاعات المتعلقة بأراضي تعاونيات الإصلاح الزراعي؟", answer: "تخضع أراضي تعاونيات الإصلاح الزراعي لنظام قانوني خاص يحدد شروط الاستفادة والاستغلال؛ ويتدخل المكتب في معالجة القضايا والمنازعات المرتبطة بها سواء في حياة المستفيدين أو بعد وفاتهم، لا سيما ما يتعلق بانتقال الحقوق، وقضايا الإرث، وتسوية الوضعية القانونية للقطعة الفلاحية." },
        { question: "كيف تتم معالجة نزاعات الحدود والترامي على الأراضي الفلاحية غير المحفظة؟", answer: "تتم معالجة الترامي عبر إقامة دعوى استرداد الحيازة أو دعوى منع المعارضة داخل أجل سنة من تاريخ الاعتداء، مع إثبات وضع اليد الهادئ العلني، والمطالبة بندب خبير طبوغرافي محلف لتطبيق الرسوم العدلية ومقارنة المعالم والحدود المنصوص عليها في وثائق الطرفين." },
        { question: "هل يمكن قسمة ضيعة فلاحية موروثة بين عدة ورثة على الشياع؟", answer: "تخضع قسمة الأراضي الفلاحية لضوابط مدونة الحقوق العينية وللقوانين المانعة لتفتيت الملكيات الفلاحية دون الحد الأدنى للاستغلال المسطر قانوناً؛ فإذا تعذرت القسمة العينية يتم اللجوء إلى قسمة المهايأة (الانتفاع الدوري) أو إسناد الاستغلال لأحد الورثة مع أداء مقابل مالي، أو البيع بالمزاد العلني كحل أخير." },
        { question: "ما هي الحقوق المخولة للمالك في حال نزع ملكية أرضه الفلاحية للمنفعة العامة؟", answer: "يخول القانون رقم 7.81 للمالك المنزوعة ملكيته حق الطعن في مرسوم إعلان المنفعة العامة ومقرر التخلي أمام المحكمة الإدارية، والمطالبة بإعادة تقدير التعويض الاحتياطي عبر خبرة قضائية تأخذ بعين الاعتبار نوعية التربة، المغروسات، الآبار، التجهيزات الهيدروليكية، والموقع الاستراتيجي للأرض." },
        { question: "ما هي شروط صحة رسم الملكية (الملكية العدلية) في العقار الفلاحي؟", answer: "يجب أن يتضمن رسم الملكية العدلي الشروط الشرعية والقانونية المنصوص عليها في المادة 240 من مدونة الحقوق العينية (واضعاً يده، متصرفاً، تصرف المالك في ملكه، هادئاً، علنياً، دون منازع، منسوباً لأصل الملك، ومستوفياً للمدة المشترطة شرعاً وهي 10 سنوات بين الأجانب و40 سنة بين الأقارب)، مع بيان دقيق للمساحة والحدود." },
        { question: "كيف تتم معالجة قضايا الإرث وانتقال الحقوق في أراضي تعاونيات الإصلاح الزراعي؟", answer: "تخضع مسألة وفاة المستفيد من أراضي الإصلاح الزراعي لضوابط تشريعية خاصة تنظم استمرار الاستغلال وانتقال الحقوق لفائدة الورثة أو أحدهم وفق الشروط القانونية المقررة؛ ويتولى المكتب مواكبة الورثة في مساطر تسوية انتقال الحقوق وحل أي نزاع يطرأ بشأن الاستغلال أو التعويض." },
      ],
      related: [
        { key: "immobilier", label: "القانون العقاري والتحفيظ" },
        { key: "succession", label: "الميراث وتصفية التركات" },
      ],
      ctaTitle: "هل تواجهون نزاعاً عقارياً فلاحياً أو إشكالاً في أراضي تعاونيات الإصلاح الزراعي؟",
      ctaText: "تفضلوا بعرض رسومكم ومستنداتكم على مكتب الأستاذ عبد الرزاق الرويسي بالمحمدية لتقييم الوضع القانوني ورسم الخطة القضائية لحماية حقوقكم واستغلاليتكم.",
    },
  },
};
