import type { ServicePageDefinition } from "@/lib/service-page-types";

export const foncierRuralPage: ServicePageDefinition = {
  key: "foncierRural",
  index: "03",
  content: {
    fr: {
      slug: "droit-foncier-rural",
      seo: {
        title: "Avocat terres agricoles et foncier rural au Maroc",
        description: "Avocat en foncier rural au Maroc : terres agricoles, Soulaliyates, indivision, bornage et expropriation à Benslimane, Chaouia et Mohammedia.",
      },
      eyebrow: "Foncier rural · Terres agricoles · Maroc",
      h1: "Avocat en terres agricoles et foncier rural au Maroc",
      lead: "Maître Abderrazak Errouissi accompagne familles, agriculteurs et exploitants dans les conflits de propriété, d’héritage, de bornage et d’usage touchant les terres rurales.",
      summary: [
        "Un terrain agricole ne peut pas être traité comme un simple bien urbain. Avant toute action, il faut identifier son statut, l’origine des droits, les actes disponibles, l’occupation réelle, les limites physiques et les éventuelles décisions administratives qui l’affectent.",
        "Le cabinet intervient depuis Mohammedia dans les dossiers situés notamment à Benslimane, dans la Chaouia et dans d’autres régions du Maroc. Son analyse relie droit foncier, succession et réalité de l’exploitation afin d’éviter qu’un conflit familial ou une limite incertaine ne bloque durablement la terre.",
        "Melkiya, titre foncier, terre collective ou bien en indivision n’obéissent pas à la même logique de preuve et de procédure. La première étape consiste donc à qualifier précisément le terrain avant de choisir négociation, expertise, démarche administrative ou action judiciaire.",
      ],
      servicesTitle: "Défendre la terre, ses limites et sa transmission",
      servicesIntro: "Le cabinet rassemble les pièces, reconstitue l’origine des droits et confronte les documents à la situation effective du terrain agricole.",
      services: [
        { title: "Terres agricoles Melk et Melkiya", text: "Étude des actes de propriété non immatriculée, de la possession, des témoignages et des transmissions successives, puis articulation avec une éventuelle procédure d’immatriculation." },
        { title: "Terres Soulaliyates et terres collectives", text: "Analyse du statut de la terre, de la qualité invoquée par les ayants droit et des actes ou décisions administratives avant toute contestation ou opération." },
        { title: "Indivision et sortie du الشياع", text: "Partage amiable ou judiciaire des fermes et parcelles héritées, droits des cohéritiers, exploitation exclusive et blocage d’un bien rural détenu à plusieurs." },
        { title: "Bornage, limites et empiètement", text: "Conflits de limites entre parcelles, accès, chemins, occupation d’une bande de terrain et examen des plans, constats, expertises et repères matériels." },
        { title: "Expropriation et indemnisation", text: "Examen de la procédure, des notifications, de la consistance du bien et des éléments utiles à la discussion de l’indemnité, sans préjuger de l’évaluation retenue." },
        { title: "Vente, bail et exploitation agricole", text: "Vérification du statut du terrain, des pouvoirs du cédant ou bailleur et des risques liés à l’usage, à l’accès, à l’eau ou à l’indivision avant engagement." },
      ],
      processTitle: "Partir du statut réel de la terre",
      processIntro: "En matière rurale, une stratégie solide commence par la concordance entre l’acte, la parcelle, les limites et les personnes qui revendiquent ou exercent les droits.",
      process: [
        { title: "Qualifier le terrain", text: "Déterminer le statut foncier, l’origine de propriété, l’existence d’un titre et la situation d’occupation ou d’exploitation." },
        { title: "Reconstituer les droits", text: "Rassembler Melkiya, actes, certificats, plans, documents successoraux, décisions, constats et éléments de possession." },
        { title: "Choisir la voie utile", text: "Organiser une négociation, une expertise, une démarche administrative ou une procédure adaptée à la nature exacte du conflit." },
      ],
      faqTitle: "Questions fréquentes sur les terres agricoles",
      faqIntro: "Le statut foncier et les documents disponibles changent entièrement la solution. Ces repères généraux ne remplacent pas l’étude de la parcelle et de son historique.",
      faqs: [
        { question: "Quelle différence entre une Melkiya et un titre foncier ?", answer: "La Melkiya constitue un acte invoqué pour établir une propriété non immatriculée, tandis que le titre foncier résulte de l’immatriculation et retrace les droits inscrits sur l’immeuble. Leur force, leurs mentions et les voies de contestation ne s’analysent donc pas de la même manière." },
        { question: "Comment régler un conflit de bornage sur un terrain rural ?", answer: "Il faut comparer les actes, plans, limites matérielles, accès et occupations, puis apprécier l’utilité d’un constat ou d’une expertise. À Benslimane et dans la Chaouia, l’historique des parcelles et des transmissions est souvent déterminant." },
        { question: "Comment sortir de l’indivision d’une terre agricole ?", answer: "Les coindivisaires peuvent rechercher une répartition amiable si elle est juridiquement et matériellement possible. À défaut d’accord, une demande de partage peut être étudiée en tenant compte du statut de la terre, de sa divisibilité et des droits de chacun." },
        { question: "Peut-on partager une ferme entre plusieurs héritiers ?", answer: "Le partage dépend des titres, de la configuration de l’exploitation, des droits successoraux et de la possibilité réelle de diviser sans méconnaître le statut applicable. Une évaluation et une solution d’attribution ou de cession peuvent aussi être examinées." },
        { question: "Que faire en cas d’expropriation d’un terrain agricole ?", answer: "Il convient de vérifier les actes et notifications, d’identifier exactement la parcelle et de réunir les éléments concernant sa consistance et son exploitation. Les délais et voies de contestation doivent être examinés dès réception des documents." },
        { question: "Comment contester une décision concernant une terre Soulaliyate ?", answer: "Il faut d’abord déterminer le statut collectif du terrain, la qualité de l’intéressé et l’autorité ou la décision concernée. Les documents familiaux, administratifs et fonciers orientent ensuite la démarche appropriée." },
      ],
      related: [
        { key: "immobilier", label: "Droit immobilier" },
        { key: "succession", label: "Successions rurales" },
      ],
      ctaTitle: "Une terre agricole est bloquée ou contestée ?",
      ctaText: "Apportez Melkiya, titre, plan, documents successoraux et décisions reçues pour qualifier le terrain et identifier les premières mesures utiles.",
    },
    ar: {
      slug: "العقار-الفلاحي-وأراضي-الجموع",
      seo: {
        title: "محامي الأراضي الفلاحية وأراضي الجموع بالمغرب",
        description: "محامي العقار الفلاحي بالمغرب لقضايا أراضي الجموع والشياع والتحديد ونزع الملكية ببنسليمان والشاوية والمحمدية.",
      },
      eyebrow: "العقار الفلاحي · أراضي الجموع · المغرب",
      h1: "محامي الأراضي الفلاحية وأراضي الجموع بالمغرب",
      lead: "يرافق الأستاذ عبد الرزاق الرويسي الأسر والفلاحين والمستغلين في نزاعات الملكية والإرث والتحديد والانتفاع المرتبطة بالأراضي القروية.",
      summary: [
        "لا يمكن التعامل مع الأرض الفلاحية كعقار حضري عادي. يجب أولاً تحديد وضعها القانوني وأصل الحقوق والعقود المتوفرة والحيازة الفعلية والحدود والقرارات الإدارية التي قد تمسها.",
        "يتدخل المكتب من المحمدية في ملفات ببنسليمان والشاوية ومناطق أخرى من المغرب. ويربط التحليل بين القانون العقاري والميراث وواقع الاستغلال حتى لا يبقى النزاع العائلي أو غموض الحدود سبباً في تعطيل الأرض.",
        "الملكية والعقار المحفظ وأراضي الجموع والعقار المشاع أوضاع مختلفة من حيث الإثبات والمساطر. لذلك تبدأ المعالجة بتكييف وضع الأرض قبل اختيار التفاوض أو الخبرة أو المسطرة الإدارية أو الدعوى القضائية.",
      ],
      servicesTitle: "حماية الأرض وحدودها وانتقالها بين الأجيال",
      servicesIntro: "يجمع المكتب الوثائق ويعيد بناء أصل الحقوق ويقارن المستندات بالوضع الفعلي للأرض الفلاحية.",
      services: [
        { title: "الأراضي الملكية والملكية", text: "دراسة رسوم الملكية والحيازة والشهادات والتفويتات المتعاقبة، وربطها عند الاقتضاء بمسطرة التحفيظ العقاري." },
        { title: "أراضي الجموع والأراضي السلالية", text: "فحص وضع الأرض وصفة ذوي الحقوق والقرارات والوثائق الإدارية قبل أي تعرض أو تصرف." },
        { title: "الشياع والخروج من الشياع", text: "القسمة الرضائية أو القضائية للضيعات والأراضي الموروثة، وحقوق الورثة والاستغلال المنفرد وتعطيل العقار المشترك." },
        { title: "التحديد والتعدي على الحدود", text: "نزاعات الحدود والممرات واحتلال جزء من الأرض، مع فحص التصاميم والمعاينات والخبرة والعلامات الموجودة بالميدان." },
        { title: "نزع الملكية والتعويض", text: "دراسة المسطرة والإشعارات ووصف العقار والعناصر المفيدة لمناقشة التعويض دون ضمان التقييم الذي قد يعتمد." },
        { title: "بيع وكراء واستغلال الأرض", text: "التحقق من وضع الأرض وصفة البائع أو المكري ومخاطر الاستعمال والولوج والماء والشياع قبل الالتزام." },
      ],
      processTitle: "الانطلاق من الوضع الحقيقي للأرض",
      processIntro: "تبدأ الاستراتيجية المتينة بمطابقة العقد مع القطعة والحدود والأشخاص الذين يدعون الحقوق أو يمارسونها.",
      process: [
        { title: "تكييف وضع الأرض", text: "تحديد النظام العقاري وأصل الملكية ووجود رسم عقاري ووضع الحيازة أو الاستغلال." },
        { title: "إعادة بناء الحقوق", text: "جمع الملكية والعقود والشهادات والتصاميم ووثائق الإرث والقرارات والمعاينات وأدلة الحيازة." },
        { title: "اختيار المسطرة المفيدة", text: "تنظيم تفاوض أو خبرة أو إجراء إداري أو دعوى تتناسب مع الطبيعة الدقيقة للنزاع." },
      ],
      faqTitle: "أسئلة شائعة حول الأراضي الفلاحية",
      faqIntro: "يغير وضع الأرض والوثائق المتوفرة طريقة الحل بالكامل. وتبقى دراسة القطعة وتاريخها ضرورية لكل ملف.",
      faqs: [
        { question: "ما الفرق بين الملكية والرسم العقاري؟", answer: "الملكية وثيقة يُستند إليها لإثبات عقار غير محفظ، أما الرسم العقاري فينتج عن التحفيظ ويتضمن الحقوق المقيدة على العقار. لذلك تختلف قوة الوثيقتين وبياناتهما وطرق المنازعة المرتبطة بكل واحدة." },
        { question: "كيف أحل نزاع تحديد أرض فلاحية؟", answer: "يجب مقارنة العقود والتصاميم والحدود المادية والممرات والحيازة، ثم تقييم الحاجة إلى معاينة أو خبرة. ويكون تاريخ القطع والتفويتات مهماً في ملفات بنسليمان والشاوية." },
        { question: "كيف يتم الخروج من الشياع في أرض فلاحية؟", answer: "يمكن للشركاء البحث عن قسمة رضائية إذا كانت ممكنة قانوناً وواقعاً. وعند غياب الاتفاق يمكن دراسة القسمة القضائية بحسب وضع الأرض وقابليتها للقسمة وحقوق كل طرف." },
        { question: "هل يمكن تقسيم ضيعة فلاحية بين الورثة؟", answer: "يتوقف الأمر على الرسوم وشكل الاستغلال والأنصبة وقابلية التقسيم مع احترام النظام المطبق. ويمكن أيضاً دراسة الإسناد لأحد الورثة أو التفويت بحسب الحالة." },
        { question: "ماذا أفعل عند نزع ملكية أرض فلاحية؟", answer: "ينبغي فحص العقود والإشعارات وتحديد القطعة وجمع عناصر وصفها واستغلالها. كما يجب التحقق سريعاً من الآجال والمساطر الممكنة بعد التوصل بالوثائق." },
        { question: "كيف أطعن في قرار يخص أرضاً من أراضي الجموع؟", answer: "يجب أولاً تحديد الوضع الجماعي للأرض وصفة المعني والقرار أو الجهة المعنية. ثم توجه الوثائق العائلية والإدارية والعقارية نحو المسطرة المناسبة." },
      ],
      related: [
        { key: "immobilier", label: "القانون العقاري" },
        { key: "succession", label: "ميراث الأراضي" },
      ],
      ctaTitle: "هل الأرض الفلاحية متوقفة أو محل نزاع؟",
      ctaText: "أحضروا الملكية أو الرسم والتصميم ووثائق الإرث والقرارات المتوصل بها لتكييف وضع الأرض وتحديد الإجراءات الأولى.",
    },
  },
};
