import type { ServicePageDefinition } from "@/lib/service-page-types";

export const immobilierPage: ServicePageDefinition = {
  key: "immobilier",
  index: "01",
  content: {
    fr: {
      slug: "droit-immobilier",
      seo: {
        title: "Avocat immobilier à Mohammedia et Casablanca",
        description: "Avocat immobilier au Maroc : titres fonciers, vente, location et litiges à Mohammedia et Casablanca. Analyse rigoureuse depuis 1992.",
      },
      eyebrow: "Droit immobilier · Foncier · Maroc",
      h1: "Avocat immobilier à Mohammedia et Casablanca",
      lead: "Maître Abderrazak Errouissi conseille et défend particuliers, entreprises et agriculteurs dans leurs opérations immobilières et leurs litiges fonciers au Maroc.",
      summary: [
        "Un dossier immobilier engage souvent un patrimoine important. Avant une acquisition, une vente, une location ou un transfert de propriété, le cabinet examine les actes, le titre foncier, les droits inscrits et les risques de contestation.",
        "En cas de conflit, l’intervention est adaptée à la situation : négociation, mise en demeure, médiation, expertise ou procédure judiciaire. Le cabinet intervient depuis Mohammedia dans le ressort de Casablanca et, selon le dossier, partout au Maroc.",
        "En zone rurale, la distinction entre une Melkiya et un titre foncier est décisive. La Melkiya participe à la preuve d’une propriété non immatriculée, tandis que le titre foncier résulte de l’immatriculation et porte les droits inscrits. Le cabinet examine aussi la possession, les plans et les limites matérielles, notamment dans les litiges de bornage à Benslimane et dans la Chaouia.",
      ],
      servicesTitle: "Sécuriser le bien, l’acte et la procédure",
      servicesIntro: "Chaque dossier commence par une lecture des pièces et de la situation foncière afin de définir une stratégie proportionnée aux enjeux.",
      services: [
        { title: "Titre foncier et conservation foncière", text: "Analyse du certificat de propriété, des inscriptions, hypothèques, saisies et servitudes. Accompagnement dans les procédures d’immatriculation, d’opposition et de rectification." },
        { title: "Achat, vente et transfert de propriété", text: "Vérification juridique de l’opération, lecture des avant-contrats et actes, difficultés d’exécution, refus de régularisation ou contestation du transfert." },
        { title: "Litiges immobiliers et fonciers", text: "Conflits de propriété, occupation sans droit, bornage, empiètement, possession, revendication et inexécution d’obligations liées à un bien." },
        { title: "Baux et rapports locatifs", text: "Baux civils ou commerciaux, loyers impayés, résiliation, expulsion, renouvellement et différends entre bailleur et locataire." },
        { title: "Indivision et biens successoraux", text: "Gestion des biens détenus à plusieurs, sortie d’indivision, partage judiciaire et articulation entre droit immobilier et succession." },
        { title: "Melkiya, titre foncier et bornage rural", text: "Comparaison des actes avec la situation de la parcelle, examen de la possession, des plans et des limites en cas d’empiètement ou de conflit de bornage dans les zones rurales de Benslimane et de la Chaouia." },
      ],
      processTitle: "Une méthode lisible à chaque étape",
      processIntro: "Aucune issue n’est promise. Le cabinet établit en revanche un diagnostic clair, documente les risques et explique les options disponibles.",
      process: [
        { title: "Étude des pièces", text: "Titre foncier, contrats, plans, correspondances, décisions et chronologie du dossier." },
        { title: "Qualification juridique", text: "Identification des droits en présence, des délais utiles et de la juridiction ou procédure appropriée." },
        { title: "Stratégie et action", text: "Recherche d’une solution négociée lorsqu’elle protège les intérêts, ou engagement de la procédure adaptée." },
      ],
      faqTitle: "Questions fréquentes en droit immobilier",
      faqIntro: "Ces réponses donnent des repères généraux. Une consultation et l’examen des documents restent nécessaires pour apprécier un cas particulier.",
      faqs: [
        { question: "Comment vérifier un titre foncier au Maroc ?", answer: "Il convient notamment d’obtenir un certificat de propriété récent et d’examiner les inscriptions qui affectent le bien : hypothèque, saisie, servitude ou autre charge. L’analyse doit être rapprochée des actes et de la situation réelle du bien." },
        { question: "Que faire en cas de litige sur la propriété d’un terrain ?", answer: "Il faut réunir les titres, actes, plans, preuves de possession et échanges disponibles. La stratégie dépend ensuite du statut foncier du terrain, de la nature de la contestation et des délais applicables." },
        { question: "Combien coûte une procédure immobilière ?", answer: "Le coût varie selon la complexité, les actes nécessaires, une éventuelle expertise, les frais judiciaires et la durée prévisible. Le cabinet précise les honoraires et dépenses envisageables après une première analyse du dossier." },
        { question: "Peut-on vendre un bien immobilier en indivision ?", answer: "La cession et le partage d’un bien indivis dépendent des droits de chaque indivisaire et de l’accord possible entre eux. À défaut d’accord, une procédure de partage peut être envisagée après étude des titres et de l’origine de l’indivision." },
        { question: "Quelle différence entre une Melkiya et un titre foncier au Maroc ?", answer: "La Melkiya est un acte invoqué pour établir la propriété d’un bien non immatriculé. Le titre foncier est créé à l’issue de l’immatriculation et retrace les droits inscrits. La preuve, les formalités et les voies de contestation doivent donc être analysées selon le statut exact du terrain." },
        { question: "Que faire lors d’un conflit de bornage à Benslimane ou dans la Chaouia ?", answer: "Il faut réunir les actes, plans, repères de terrain, constats et éléments de possession, puis comparer les limites documentaires à l’occupation réelle. Une expertise ou une procédure peut être envisagée selon le statut foncier et la nature de l’empiètement." },
      ],
      related: [
        { key: "succession", label: "Successions et héritage" },
        { key: "foncierRural", label: "Foncier rural et agricole" },
      ],
      ctaTitle: "Un bien ou un litige immobilier à sécuriser ?",
      ctaText: "Présentez votre situation et les documents disponibles au cabinet de Mohammedia afin d’identifier les premières mesures utiles.",
    },
    ar: {
      slug: "القانون-العقاري",
      seo: {
        title: "محامٍ في قضايا العقار والتحفيظ العقاري بالمحمدية والدار البيضاء",
        description: "محامٍ في النزاعات العقارية والتحفيظ العقاري بالمغرب: الرسوم العقارية، التعرضات، دعاوى الاستحقاق، وعقود البيع والكراء بالمحمدية والدار البيضاء ومختلف المحاكم.",
      },
      eyebrow: "القانون العقاري · التحفيظ العقاري · المغرب",
      h1: "محامٍ في قضايا العقار والتحفيظ العقاري بالمحمدية والدار البيضاء",
      lead: "يؤازر الأستاذ عبد الرزاق الرويسي، محامٍ بهيئة الدار البيضاء مقبول لدى محكمة النقض، الخواص والشركات والفاعلين العقاريين في المعاملات العقارية، مساطر التحفيظ، ودعاوى النزاع العقاري بالمغرب.",
      summary: [
        "تمثل الأصول العقارية عماد الذمة المالية ومحور الاستثمارات الكبرى. لذا يتولى المكتب الفحص الدقيق للشواهد العقارية الصادرة عن الوكالة الوطنية للمحافظة العقارية، وكافة التقييدات والارتفاقات والرهون الرسمية والتقييدات الاحتياطية قبل إبرام أي تفويت أو التزام عقاري.",
        "عند نشوب نزاع، يرسم المكتب الاستراتيجية الإجرائية الفعالة: مساطر التقييد الاحتياطي التحفظية (الفصلان 85 و86 من ظهير التحفيظ العقاري)، مفاوضات الصلح، مساطر الخبرة القضائية الطبوغرافية، أو إقامة دعاوى الاستحقاق وبطلان التصرفات أمام المحاكم المختصة.",
        "في المجال القروي، تُعد التفرقة بين العقار المحفظ والعقار غير المحفظ (الخاضع للملكية العدلية وقواعد الحيازة المكسبة بالاستحقاق) حاسمة في الإثبات؛ حيث يُخضع المكتب رسوم الملكية القديمة والتصاميم الهندسية لتدقيق صارم، لا سيما في دعاوى التحديد ومنازعات الترامي ببنسليمان والشاوية وسائر مناطق المملكة.",
      ],
      servicesTitle: "صيانة الحقوق العقارية وتأمين المعاملات والتقاضي",
      servicesIntro: "تنطلق مؤازرة المكتب من تشخيص قانوني وميداني للرسوم والوثائق لتحديد المسطرة القضائية الفعالة والموازنة بين التكاليف والمصالح المرجوة.",
      services: [
        { title: "التحفيظ العقاري والمساطر لدى المحافظة العقارية", text: "فحص شواهد الملكية، الرهون الرسمية، الحجوزات والارتفاقات، ومباشرة مطالب التحفيظ، ومساطر التعرض والتقييدات الاحتياطية وإلغائها وتصحيح القيود." },
        { title: "عقود البيع والوعد بالبيع ونقل الملكية", text: "تدقيق عقود البيع التوثيقية والعدلية والمحررة من طرف المحامي المقبول لدى محكمة النقض (المادة 4 من مدونة الحقوق العينية)، ودعاوى إتمام البيع والفسخ واسترجاع العربون." },
        { title: "المنازعات العقارية ودعاوى الاستحقاق", text: "مباشرة دعاوى الاستحقاق العقاري، استرداد الحيازة، رفع التعدي والترامي، إزالة المنشآت وتعيين الحدود طبوغرافياً." },
        { title: "الأكرية المدنية والتجارية والمهنية", text: "تطبيق مقتضيات القانون 49.16 المتعلق بكراء العقارات التجارية والحرفية والصناعية والقانون 67.12 للأكرية السكنية والمهنية، ودعاوى الإفراغ واستيفاء الوجيبة الكرائية والتعويض عن إنهاء الكراء." },
        { title: "قسمة العقارات المشاعة وتصفية التركات", text: "تصفية الشياع رضاءً أو قضاءً بمقتضى مدونة الحقوق العينية، ممارسة حق الشفعة (الفصل 304 وما بعده)، وقسمة التركات العقارية تجنباً للجمود أو البيع بالمزاد بأبخس الأثمان." },
        { title: "تدقيق الملكية العدلية ومنازعات الحدود القروية", text: "فحص ومطابقة رسوم الملكية (الملكية العدلية) وعقود الاستمرار، ودراسة شروط الحيازة والتقادم المكسب وتحديد معالم العقار في النزاعات الفلاحية والقروية." },
      ],
      processTitle: "مراحل المعالجة الإجرائية من التشخيص إلى صدور الحكم وتنفيذه",
      processIntro: "لا نقدم وعوداً جزافية بالنتائج، بل نلتزم بأعلى معايير الدقة والصرامة الإجرائية وتنوير الموكل بكافة احتمالات الدعوى ومخاطرها.",
      process: [
        { title: "التدقيق الوثائقي والميداني", text: "فحص الرسوم العقارية والعدلية، التصاميم الهندسية، الإنذارات والمراسلات، وحصر التسلسل الزمني للوقائع." },
        { title: "التكييف القانوني وتحديد المسطرة", text: "تحديد طبيعة الدعوى (عينية، شخصية عقارية، أو تحفظية)، التدقيق في الاختصاص النوعي والمحلي ومراعاة الآجال القانونية المسقطة." },
        { title: "مباشرة الترافع والصلح والتنفيذ", text: "صياغة المذكرات والمقالات الافتتاحية بدقة، حضور جلسات البحث والخبرات الميدانية، ومتابعة تنفيذ الأحكام العقارية عبر مؤسسة كتابة الضبط." },
      ],
      faqTitle: "أسئلة شائعة في القانون العقاري والمنازعات الفلاحية",
      faqIntro: "هذه التوضيحات تقدم خطوطاً إرشادية عامة، وتظل دراسة وثائق الملكية والظروف الواقعية لكل نازلة ضرورية لتشخيص الموقف القانوني بدقة.",
      faqs: [
        { question: "كيف يتم التحقق من سلامة الوضعية القانونية للرسم العقاري بالمغرب؟", answer: "يتعين سحب شهادة ملكية عقارية حديثة وتصميم عقاري من الوكالة الوطنية للمحافظة العقارية، والتأكد من خلو الرسم من أي تقييد احتياطي، رهن رسمي، حجز تحفظي، أو ارتفاق يحد من التصرف، ومطابقة البيانات الطبوغرافية مع واقع العقار على الأرض." },
        { question: "ما الإجراءات الواجب اتخاذها عند نشوب نزاع حول ملكية عقار أو ترامٍ عليه؟", answer: "يتعين جمع سندات الملكية فوراً، وإنجاز محضر معاينة بواسطة مفوض قضائي لإثبات واقعة الاعتداء على الحيازة، ومباشرة مسطرة الأمر القضائي بإجراء حراسة قضائية أو تقييد احتياطي بناء على دعوى في الموضوع طبقاً للفصل 85 من ظهير التحفيظ العقاري لحفظ الحقوق من التصرف والتفويت." },
        { question: "كيف تُحدد مصاريف وأتعاب الدعاوى العقارية؟", answer: "تُحدد الأتعاب باتفاق مسبق شفاف يراعي جسامة النزاع وقيمة العقار والجهد الميداني، بالإضافة إلى الرسوم القضائية المقررة قانوناً ومصاريف أتعاب الخبراء الطبوغرافيين التي تأمر بها المحكمة." },
        { question: "هل يحق لأحد الشركاء على الشياع بيع حصته، وكيف يتصرف باقي الشركاء؟", answer: "يحق للشريك التصرف في حصته الشائعة، غير أنه يثبت لباقي الشركاء على الشياع ممارسة حق الشفعة لأخذ الحصة المبيعة بثمنها ومصروفاتها، شريطة التقيد بالآجال القانونية الصارمة وإيداع الثمن بصندوق المحكمة (المادة 306 من مدونة الحقوق العينية)." },
        { question: "ما الفرق الجوهري بين رسم الملكية (الملكية العدلية) والرسم العقاري؟", answer: "الرسم العقاري يحظى بحجية قاطعة ومطلقة تُطهر العقار من كافة الحقوق السالفة غير المسجلة وفق مقتضيات ظهير 12 غشت 1913 المعدل بالقانون 14.07، في حين يخضع رسم الملكية العدلي لقواعد الإثبات الفقهية وقابل للطعن بالاستحقاق أو إثبات حيازة أقوى." },
        { question: "كيف يتم فض نزاعات التحديد وتداخل الحدود في الأراضي القروية؟", answer: "تتم معالجة نزاعات الحدود الفلاحية عبر فحص الرسوم القديمة وحدود الجوار ومعالم الأرض الطبيعية، ومطالبتها بندب خبير مساح طبوغرافي محلف لتطبيق الرسوم على الأرض بدقة وتحديد معالم كل ملك وفقاً للقانون." },
      ],
      related: [
        { key: "succession", label: "الميراث وتصفية التركات" },
        { key: "foncierRural", label: "العقار الفلاحي والقروي" },
      ],
      ctaTitle: "هل لديكم نزاع عقاري أو ترغبون في تأمين عملية تفويت عقاري؟",
      ctaText: "بادروا بعرض وثائقكم ورسومكم على مكتبنا بالمحمدية لدراستها وتحديد المساطر التحفظية والقضائية الكفيلة بحماية حقوقكم وصيانتها.",
    },
  },
};
