import type { ServicePageDefinition } from "@/lib/service-page-types";

export const successionPage: ServicePageDefinition = {
  key: "succession",
  index: "02",
  content: {
    fr: {
      slug: "succession-heritage",
      seo: {
        title: "Avocat succession et héritage au Maroc",
        description: "Avocat en succession au Maroc : héritage, partage, indivision et conflits entre héritiers à Mohammedia et Casablanca. Cabinet depuis 1992.",
      },
      eyebrow: "Succession · Héritage · Partage",
      h1: "Avocat en succession et héritage au Maroc",
      lead: "Le cabinet accompagne les héritiers dans l’identification des droits, la liquidation de la succession, le partage des biens et la résolution des conflits familiaux ou patrimoniaux.",
      summary: [
        "Une succession peut réunir des questions familiales, immobilières, bancaires et fiscales. L’inventaire des biens, l’établissement de la qualité d’héritier et l’analyse des actes permettent de distinguer ce qui peut être réglé amiablement de ce qui nécessite une procédure.",
        "Maître Abderrazak Errouissi intervient pour les successions situées à Mohammedia, Casablanca et ailleurs au Maroc, y compris lorsque des héritiers résident à l’étranger ou que la succession comprend un terrain, un logement, un commerce ou des parts sociales.",
        "Lorsqu’une ferme ou une terre agricole reste en indivision, le conflit porte souvent autant sur l’exploitation que sur les quotes-parts : occupation par un seul héritier, revenus non partagés, refus d’accès, limites incertaines ou désaccord sur la vente. Le cabinet relie alors les droits successoraux au statut foncier et à la réalité rurale du bien.",
      ],
      servicesTitle: "Clarifier les droits et organiser le partage",
      servicesIntro: "L’objectif est de préserver les droits de chacun tout en recherchant, lorsque les conditions le permettent, une issue qui évite l’enlisement du patrimoine.",
      services: [
        { title: "Identification des héritiers et des biens", text: "Étude des documents d’état civil, actes d’hérédité, titres de propriété, comptes, créances et dettes composant la succession." },
        { title: "Partage amiable de la succession", text: "Préparation de la négociation entre héritiers, examen des évaluations et formalisation d’un accord conforme aux droits de chacun." },
        { title: "Partage judiciaire et sortie d’indivision", text: "Action lorsque l’accord est impossible, avec traitement des biens indivis, demandes d’expertise et opérations de liquidation." },
        { title: "Conflits entre héritiers", text: "Contestation d’actes, occupation ou gestion exclusive d’un bien, dissimulation alléguée d’éléments de la succession et blocage des opérations." },
        { title: "Succession immobilière ou internationale", text: "Coordination des aspects successoraux et fonciers, notamment lorsque des biens sont au Maroc et que certains héritiers vivent à l’étranger." },
        { title: "Fermes et terres agricoles en indivision", text: "Conflits ruraux entre cohéritiers, exploitation exclusive, partage des récoltes ou revenus, accès à la parcelle, sortie d’indivision et partage d’une exploitation familiale." },
      ],
      processTitle: "Transformer une situation familiale en dossier structuré",
      processIntro: "Le cabinet distingue les faits établis, les points contestés et les documents manquants avant de recommander une négociation ou une procédure.",
      process: [
        { title: "Reconstituer la succession", text: "Identifier les héritiers, les actifs, les dettes, les actes et les éventuelles opérations antérieures." },
        { title: "Évaluer les options", text: "Comparer partage amiable, maintien temporaire de l’indivision, cession de droits ou partage judiciaire." },
        { title: "Formaliser ou agir", text: "Sécuriser l’accord obtenu ou saisir la juridiction compétente lorsque le blocage persiste." },
      ],
      faqTitle: "Questions fréquentes sur l’héritage au Maroc",
      faqIntro: "Les droits dépendent de la situation familiale, de la nature des biens et des documents disponibles. Ces réponses ne remplacent pas une analyse individualisée.",
      faqs: [
        { question: "Comment faire le partage d’un héritage au Maroc ?", answer: "Il faut d’abord déterminer les héritiers et inventorier les biens et dettes. Un partage amiable peut être préparé si tous les intéressés s’accordent. En cas de désaccord, le partage peut être demandé en justice selon la nature des biens." },
        { question: "Que faire si un héritier refuse le partage ?", answer: "Il convient de vérifier les droits de chacun, les titres et les possibilités de règlement amiable. Si le blocage demeure, une action en partage ou d’autres mesures adaptées à la situation peuvent être envisagées." },
        { question: "Combien coûte une procédure de succession ?", answer: "Le coût dépend du nombre de biens et d’héritiers, de la nécessité d’une expertise, des formalités foncières et de l’existence d’un contentieux. Une estimation ne peut être donnée qu’après examen du dossier." },
        { question: "Un héritier vivant à l’étranger peut-il agir au Maroc ?", answer: "Oui, selon le dossier, il peut accomplir certaines démarches par l’intermédiaire d’un mandataire et être représenté dans une procédure. Les pouvoirs et documents étrangers doivent être préparés avec soin." },
        { question: "Comment partager un bien immobilier hérité ?", answer: "Le partage peut être matériel si le bien est divisible, résulter d’une attribution ou d’une vente, ou être ordonné judiciairement. Le titre foncier, la valeur du bien et les droits de chaque héritier sont déterminants." },
        { question: "Comment sortir de l’indivision d’une terre agricole héritée ?", answer: "Il faut vérifier le statut foncier, les droits de chaque héritier, la configuration de la parcelle et sa divisibilité. Un partage amiable, une attribution, une cession ou une procédure de partage peuvent être étudiés selon la situation." },
        { question: "Que faire si un héritier exploite seul la ferme familiale ?", answer: "Il convient de documenter l’occupation, les revenus, les dépenses, les accords antérieurs et les droits de chacun. Une discussion encadrée, des comptes entre cohéritiers ou une action liée au partage et à l’usage du bien peuvent être envisagés après analyse." },
        { question: "Peut-on partager une ferme sans interrompre son exploitation ?", answer: "Cela dépend de la configuration, du statut de la terre et de l’accord des héritiers. Une attribution avec compensation, une organisation conventionnelle ou une autre solution peut parfois préserver l’unité économique mieux qu’une division matérielle." },
      ],
      related: [
        { key: "immobilier", label: "Droit immobilier" },
        { key: "foncierRural", label: "Terres agricoles" },
      ],
      ctaTitle: "Une succession est bloquée ou contestée ?",
      ctaText: "Apportez les actes d’hérédité, titres et échanges disponibles pour obtenir une première lecture structurée de la situation.",
    },
    ar: {
      slug: "الميراث-والتركات",
      seo: {
        title: "محامٍ في قضايا الميراث وقسمة التركات بالمغرب | الأستاذ عبد الرزاق الرويسي",
        description: "محامٍ في تصفية التركات وقسمة الميراث بالمغرب: الخروج من الشياع، دعاوى القسمة القضائية، تصفية العقارات والضيعات الموروثة، وحل النزاعات بين الورثة بالمحمدية والدار البيضاء.",
      },
      eyebrow: "قضايا الميراث · تصفية التركات · القسمة القضائية",
      h1: "محامٍ في قضايا الميراث وقسمة التركات بالمغرب",
      lead: "يؤازر مكتب الأستاذ عبد الرزاق الرويسي، محامٍ بهيئة الدار البيضاء مقبول لدى محكمة النقض، الورثة وذوي الحقوق في حصر التركات وتصفيتها، دعاوى القسمة الرضائية والقضائية، وفض النزاعات العائلية والعقارية المعقدة بالمغرب.",
      summary: [
        "تتطلب قضايا التركات إلماماً دقيقاً بأحكام الفقه المالكي ومدونة الأسرة (المادة 322 وما بعدها)، وقواعد التحفيظ العقاري ومدونة الحقوق العينية (المواد 27 إلى 315). ويتولى المكتب إعداد جرد شرعي وقانوني شامل للحقوق العينية، الديون التوثيقية، والودائع البنكية والشركات التجارية التابعة للتركة.",
        "يباشر المكتب إجراءات التفاوض لإبرام مخارجات وقسمات رضائية موثقة تصون الروابط الأسرية؛ وعند تعذر الاتفاق يقود دعاوى القسمة القضائية أمام المحاكم الابتدائية ومحاكم الاستئناف، مع المطالبة بإجراء خبرات تقييمية عقارية منصفة أو تصفية التركة طبقاً للقانون.",
        "في الاستغلاليات الفلاحية والضيعات المشاعة، يحرص المكتب على تطبيق قواعد المهايأة الزمنية أو المكانية، أو إسناد الاستغلال لأحد الورثة بمُعدَّل القسمة لتفادي تجزئة الأراضي دون الحد الأدنى، أو بيعها بالمزاد العلني بأثمان بخسة تلحق الضرر بكافة الشركاء.",
      ],
      servicesTitle: "حصر التركات، قسمة الأموال الشائعة وحماية حقوق الورثة",
      servicesIntro: "تهدف استراتيجية المكتب إلى حماية الحقوق الشرعية والقانونية لكل وارث وتفادي الجمود القضائي الطويل لأموال التركة.",
      services: [
        { title: "حصر التركة وتحديد الورثة والديون", text: "دراسة وتدقيق رسوم الوراثة، الوصايا، عقود الإبراء والهبات، حصر عناصر الأصول العقارية والمنقولة والديون المترتبة على التركة طبقاً للمادة 322 من مدونة الأسرة." },
        { title: "القسمة الرضائية وإبرام المخارجة", text: "إدارة المفاوضات التوافقية بين الورثة، تدقيق تقارير تقييم العقارات والأموال، وصياغة عقود المخارجة والقسمة الرضائية التوثيقية أو العدلية بما يضمن عدم الطعن فيها بالغبن." },
        { title: "دعاوى القسمة القضائية وتصفية الشياع", text: "رفع ومتابعة دعاوى القسمة العينية أو التصفية القضائية أمام المحكمة المختصة، مناقشة تقارير الخبرة العقارية، وتتبع البيع بالمزاد العلني متى تعذرت القسمة العينية." },
        { title: "منازعات التصرف في التركة والاستئثار بالغلّة", text: "مباشرة دعاوى محاسبة الشريك الحائز، المطالبة بنصيب الوارث في مداخيل الأكرية والاستغلال الفلاحي، والطعن في التصرفات الصادرة عن المورث خلال مرض الموت أو الهبات الصورية." },
        { title: "تركات المغاربة المقيمين بالخارج والأموال الدولية", text: "تمثيل الورثة المقيمين بالخارج بموجب وكالات رسمية وتنسيق نقل الملكيات العقارية وتصفية الحسابات البنكية وحماية مصالحهم أمام المحاكم والإدارات المغربية." },
        { title: "تصفية الضيعات الفلاحية المشاعة", text: "معالجة التركات المشتملة على أراضٍ فلاحية، دعاوى قسمة المهايأة (الانتفاع الدوري)، تنظيم إدارة الاستغلال الفلاحي ومواجهة استئثار أحد الورثة بالإنتاج والآلات." },
      ],
      processTitle: "مراحل تسوية ملفات التركات من الحصر إلى تسليم الأنصبة",
      processIntro: "نعتمد مساراً إجرائياً مهنياً يفرز الحقوق الثابتة عن الادعاءات غير المؤسسة، مع تفضيل الحلول التوافقية المستدامة قبل اللجوء للتقاضي.",
      process: [
        { title: "الحصر والتحقيق الشرعي والمستندي", text: "جمع رسوم الإراثة، الشواهد العقارية، عقود التفويتات القديمة، وتحديد نصيب كل وارث فرضاً أو تعصيباً." },
        { title: "تقييم خيارات القسمة والمخارجة", text: "الموازنة القانونية والمالية بين خيار القسمة الرضائية، التخارج بمقابل، أو اللجوء إلى دعوى القسمة والتصفية القضائية." },
        { title: "مباشرة المسطرة القضائية والتنفيذ", text: "رفع المقال الافتتاحي لدعوى القسمة، تتبع إجراءات الخبرة القضائية الطبوغرافية، وتوزيع الأنصبة أو عائدات المزاد بصندوق المحكمة." },
      ],
      faqTitle: "أسئلة شائعة حول الميراث وقسمة التركات بالمغرب",
      faqIntro: "تتضمن هذه التوضيحات مبادئ توجيهية عامة، وتظل دراسة وثائق التركة ورسوم الإراثة ضرورية لتحديد الوضعية الشرعية والقانونية لكل نازلة بدقة.",
      faqs: [
        { question: "كيف تتم قسمة التركة المتضمنة لأموال وعقارات بالمغرب؟", answer: "تتم تصفية التركة أولاً بأداء الديون وتجهيز الجنازة وتنفيذ الوصايا الصحيحة في حدود الثلث طبقاً للمادة 322 من مدونة الأسرة؛ ثم يتم حصر الباقي وقسمته بين الورثة بحسب أنصبتهم الشرعية إما رضائياً بعقد موثق أو قضائياً عبر المحكمة الابتدائية." },
        { question: "ما العمل القانوني في حال رفض أحد الورثة إجراء القسمة أو عرقلتها؟", answer: "تنص المادة 27 من مدونة الحقوق العينية على أنه 'لا يُجبر أحد على البقاء في الشياع'؛ وعليه يحق لأي وارث رفع دعوى القسمة القضائية أمام المحكمة التي تأمر بإجراء خبرة للقسمة العينية إن أمكنت، أو بالبيع بالمزاد العلني وتوزيع الثمن على الشركاء." },
        { question: "كيف يتعامل المشرع المغربي مع استئثار أحد الورثة بغلة التركة أو استغلالها منفرداً؟", answer: "يُعتبر الشريك الذي يستغل العقار المشترك منفرداً مسؤولاً عن أداء تعويض عن الاحتلال ومحاسبته عن كافة المداخيل والغلات التي جناها طيلة مدة الاستغلال لفائدة مجموع الورثة، ويحق للشركاء رفع دعوى المحاسبة واسترداد نصيبهم مشمولاً بالفوائد القانونية." },
        { question: "هل يستطيع الوارث المقيم بالخارج توكيل محامٍ لمباشرة كافة إجراءات التركة بالمغرب؟", answer: "نعم، يمكن للوارث المقيم بالخارج تحرير وكالة رسمية مفصلة لدى القنصلية المغربية أو موثق معتمد بالخارج وتذييلها بالأبوستيل (Apostille)، لمباشرة الحصر العقاري ورفع دعاوى القسمة واستلام مستحقاته دون الحاجة للتنقل الشخصي." },
        { question: "كيف يتم تقسيم ضيعة فلاحية مشاعة دون الإضرار بوحدتها الاقتصادية؟", answer: "إذا كانت مساحة الضيعة لا تتحمل التجزئة المادية بمقتضى القوانين الفلاحية، يمكن للمحكمة اللجوء إلى قسمة المهايأة الزمانية أو المكانية، أو الحكم بإسناد الضيعة للوارث الأقدر على استغلالها مع إلزامه بأداء مقابل مالي نقدي (مُعدَّل القسمة) لباقي الشركاء." },
        { question: "ما هي شروط وإجراءات الطعن في تصرفات المورث المنجزة في مرض الموت أو الهبات الصورية؟", answer: "إذا ثبت أن المورث أجرى بيعاً أو هبة لوارث أو للغير وهو في مرض مخوف اتصل به الموت (مرض الموت طبقاً للفصلين 344 و479 من ق.ل.ع والمادة 344 من مدونة الأسرة)، فإن التصرف يأخذ حكم الوصية ولا ينفذ في حق باقي الورثة فيما زاد عن الثلث إلا بإجازتهم، ويحق للورثة الطعن ببطلانه قضائياً." },
      ],
      related: [
        { key: "immobilier", label: "القانون العقاري والتحفيظ" },
        { key: "foncierRural", label: "العقار الفلاحي وقسمة الأراضي" },
      ],
      ctaTitle: "هل تواجهون صعوبة في قسمة تركة أو نزاعاً بين الورثة على الشياع؟",
      ctaText: "بادروا بحجز موعد لعرض وثائق التركة والإراثة على مكتب الأستاذ عبد الرزاق الرويسي لدراسة الحلول الرضائية والمساطر القضائية الضامنة لحقوقكم.",
    },
  },
};
