import type { ServicePageDefinition } from "@/lib/service-page-types";

export const successionPage: ServicePageDefinition = {
  key: "succession",
  index: "02",
  content: {
    fr: {
      slug: "succession-heritage",
      seo: {
        title: "Avocat succession et héritage au Maroc",
        description: "Avocat en succession au Maroc : héritage, partage, indivision et conflits entre héritiers à Mohammedia et Casablanca. Cabinet depuis 1992.",
      },
      eyebrow: "Succession · Héritage · Partage",
      h1: "Avocat en succession et héritage au Maroc",
      lead: "Le cabinet accompagne les héritiers dans l’identification des droits, la liquidation de la succession, le partage des biens et la résolution des conflits familiaux ou patrimoniaux.",
      summary: [
        "Une succession peut réunir des questions familiales, immobilières, bancaires et fiscales. L’inventaire des biens, l’établissement de la qualité d’héritier et l’analyse des actes permettent de distinguer ce qui peut être réglé amiablement de ce qui nécessite une procédure.",
        "Maître Abderrazak Errouissi intervient pour les successions situées à Mohammedia, Casablanca et ailleurs au Maroc, y compris lorsque des héritiers résident à l’étranger ou que la succession comprend un terrain, un logement, un commerce ou des parts sociales.",
        "Lorsqu’une ferme ou une terre agricole reste en indivision, le conflit porte souvent autant sur l’exploitation que sur les quotes-parts : occupation par un seul héritier, revenus non partagés, refus d’accès, limites incertaines ou désaccord sur la vente. Le cabinet relie alors les droits successoraux au statut foncier et à la réalité rurale du bien.",
      ],
      servicesTitle: "Clarifier les droits et organiser le partage",
      servicesIntro: "L’objectif est de préserver les droits de chacun tout en recherchant, lorsque les conditions le permettent, une issue qui évite l’enlisement du patrimoine.",
      services: [
        { title: "Identification des héritiers et des biens", text: "Étude des documents d’état civil, actes d’hérédité, titres de propriété, comptes, créances et dettes composant la succession." },
        { title: "Partage amiable de la succession", text: "Préparation de la négociation entre héritiers, examen des évaluations et formalisation d’un accord conforme aux droits de chacun." },
        { title: "Partage judiciaire et sortie d’indivision", text: "Action lorsque l’accord est impossible, avec traitement des biens indivis, demandes d’expertise et opérations de liquidation." },
        { title: "Conflits entre héritiers", text: "Contestation d’actes, occupation ou gestion exclusive d’un bien, dissimulation alléguée d’éléments de la succession et blocage des opérations." },
        { title: "Succession immobilière ou internationale", text: "Coordination des aspects successoraux et fonciers, notamment lorsque des biens sont au Maroc et que certains héritiers vivent à l’étranger." },
        { title: "Fermes et terres agricoles en indivision", text: "Conflits ruraux entre cohéritiers, exploitation exclusive, partage des récoltes ou revenus, accès à la parcelle, sortie d’indivision et partage d’une exploitation familiale." },
      ],
      processTitle: "Transformer une situation familiale en dossier structuré",
      processIntro: "Le cabinet distingue les faits établis, les points contestés et les documents manquants avant de recommander une négociation ou une procédure.",
      process: [
        { title: "Reconstituer la succession", text: "Identifier les héritiers, les actifs, les dettes, les actes et les éventuelles opérations antérieures." },
        { title: "Évaluer les options", text: "Comparer partage amiable, maintien temporaire de l’indivision, cession de droits ou partage judiciaire." },
        { title: "Formaliser ou agir", text: "Sécuriser l’accord obtenu ou saisir la juridiction compétente lorsque le blocage persiste." },
      ],
      faqTitle: "Questions fréquentes sur l’héritage au Maroc",
      faqIntro: "Les droits dépendent de la situation familiale, de la nature des biens et des documents disponibles. Ces réponses ne remplacent pas une analyse individualisée.",
      faqs: [
        { question: "Comment faire le partage d’un héritage au Maroc ?", answer: "Il faut d’abord déterminer les héritiers et inventorier les biens et dettes. Un partage amiable peut être préparé si tous les intéressés s’accordent. En cas de désaccord, le partage peut être demandé en justice selon la nature des biens." },
        { question: "Que faire si un héritier refuse le partage ?", answer: "Il convient de vérifier les droits de chacun, les titres et les possibilités de règlement amiable. Si le blocage demeure, une action en partage ou d’autres mesures adaptées à la situation peuvent être envisagées." },
        { question: "Combien coûte une procédure de succession ?", answer: "Le coût dépend du nombre de biens et d’héritiers, de la nécessité d’une expertise, des formalités foncières et de l’existence d’un contentieux. Une estimation ne peut être donnée qu’après examen du dossier." },
        { question: "Un héritier vivant à l’étranger peut-il agir au Maroc ?", answer: "Oui, selon le dossier, il peut accomplir certaines démarches par l’intermédiaire d’un mandataire et être représenté dans une procédure. Les pouvoirs et documents étrangers doivent être préparés avec soin." },
        { question: "Comment partager un bien immobilier hérité ?", answer: "Le partage peut être matériel si le bien est divisible, résulter d’une attribution ou d’une vente, ou être ordonné judiciairement. Le titre foncier, la valeur du bien et les droits de chaque héritier sont déterminants." },
        { question: "Comment sortir de l’indivision d’une terre agricole héritée ?", answer: "Il faut vérifier le statut foncier, les droits de chaque héritier, la configuration de la parcelle et sa divisibilité. Un partage amiable, une attribution, une cession ou une procédure de partage peuvent être étudiés selon la situation." },
        { question: "Que faire si un héritier exploite seul la ferme familiale ?", answer: "Il convient de documenter l’occupation, les revenus, les dépenses, les accords antérieurs et les droits de chacun. Une discussion encadrée, des comptes entre cohéritiers ou une action liée au partage et à l’usage du bien peuvent être envisagés après analyse." },
        { question: "Peut-on partager une ferme sans interrompre son exploitation ?", answer: "Cela dépend de la configuration, du statut de la terre et de l’accord des héritiers. Une attribution avec compensation, une organisation conventionnelle ou une autre solution peut parfois préserver l’unité économique mieux qu’une division matérielle." },
      ],
      related: [
        { key: "immobilier", label: "Droit immobilier" },
        { key: "foncierRural", label: "Terres agricoles" },
      ],
      ctaTitle: "Une succession est bloquée ou contestée ?",
      ctaText: "Apportez les actes d’hérédité, titres et échanges disponibles pour obtenir une première lecture structurée de la situation.",
    },
    ar: {
      slug: "الميراث-والتركات",
      seo: {
        title: "محامٍ في قضايا الميراث والتركات بالمغرب",
        description: "محامٍ في قضايا الميراث والتركات بالمغرب لقسمة التركة والشياع والنزاعات بين الورثة بالمحمدية والدار البيضاء. مواكبة قانونية بخبرة منذ 1992.",
      },
      eyebrow: "الميراث · التركات · القسمة",
      h1: "محامٍ في قضايا الميراث وقسمة التركات بالمغرب",
      lead: "يرافق المكتب الورثة في تحديد الحقوق وحصر التركة وتصفيتها وقسمة الأموال والعقارات وتسوية النزاعات العائلية والمالية المرتبطة بالإرث.",
      summary: [
        "قد تجمع التركة بين مسائل أسرية وعقارية وبنكية ومالية. ويساعد حصر الأموال والديون وإثبات صفة الورثة وفحص العقود على تحديد ما يمكن تسويته بالاتفاق وما يتطلب اللجوء إلى القضاء.",
        "يتدخل الأستاذ عبد الرزاق الرويسي في ملفات الميراث بالمحمدية والدار البيضاء ومختلف مناطق المغرب، بما في ذلك الملفات التي يقيم بعض ورثتها بالخارج أو تضم عقارات أو أراضي أو محلات تجارية أو حصصاً في شركات.",
        "عندما تبقى ضيعة أو أرض فلاحية على الشياع، يرتبط النزاع غالباً بالاستغلال إلى جانب الأنصبة: استئثار وارث بالأرض أو المداخيل، منع الولوج، غموض الحدود أو الخلاف حول البيع. لذلك يربط المكتب حقوق الإرث بالوضع العقاري والواقع القروي للأرض.",
      ],
      servicesTitle: "تحديد الحقوق وتنظيم قسمة التركة",
      servicesIntro: "يهدف المكتب إلى حماية حقوق موكليه والبحث، متى توفرت الشروط، عن تسوية رضائية تحول دون استمرار تعطيل أموال التركة.",
      services: [
        { title: "تحديد الورثة وأموال التركة", text: "دراسة وثائق الحالة المدنية ورسم الإراثة والرسوم العقارية والحسابات والديون والحقوق الداخلة في التركة." },
        { title: "القسمة الرضائية", text: "مواكبة التفاوض بين الورثة وفحص التقييمات وصياغة اتفاق واضح يحترم حقوق الأطراف." },
        { title: "القسمة القضائية والخروج من الشياع", text: "مباشرة الدعوى عند تعذر الاتفاق ومعالجة العقارات المشاعة والخبرة وإجراءات التصفية." },
        { title: "النزاعات بين الورثة", text: "الطعن في التصرفات والاستئثار بالانتفاع أو التسيير والادعاء بإخفاء أموال من التركة وتعطيل القسمة." },
        { title: "التركات العقارية والدولية", text: "تنسيق مسائل الإرث والملكية عندما توجد الأموال في المغرب أو يقيم بعض الورثة في الخارج." },
        { title: "الضيعات والأراضي الفلاحية المشاعة", text: "النزاعات القروية بين الورثة والاستغلال المنفرد وتقاسم الغلة أو المداخيل والولوج والخروج من الشياع وقسمة الضيعة العائلية." },
      ],
      processTitle: "مواكبة منظمة من دراسة التركة إلى تسويتها",
      processIntro: "يفصل المكتب بين الوقائع الثابتة والنقاط المتنازع عليها والوثائق الناقصة قبل اقتراح الصلح أو المسطرة القضائية.",
      process: [
        { title: "حصر عناصر التركة", text: "تحديد الورثة والأموال والديون والعقود والتصرفات السابقة ذات الصلة." },
        { title: "تقييم طرق الحل", text: "مقارنة القسمة الرضائية والاستمرار المؤقت في الشياع وتفويت الحقوق والقسمة القضائية." },
        { title: "توثيق الاتفاق أو رفع الدعوى", text: "صياغة الاتفاق المتوصل إليه وتحديد إجراءات تنفيذه، أو اللجوء إلى المحكمة المختصة عند استمرار التعطيل." },
      ],
      faqTitle: "أسئلة شائعة حول الميراث في المغرب",
      faqIntro: "تختلف الحقوق حسب الوضع العائلي وطبيعة الأموال والوثائق. لذلك تبقى دراسة كل ملف ضرورية.",
      faqs: [
        { question: "كيف تتم قسمة التركة في المغرب؟", answer: "يجب أولاً تحديد الورثة وحصر الأموال والديون. ويمكن إنجاز قسمة رضائية إذا اتفق الجميع، وإلا أمكن طلب القسمة القضائية بحسب طبيعة الأموال والعقارات." },
        { question: "ماذا أفعل إذا رفض أحد الورثة القسمة؟", answer: "يُفحص أصل الحقوق والرسوم وإمكانية الوصول إلى اتفاق. وإذا استمر التعطيل يمكن دراسة دعوى القسمة أو الإجراءات الملائمة لحماية المال المشترك." },
        { question: "كم تكلف دعوى قسمة التركة؟", answer: "تتغير التكلفة بحسب عدد الورثة والأموال والحاجة إلى الخبرة والإجراءات العقارية ووجود منازعة. لا يمكن تقدير الأتعاب والمصاريف المتوقعة إلا بعد فحص الملف." },
        { question: "هل يستطيع الوارث المقيم بالخارج متابعة الملف؟", answer: "يمكنه، حسب الحالة، إنجاز بعض الإجراءات بواسطة وكيل وتمثيله أمام القضاء. ويجب إعداد الوكالة والوثائق الصادرة بالخارج بصورة صحيحة." },
        { question: "كيف تتم قسمة عقار موروث؟", answer: "قد تكون القسمة عينية إذا كان العقار قابلاً للتقسيم، أو تتم عن طريق الإسناد أو البيع، أو بأمر قضائي. ويتوقف الحل على الرسم العقاري وقيمة العقار وأنصبة الورثة." },
        { question: "كيف يتم الخروج من الشياع في أرض فلاحية موروثة؟", answer: "يجب التحقق من النظام العقاري وأنصبة الورثة وشكل القطعة وقابليتها للقسمة. ويمكن دراسة القسمة الرضائية أو الإسناد أو التفويت أو القسمة القضائية بحسب الوضع." },
        { question: "ماذا أفعل إذا استغل وارث واحد الضيعة العائلية؟", answer: "ينبغي توثيق الاستغلال والمداخيل والمصاريف والاتفاقات السابقة وحقوق كل وارث. وبعد الفحص يمكن بحث تفاوض منظم أو محاسبة بين الورثة أو إجراء مرتبط بالقسمة واستعمال المال المشترك." },
        { question: "هل يمكن تقسيم الضيعة دون توقيف استغلالها؟", answer: "يتوقف ذلك على شكل الضيعة ووضع الأرض واتفاق الورثة. وقد يكون الإسناد مع التعويض أو تنظيم الاستغلال باتفاق أو حل آخر أنسب من التقسيم المادي للحفاظ على الوحدة الاقتصادية." },
      ],
      related: [
        { key: "immobilier", label: "القانون العقاري" },
        { key: "foncierRural", label: "الأراضي الفلاحية" },
      ],
      ctaTitle: "هل تواجهون صعوبة في قسمة التركة أو نزاعاً بين الورثة؟",
      ctaText: "أحضروا رسم الإراثة ووثائق الملكية والمراسلات المتوفرة للحصول على تقييم أولي للملف وتحديد الإجراءات المناسبة.",
    },
  },
};
