import type { GuideDefinition } from "@/lib/guide-types";

const landRegistrationLaw = "https://adala.justice.gov.ma/api/uploads/2024/06/25/%D8%A7%D9%84%D8%AA%D8%AD%D9%81%D9%8A%D8%B8%20%D8%A7%D9%84%D8%B9%D9%82%D8%A7%D8%B1%D9%8A-1719327275958.pdf";
const realRightsCode = "https://adala.justice.gov.ma/api/uploads/2024/09/02/%D9%85%D8%AF%D9%88%D9%86%D8%A9%20%D8%A7%D9%84%D8%AD%D9%82%D9%88%D9%82%20%D8%A7%D9%84%D8%B9%D9%8A%D9%86%D9%8A%D8%A9%20%D8%BA%D8%B4%D8%AA%202024-1725270480202.pdf";
const obligationsCode = "https://adala.justice.gov.ma/api/uploads/2024/09/04/%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D8%A7%D9%84%D8%AA%D8%B2%D8%A7%D9%85%D8%A7%D8%AA%20%D9%88%D8%A7%D9%84%D8%B9%D9%82%D9%88%D8%AF%20%D8%BA%D8%B4%D8%AA%202024%201-1725443715659.pdf";
const penalCode = "https://adala.justice.gov.ma/api/uploads/2024/09/18/%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A9%20%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%A7%D9%84%D8%AC%D9%86%D8%A7%D8%A6%D9%8A%20%D8%B5%D9%8A%D8%BA%D8%A9%20%D8%BA%D8%B4%D8%AA%202024-1726666547280.pdf";
const ancfcc = "https://www.ancfcc.gov.ma/";

export const caveatGuide: GuideDefinition = {
  key: "caveat", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "immobilier",
  relatedGuides: ["immatriculation", "opposition", "sale-others-property"],
  content: {
    fr: {
      slug: "prenotation-titre-foncier-maroc",
      seo: { title: "Prénotation sur titre foncier au Maroc : guide", description: "Prénotation au Maroc : fondement, durée, radiation et pièces à vérifier pour préserver provisoirement un droit sur un titre foncier." },
      category: "Publicité foncière",
      h1: "Prénotation sur un titre foncier au Maroc : protéger provisoirement un droit",
      lead: "La prénotation, appelée التقييد الاحتياطي en arabe, signale provisoirement une prétention sur un immeuble immatriculé. Son effet, sa durée et sa radiation dépendent de son fondement.",
      intro: ["Lorsqu’un droit ne peut pas encore être inscrit définitivement sur un titre foncier, attendre sans analyser la publicité foncière peut exposer le demandeur à des inscriptions ultérieures. La prénotation sert à préserver provisoirement le rang du droit invoqué, dans les limites prévues par la législation foncière.", "Ce mécanisme n’établit pas à lui seul la propriété et ne remplace ni l’action au fond ni la pièce manquante. Il faut rapprocher le certificat de propriété, l’acte, la procédure engagée et toutes les dates utiles avant de choisir le fondement de la demande."],
      takeaways: ["La prénotation concerne un droit prétendu sur un immeuble immatriculé.", "Sa durée n’est pas identique selon qu’elle repose sur un titre, une requête judiciaire ou une ordonnance.", "L’inscription définitive et la radiation exigent un suivi actif du dossier."],
      sections: [
        { id: "role", title: "À quoi sert la prénotation foncière ?", paragraphs: ["La prénotation rend provisoirement visible sur le titre foncier un droit dont l’inscription définitive est différée. Si ce droit est ensuite reconnu et régulièrement inscrit, son rang peut être apprécié en tenant compte de la prénotation, selon les conditions légales applicables.", "Elle doit être distinguée d’une saisie, d’une hypothèque et d’une opposition à une réquisition d’immatriculation. Ces mécanismes n’ont ni le même objet ni la même procédure."], bullets: ["Identifier le droit dont l’inscription est recherchée.", "Vérifier le numéro exact du titre et les inscriptions existantes.", "Déterminer si une instance au fond doit être introduite ou poursuivie."] },
        { id: "grounds", title: "Titre, requête ou ordonnance : choisir le bon fondement", paragraphs: ["Le dahir sur l’immatriculation foncière prévoit plusieurs fondements de prénotation. Le document disponible, la nature du défaut empêchant l’inscription et l’existence d’un litige déterminent la voie utile.", "Chaque fondement obéit à son propre régime. Il serait donc risqué de retenir un délai trouvé en ligne sans vérifier le support de la prénotation, la date de son inscription et les actes accomplis ensuite."], note: "Une prénotation expirée ou mal suivie peut ne plus préserver le rang recherché. Les dates doivent être contrôlées sur les pièces du dossier." },
        { id: "follow-up", title: "Suivre l’inscription, la procédure et la radiation", paragraphs: ["Le suivi porte sur le certificat de propriété, le récépissé, la procédure judiciaire éventuelle et les décisions rendues. Si le droit est reconnu, les formalités nécessaires à l’inscription définitive doivent être accomplies.", "La radiation peut résulter de l’arrivée du terme, d’un consentement ou d’une décision, selon la situation. Avant de demander ou de contester une radiation, il faut vérifier le fondement exact de l’inscription et l’état de l’instance."], bullets: ["Obtenir un certificat de propriété récent.", "Classer requêtes, ordonnances, décisions et preuves de notification.", "Noter séparément les dates d’inscription et les échéances procédurales."] },
      ],
      checklistTitle: "Pièces à réunir pour examiner une prénotation", checklistIntro: "La liste dépend du fondement retenu et de l’état du litige.",
      checklist: ["Certificat de propriété récent et références complètes du titre.", "Acte ou document dont l’inscription définitive est demandée.", "Copie de la requête, ordonnance ou décision invoquée.", "Récépissés de la conservation foncière et notifications reçues.", "Chronologie des ventes, inscriptions et procédures connues."],
      faqTitle: "Questions fréquentes sur la prénotation",
      faqs: [
        { question: "Combien de temps dure une prénotation au Maroc ?", answer: "La durée dépend de son fondement juridique. Une prénotation fondée sur un titre, une requête judiciaire ou une ordonnance ne suit pas nécessairement le même régime. Il faut vérifier l’inscription et les pièces avant de calculer une échéance." },
        { question: "La prénotation empêche-t-elle toute vente du bien ?", answer: "Elle rend la prétention visible et peut affecter le rang des droits ultérieurs, mais son effet exact doit être apprécié avec son fondement et les inscriptions du titre. Elle ne doit pas être présentée comme une interdiction automatique de toute opération." },
        { question: "Comment faire radier une prénotation ?", answer: "La voie dépend du motif de la prénotation, de sa durée et de l’état de la procédure. La radiation peut exiger une pièce justificative, un consentement ou une décision. Le titre et le dossier judiciaire doivent être examinés ensemble." },
        { question: "Une prénotation prouve-t-elle que son bénéficiaire est propriétaire ?", answer: "Non. Elle préserve provisoirement une prétention dans les conditions légales ; elle ne remplace pas la décision ou le document permettant l’inscription définitive du droit." },
      ],
      ctaTitle: "Une prénotation apparaît sur votre titre foncier ?", ctaText: "Le cabinet examine son fondement, ses dates, les actes et la procédure afin d’identifier les démarches adaptées.", serviceLabel: "Droit immobilier",
      sourcesLabel: "Textes et organismes officiels", sources: [{ label: "Ministère de la Justice — dahir sur l’immatriculation foncière (chapitre des prénotations)", url: landRegistrationLaw }, { label: "ANCFCC — services de la conservation foncière", url: ancfcc }],
    },
    ar: {
      slug: "التقييد-الاحتياطي-على-الرسم-العقاري",
      seo: { title: "التقييد الاحتياطي في القانون المغربي", description: "دليل التقييد الاحتياطي على الرسم العقاري بالمغرب: السند والمدة والتشطيب والوثائق اللازمة للحفاظ المؤقت على الحق." },
      category: "الإشهار العقاري",
      h1: "التقييد الاحتياطي على الرسم العقاري في المغرب",
      lead: "يهدف التقييد الاحتياطي إلى الإشهار المؤقت بحق يدعيه صاحبه على عقار محفظ، وتختلف مدته وآثاره وكيفية التشطيب عليه بحسب السند المعتمد.",
      intro: ["قد يتعذر تقييد حق نهائياً في الرسم العقاري بسبب نقص وثيقة أو وجود نزاع معروض على القضاء. وفي هذه الحالة قد يسمح التقييد الاحتياطي بالحفاظ المؤقت على رتبة الحق المدعى به ضمن الحدود التي يقررها قانون التحفيظ العقاري.", "لا يثبت هذا التقييد الملكية بمفرده، ولا يعوض الدعوى في الموضوع أو الوثيقة اللازمة للتقييد النهائي. لذلك ينبغي فحص شهادة الملكية والعقد والمسطرة الجارية وجميع التواريخ قبل اختيار الإجراء."],
      takeaways: ["يرتبط التقييد الاحتياطي بحق مدعى به على عقار محفظ.", "تختلف مدته بحسب استناده إلى سند أو مقال دعوى أو أمر قضائي.", "يقتضي الحفاظ على أثره تتبع المسطرة داخل الآجال المناسبة."],
      sections: [
        { id: "role", title: "ما الغرض من التقييد الاحتياطي؟", paragraphs: ["يشهر التقييد الاحتياطي بصورة مؤقتة حقاً تعذر تقييده نهائياً. وإذا ثبت الحق لاحقاً وتم تقييده وفق القانون، فإن ترتيب آثاره يدرس على ضوء التقييد الاحتياطي وشروطه.", "ويختلف عن الحجز والرهن والتعرض على مطلب التحفيظ، لأن لكل واحد من هذه الإجراءات غاية ومسطرة وآثاراً خاصة."], bullets: ["تحديد الحق المطلوب تقييده نهائياً.", "التحقق من رقم الرسم العقاري والتقييدات الواردة عليه.", "تحديد ما إذا كان يلزم رفع الدعوى في الموضوع أو مواصلتها."] },
        { id: "grounds", title: "التقييد بناء على سند أو مقال أو أمر قضائي", paragraphs: ["يتيح قانون التحفيظ العقاري أسساً مختلفة للتقييد الاحتياطي. ويتوقف الاختيار على الوثيقة المتوفرة وسبب تعذر التقييد النهائي ووجود منازعة من عدمه.", "ولا تخضع هذه الأسس بالضرورة للمدة نفسها. لذلك لا ينبغي اعتماد أجل متداول دون التحقق من سند التقييد وتاريخه والإجراءات التي اتخذت بعده."], note: "قد يؤدي انقضاء الأجل أو عدم تتبع المسطرة إلى زوال الحماية المؤقتة المطلوبة؛ لذا يجب احتساب التواريخ انطلاقاً من وثائق الملف." },
        { id: "follow-up", title: "تتبع التقييد والدعوى والتشطيب", paragraphs: ["يشمل التتبع شهادة الملكية والوصل والمقال القضائي والأوامر والأحكام الصادرة. وعند ثبوت الحق، ينبغي إنجاز الإجراءات اللازمة لتقييده بصورة نهائية.", "يختلف التشطيب بحسب سبب التقييد ومدته ومآل النزاع. وقبل طلب التشطيب أو الاعتراض عليه، يجب معرفة السند الدقيق للتقييد والمرحلة التي بلغتها الدعوى."], bullets: ["طلب شهادة ملكية حديثة.", "ترتيب المقالات والأوامر والأحكام وإثباتات التبليغ.", "تدوين تاريخ التقييد والآجال القضائية بصورة مستقلة."] },
      ],
      checklistTitle: "وثائق دراسة التقييد الاحتياطي", checklistIntro: "تتغير الوثائق المطلوبة بحسب سند التقييد ومرحلة النزاع.",
      checklist: ["شهادة ملكية حديثة ومراجع الرسم العقاري.", "العقد أو الوثيقة المراد تقييد الحق استناداً إليها.", "نسخة المقال أو الأمر أو الحكم المعتمد.", "وصولات المحافظة العقارية والتبليغات المتوفرة.", "تسلسل زمني للتفويتات والتقييدات والمساطر المعروفة."],
      faqTitle: "أسئلة حول التقييد الاحتياطي",
      faqs: [
        { question: "ما مدة التقييد الاحتياطي في المغرب؟", answer: "تختلف المدة بحسب السند القانوني للتقييد. فالتقييد المبني على سند أو مقال دعوى أو أمر قضائي لا يخضع بالضرورة للنظام نفسه، ويجب الرجوع إلى التقييد والوثائق قبل احتساب الأجل." },
        { question: "هل يمنع التقييد الاحتياطي بيع العقار؟", answer: "يشهر الحق المدعى به وقد يؤثر في ترتيب الحقوق اللاحقة، لكن أثره الدقيق يحدد بحسب سنده وباقي التقييدات. لذلك لا يصح اعتباره في جميع الحالات منعاً آلياً لكل تفويت." },
        { question: "كيف يتم التشطيب على التقييد الاحتياطي؟", answer: "يتوقف الإجراء على سبب التقييد ومدته ومآل الدعوى. وقد يستلزم وثيقة مثبتة أو موافقة أو قراراً قضائياً، مما يقتضي فحص الرسم العقاري والملف القضائي معاً." },
        { question: "هل يثبت التقييد الاحتياطي الملكية؟", answer: "لا. إنه يحافظ مؤقتاً على حق مدعى به وفق شروط القانون، ولا يعوض الحكم أو الوثيقة التي تسمح بالتقييد النهائي." },
      ],
      ctaTitle: "هل يوجد تقييد احتياطي على رسمكم العقاري؟", ctaText: "يفحص المكتب سند التقييد وتواريخه والوثائق والمساطر لتحديد الإجراء المناسب.", serviceLabel: "القانون العقاري",
      sourcesLabel: "النصوص والجهات الرسمية", sources: [{ label: "وزارة العدل — ظهير التحفيظ العقاري، باب التقييدات الاحتياطية", url: landRegistrationLaw }, { label: "الوكالة الوطنية للمحافظة العقارية", url: ancfcc }],
    },
  },
};

export const shufaaGuide: GuideDefinition = {
  key: "shufaa", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "immobilier", relatedGuides: ["indivision", "sale-others-property", "ownership-claim"],
  content: {
    fr: {
      slug: "droit-chafaa-preemption-maroc", seo: { title: "Chafaa au Maroc : conditions, délais et procédure", description: "Comprendre la chafaa au Maroc : qualité de copropriétaire, vente d’une quote-part, délais, offre du prix et procédure." }, category: "Copropriété et indivision",
      h1: "Chafaa au Maroc : conditions, délais et procédure", lead: "La chafaa permet, sous conditions, à un copropriétaire indivis de se substituer à l’acquéreur d’une quote-part vendue. Une réaction rapide et documentée est essentielle.",
      intro: ["Le droit de chafaa ne s’applique pas à toute vente immobilière. Il suppose notamment d’identifier le bien, la quote-part cédée, la qualité du demandeur et la nature de l’opération.", "Les délais et formalités varient selon la publicité de la vente et le statut foncier du bien. Avant toute démarche, il faut donc obtenir les actes, vérifier les inscriptions et dater avec précision la notification ou la connaissance de la vente."],
      takeaways: ["La qualité de copropriétaire indivis doit être établie.", "L’acte, le prix et les frais doivent être examinés avant d’agir.", "Les délais sont déterminants et se calculent à partir des faits du dossier."],
      sections: [
        { id: "conditions", title: "Vérifier si le droit de chafaa est ouvert", paragraphs: ["La chafaa vise la cession à titre onéreux d’une quote-part indivise dans les conditions prévues par le Code des droits réels. Il faut contrôler la qualité des parties, l’origine de l’indivision et l’objet exact de la vente.", "Une vente portant sur un lot déjà individualisé, une opération d’une autre nature ou une renonciation valable peuvent modifier l’analyse. Le contenu de l’acte prévaut sur l’intitulé donné par les parties."], bullets: ["Produire le titre ou les actes établissant la quote-part du demandeur.", "Obtenir l’acte de vente et identifier l’acquéreur.", "Vérifier si le bien est immatriculé, en cours d’immatriculation ou non immatriculé."] },
        { id: "deadlines", title: "Calculer le délai à partir de documents fiables", paragraphs: ["Le Code des droits réels organise des délais liés notamment à la notification, à l’inscription ou au dépôt de l’acte et à la connaissance de la vente. Le point de départ ne doit pas être supposé.", "Une date de conversation familiale ou une rumeur sur la vente ne suffit pas toujours à reconstituer la chronologie. Il faut conserver les notifications, certificats, copies d’actes et tout élément établissant la date pertinente."], note: "En matière de chafaa, attendre peut entraîner la perte du droit. Une vérification immédiate est préférable dès la découverte de la vente." },
        { id: "procedure", title: "Préparer l’offre, les frais et la procédure", paragraphs: ["L’exercice de la chafaa implique de tenir compte du prix et des frais prévus par la loi. Une contestation sur le prix apparent, la consistance vendue ou les améliorations alléguées demande une analyse des preuves.", "La démarche doit viser la bonne personne et le bon bien. Pour un immeuble immatriculé, les informations du titre et l’inscription de la vente sont centrales ; pour un bien non immatriculé, les actes et la possession prennent une place particulière."], bullets: ["Établir une chronologie de la vente et de sa découverte.", "Réunir les éléments relatifs au prix et aux frais.", "Ne pas signer une renonciation ou un accord sans en mesurer les effets."] },
      ],
      checklistTitle: "Documents utiles pour une chafaa", checklistIntro: "Ils permettent de vérifier la qualité, l’opération et les délais.", checklist: ["Titre foncier ou actes de propriété et quote-parts.", "Acte de vente ou références permettant de l’obtenir.", "Certificat de propriété récent si le bien est immatriculé.", "Notifications, correspondances et preuves de dates.", "Éléments relatifs au prix, aux frais et aux éventuels travaux."],
      faqTitle: "Questions fréquentes sur la chafaa", faqs: [
        { question: "Qui peut exercer la chafaa au Maroc ?", answer: "La qualité requise dépend de l’indivision et des conditions du Code des droits réels. Elle doit être démontrée par les actes et, pour un immeuble immatriculé, rapprochée des inscriptions foncières." },
        { question: "Quel est le délai pour demander la chafaa ?", answer: "Le calcul dépend notamment de la notification, du statut foncier et de la publicité de la vente. Comme plusieurs points de départ peuvent être discutés, les dates et pièces doivent être vérifiées sans attendre." },
        { question: "Faut-il rembourser le prix à l’acquéreur ?", answer: "L’exercice de la chafaa suppose de prendre en compte le prix et les dépenses légalement pertinentes. Leur montant et leur preuve doivent être contrôlés à partir de l’acte et des justificatifs." },
        { question: "La chafaa est-elle possible entre héritiers ?", answer: "Elle peut être envisagée lorsqu’un héritier, devenu copropriétaire indivis, remplit les conditions et qu’une quote-part a été cédée dans une opération ouvrant ce droit. Chaque acte doit être qualifié précisément." },
      ],
      ctaTitle: "Une quote-part indivise vient d’être vendue ?", ctaText: "Le cabinet vérifie la qualité des parties, l’acte, les inscriptions et les délais avant d’orienter la démarche.", serviceLabel: "Droit immobilier", sourcesLabel: "Texte officiel", sources: [{ label: "Ministère de la Justice — Code des droits réels, articles relatifs à la chafaa", url: realRightsCode }],
    },
    ar: {
      slug: "الشفعة-في-القانون-المغربي", seo: { title: "الشفعة في القانون المغربي: الشروط والآجال", description: "دليل الشفعة في القانون المغربي: صفة الشريك وبيع الحصة والأجل والثمن والمصاريف والإجراءات المتعلقة بالعقار." }, category: "الشياع والملكية المشتركة",
      h1: "الشفعة في القانون المغربي: الشروط والآجال والإجراءات", lead: "تتيح الشفعة، عند توفر شروطها، للشريك على الشياع أن يحل محل مشتري الحصة المبيعة. ويظل التحرك السريع وفحص الوثائق أمراً أساسياً.",
      intro: ["لا تطبق الشفعة على كل بيع عقاري، بل يجب تحديد العقار والحصة المبيعة وصفة طالب الشفعة وطبيعة التصرف.", "تتأثر الآجال والإجراءات بطريقة إشهار البيع والوضع القانوني للعقار. لذلك ينبغي الحصول على العقود والتقييدات وضبط تاريخ التبليغ أو العلم بالبيع قبل اتخاذ أي خطوة."],
      takeaways: ["يجب إثبات صفة الشريك على الشياع.", "ينبغي فحص العقد والثمن والمصاريف قبل مباشرة الإجراء.", "الآجال حاسمة وتحسب انطلاقاً من وقائع ووثائق الملف."],
      sections: [
        { id: "conditions", title: "التحقق من توفر شروط الشفعة", paragraphs: ["ترتبط الشفعة بتفويت حصة شائعة بعوض وفق الشروط الواردة في مدونة الحقوق العينية. ويتعين التحقق من صفة الأطراف وأصل الشياع ومحل البيع بدقة.", "قد يختلف الحكم إذا تعلق الأمر بجزء مفرز أو بتصرف من طبيعة أخرى أو بتنازل صحيح عن الحق. والعبرة بمضمون العقد لا بالاسم الذي منحه له الأطراف."], bullets: ["إثبات حصة طالب الشفعة بالرسوم والتقييدات.", "الحصول على عقد البيع وتحديد المشتري.", "معرفة ما إذا كان العقار محفظاً أو في طور التحفيظ أو غير محفظ."] },
        { id: "deadlines", title: "احتساب الأجل بناء على وثائق ثابتة", paragraphs: ["تربط مدونة الحقوق العينية الآجال بعناصر من بينها التبليغ والتقييد أو الإيداع والعلم بالبيع. لذلك لا يجوز افتراض نقطة بداية واحدة لجميع الملفات.", "لا تكفي الأخبار العائلية وحدها دائماً لإثبات التسلسل الزمني. وينبغي حفظ التبليغات والشهادات ونسخ العقود وكل ما يثبت التاريخ المعتمد."], note: "قد يؤدي التأخر إلى سقوط الحق في الشفعة؛ لذا يستحسن فحص الملف فور العلم بالبيع." },
        { id: "procedure", title: "إعداد الثمن والمصاريف والمسطرة", paragraphs: ["تقتضي ممارسة الشفعة مراعاة الثمن والمصاريف التي يعتد بها القانون. وإذا وقع خلاف بشأن الثمن المصرح به أو الحصة المبيعة أو التحسينات، وجب تقييم الحجج المثبتة لذلك.", "ينبغي توجيه الإجراء إلى الشخص والعقار المعنيين. وتكتسي بيانات الرسم العقاري وتقييد البيع أهمية خاصة في العقار المحفظ، بينما تبرز الرسوم والحيازة في العقار غير المحفظ."], bullets: ["إعداد تسلسل زمني للبيع والعلم به.", "جمع ما يثبت الثمن والمصاريف.", "عدم توقيع أي تنازل أو اتفاق قبل معرفة آثاره."] },
      ],
      checklistTitle: "وثائق دراسة طلب الشفعة", checklistIntro: "تساعد الوثائق على فحص الصفة والبيع والآجال.", checklist: ["الرسم العقاري أو رسوم الملكية وبيان الحصص.", "عقد البيع أو مراجعه للحصول على نسخة منه.", "شهادة ملكية حديثة إذا كان العقار محفظاً.", "التبليغات والمراسلات وما يثبت التواريخ.", "وثائق الثمن والمصاريف والأشغال المدعى بها."],
      faqTitle: "أسئلة حول الشفعة", faqs: [
        { question: "من يحق له طلب الشفعة في المغرب؟", answer: "تحدد الصفة المطلوبة بحسب الشياع وشروط مدونة الحقوق العينية. ويجب إثباتها بالرسوم، وبالتقييدات العقارية أيضاً إذا كان العقار محفظاً." },
        { question: "ما أجل ممارسة الشفعة؟", answer: "يتوقف الاحتساب على التبليغ والوضع القانوني للعقار وكيفية إشهار البيع. ونظراً لاحتمال اختلاف نقطة البداية، يجب فحص الوثائق والتواريخ فوراً." },
        { question: "هل يجب أداء الثمن للمشتري؟", answer: "تستلزم الشفعة مراعاة الثمن والمصاريف التي يعتد بها القانون. ويجب التحقق من المبالغ ووثائق إثباتها انطلاقاً من العقد والمستندات." },
        { question: "هل تجوز الشفعة بين الورثة؟", answer: "يمكن بحثها إذا أصبح الوارث شريكاً على الشياع وتوفرت باقي الشروط ووقع تفويت حصة بتصرف يفتح هذا الحق. ويلزم تكييف كل عقد على حدة." },
      ],
      ctaTitle: "هل بيعت حصة شائعة في العقار؟", ctaText: "يفحص المكتب صفة الأطراف والعقد والتقييدات والآجال قبل تحديد الإجراء المناسب.", serviceLabel: "القانون العقاري", sourcesLabel: "النص الرسمي", sources: [{ label: "وزارة العدل — مدونة الحقوق العينية، الأحكام المتعلقة بالشفعة", url: realRightsCode }],
    },
  },
};

export const dispossessionGuide: GuideDefinition = {
  key: "dispossession", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "foncierRural", relatedGuides: ["encroachment", "ownership-claim", "melkiya"],
  content: {
    fr: {
      slug: "depossession-occupation-terrain-maroc", seo: { title: "Dépossession d’un terrain au Maroc : que faire ?", description: "Occupation ou dépossession d’un terrain au Maroc : preuves de possession, constat, article 570, action civile et démarches à examiner." }, category: "Occupation et possession",
      h1: "Dépossession et occupation d’un terrain au Maroc : preuves et recours", lead: "Lorsqu’une personne est évincée d’un terrain, il faut distinguer immédiatement la possession, la propriété, les circonstances de l’entrée et l’urgence de préserver les preuves.",
      intro: ["Une clôture déplacée, une culture arrachée, une construction ou l’installation d’un tiers peut révéler des situations juridiques différentes. Employer seulement le mot « occupation » ne permet pas de choisir entre constat, plainte, action possessoire ou action fondée sur la propriété.", "L’article 570 du Code pénal vise l’enlèvement d’un immeuble de la possession d’autrui dans les conditions qu’il fixe. Sa qualification ne découle pas automatiquement d’un conflit de limites ou d’un désaccord familial : les faits et les éléments constitutifs doivent être établis."],
      takeaways: ["La possession et la propriété sont deux questions distinctes.", "Les lieux, les dates et les circonstances de l’éviction doivent être documentés rapidement.", "La voie pénale éventuelle ne remplace pas nécessairement le traitement civil ou foncier du conflit."],
      sections: [
        { id: "qualify", title: "Qualifier l’atteinte avant de choisir la procédure", paragraphs: ["Il faut déterminer qui occupait effectivement le terrain, depuis quand, de quelle manière et comment la situation a changé. La violence, les menaces, la fraude, l’absence du possesseur ou un simple désaccord de bornage ne conduisent pas nécessairement à la même qualification.", "Dans une indivision familiale, l’usage par un cohéritier doit aussi être distingué de l’entrée d’un tiers. Les droits de chacun et l’existence d’un partage antérieur peuvent modifier l’analyse."], bullets: ["Identifier la parcelle et ses limites réelles.", "Dater le dernier état paisible de possession et le changement constaté.", "Recueillir les identités des occupants, voisins et témoins sans provoquer d’affrontement."] },
        { id: "evidence", title: "Préserver les preuves sans aggraver le conflit", paragraphs: ["Les actes, certificats, plans et documents successoraux éclairent les droits. Les photographies datées, procès-verbaux, sommations, factures d’exploitation et témoignages peuvent éclairer la possession et la chronologie.", "Il est déconseillé de reprendre le terrain par la force ou de détruire les installations. Une telle réaction peut créer un nouveau contentieux et altérer les preuves utiles."], note: "En cas de tensions ou de risque pour les personnes, la sécurité prime. Les faits urgents doivent être signalés aux autorités compétentes." },
        { id: "routes", title: "Articuler les voies pénale, civile et foncière", paragraphs: ["Une plainte fondée sur l’article 570 exige l’examen de ses conditions propres. Parallèlement ou alternativement, une demande civile peut viser la possession, la cessation d’un trouble, la restitution ou la reconnaissance d’un droit, selon les faits.", "Pour un terrain immatriculé, le titre et les inscriptions sont essentiels. Pour un terrain non immatriculé ou rural, la chaîne des actes, la possession, les limites et l’éventuelle procédure d’immatriculation doivent être reconstituées."], bullets: ["Éviter de multiplier des demandes contradictoires.", "Coordonner la preuve technique des limites avec l’argumentation juridique.", "Suivre séparément les délais et décisions de chaque procédure."] },
      ],
      checklistTitle: "Dossier de première urgence", checklistIntro: "L’objectif est d’identifier le terrain et de figer la chronologie.", checklist: ["Titre foncier, Melkiya, actes et pièces successorales.", "Plans, coordonnées, repères et photographies datées.", "Constats, plaintes, sommations et correspondances.", "Preuves d’exploitation, d’entretien ou d’occupation antérieure.", "Identité des personnes présentes et chronologie détaillée des faits."],
      faqTitle: "Questions sur la dépossession d’un terrain", faqs: [
        { question: "Que faire si quelqu’un occupe mon terrain au Maroc ?", answer: "Il faut d’abord identifier la parcelle, préserver les preuves de vos droits et de la possession, puis qualifier le mode d’entrée. La démarche appropriée dépend du titre, des faits, de l’urgence et des personnes concernées." },
        { question: "Puis-je reprendre mon terrain moi-même ?", answer: "Une reprise par la force peut exposer les personnes et compliquer le dossier. Il est préférable de faire constater la situation et d’utiliser la voie légale adaptée." },
        { question: "L’article 570 s’applique-t-il à toute occupation ?", answer: "Non. Ce texte comporte des conditions qui doivent être caractérisées. Un litige de propriété, de limites ou entre coindivisaires ne devient pas automatiquement une infraction pénale." },
        { question: "Un titre foncier suffit-il pour obtenir l’évacuation ?", answer: "Le titre est déterminant pour les droits inscrits, mais la demande, l’identité de l’occupant, son éventuel titre et les circonstances doivent aussi être examinés." },
      ],
      ctaTitle: "Votre terrain vient d’être occupé ou clôturé ?", ctaText: "Le cabinet analyse les droits, la possession, les limites et l’urgence afin d’organiser les preuves et la procédure.", serviceLabel: "Foncier rural et agricole", sourcesLabel: "Textes officiels", sources: [{ label: "Ministère de la Justice — Code pénal, article 570", url: penalCode }, { label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }],
    },
    ar: {
      slug: "انتزاع-عقار-من-حيازة-الغير", seo: { title: "انتزاع عقار من حيازة الغير: الإثبات والإجراءات", description: "دليل انتزاع عقار من حيازة الغير بالمغرب: إثبات الحيازة والمعاينة والفصل 570 والتمييز بين المساطر المدنية والجنحية." }, category: "الحيازة والاحتلال",
      h1: "انتزاع عقار من حيازة الغير في القانون المغربي", lead: "عند إخراج شخص من أرض كان يحوزها، يجب التمييز بسرعة بين الحيازة والملكية وظروف الاستيلاء وضرورة الحفاظ على الأدلة.",
      intro: ["قد يتعلق الأمر بإزاحة سياج أو إتلاف غرس أو بناء أو دخول شخص إلى الأرض. ولا تكفي عبارة الاستيلاء على العقار لاختيار الإجراء، بل يجب بحث المعاينة والشكاية ودعاوى الحيازة أو الملكية بحسب الوقائع.", "يعاقب الفصل 570 من القانون الجنائي على انتزاع عقار من حيازة الغير متى توفرت شروطه. ولا يتحقق ذلك تلقائياً في كل خلاف حول الحدود أو نزاع عائلي، إذ يلزم إثبات الوقائع والعناصر القانونية المطلوبة."],
      takeaways: ["الحيازة والملكية مسألتان مختلفتان.", "ينبغي توثيق المكان والتاريخ وكيفية الانتزاع بسرعة.", "المسطرة الجنحية المحتملة لا تغني دائماً عن معالجة النزاع المدني أو العقاري."],
      sections: [
        { id: "qualify", title: "تكييف الاعتداء قبل اختيار المسطرة", paragraphs: ["ينبغي معرفة من كان يحوز الأرض فعلياً ومدة حيازته وكيف تغير الوضع. فالعنف أو التهديد أو التدليس أو استغلال غياب الحائز أو مجرد اختلاف حول الحدود لا يؤدي بالضرورة إلى التكييف نفسه.", "إذا كانت الأرض مشاعة بين أفراد الأسرة، يجب التمييز بين تصرف أحد الورثة ودخول شخص أجنبي، مع فحص حصص الأطراف ووجود قسمة سابقة من عدمه."], bullets: ["تحديد القطعة وحدودها الفعلية.", "ضبط آخر وضع هادئ للحيازة وتاريخ تغييره.", "تحديد الموجودين والمجاورين والشهود دون الدخول في مواجهة."] },
        { id: "evidence", title: "الحفاظ على الأدلة دون تصعيد النزاع", paragraphs: ["تفيد الرسوم والشهادات والتصاميم ووثائق الإرث في بيان الحقوق، بينما تساعد الصور المؤرخة والمحاضر والإنذارات ووثائق الاستغلال والشهادات في إثبات الحيازة والتسلسل الزمني.", "لا يستحسن استرجاع الأرض بالقوة أو هدم ما أقامه الطرف الآخر، لأن ذلك قد ينشئ نزاعاً جديداً ويؤثر في الأدلة."], note: "عند وجود تهديد للأشخاص، تعطى الأولوية للسلامة وإبلاغ السلطات المختصة بالوقائع المستعجلة." },
        { id: "routes", title: "تنسيق المساطر الجنحية والمدنية والعقارية", paragraphs: ["تستلزم الشكاية المبنية على الفصل 570 فحص شروطه الخاصة. وقد تكون هناك، إلى جانبها أو بدلها، دعوى مدنية تتعلق بالحيازة أو رفع الضرر أو الاسترداد أو ثبوت الحق بحسب الوقائع.", "في العقار المحفظ يعتمد الفحص على الرسم العقاري والتقييدات. أما العقار غير المحفظ أو القروي، فينبغي تتبع الرسوم والحيازة والحدود ومسطرة التحفيظ إن وجدت."], bullets: ["تجنب تقديم طلبات متعارضة.", "ربط الخبرة التقنية للحدود بالحجج القانونية.", "تتبع آجال وقرارات كل مسطرة بصورة مستقلة."] },
      ],
      checklistTitle: "وثائق المعالجة الأولية", checklistIntro: "الهدف هو تحديد الأرض وتثبيت التسلسل الزمني للوقائع.", checklist: ["الرسم العقاري أو رسم الملكية والعقود ووثائق الإرث.", "التصاميم والإحداثيات والعلامات والصور المؤرخة.", "المعاينات والشكايات والإنذارات والمراسلات.", "ما يثبت الاستغلال أو الصيانة أو الحيازة السابقة.", "هوية الأشخاص الموجودين وتسلسل مفصل للوقائع."],
      faqTitle: "أسئلة حول انتزاع العقار", faqs: [
        { question: "ماذا أفعل إذا استولى شخص على أرضي؟", answer: "ينبغي تحديد القطعة والحفاظ على أدلة الحقوق والحيازة ثم معرفة كيفية الدخول إليها. ويتوقف الإجراء على الوثائق والوقائع والاستعجال وصفة الأطراف." },
        { question: "هل يمكنني استرجاع الأرض بنفسي؟", answer: "قد يؤدي استعمال القوة إلى تعريض الأشخاص للخطر وتعقيد الملف. والأفضل إثبات الحالة وسلوك المسطرة القانونية المناسبة." },
        { question: "هل يطبق الفصل 570 على كل احتلال للعقار؟", answer: "لا. يتطلب الفصل شروطاً يجب إثباتها، ولا يتحول نزاع الملكية أو الحدود أو الخلاف بين الشركاء تلقائياً إلى جريمة." },
        { question: "هل يكفي الرسم العقاري لإفراغ المحتل؟", answer: "للرسم العقاري أهمية أساسية في إثبات الحقوق المقيدة، لكن يجب أيضاً فحص الطلب وصفة الموجود بالعقار وما يدعيه من سند وظروف دخوله." },
      ],
      ctaTitle: "هل تم احتلال أرضكم أو تغيير حدودها؟", ctaText: "يفحص المكتب الحقوق والحيازة والحدود والاستعجال لتنظيم الأدلة وتحديد المسطرة.", serviceLabel: "العقار الفلاحي وأراضي الجموع", sourcesLabel: "النصوص الرسمية", sources: [{ label: "وزارة العدل — القانون الجنائي، الفصل 570", url: penalCode }, { label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }],
    },
  },
};

export const encroachmentGuide: GuideDefinition = {
  key: "encroachment", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "foncierRural", relatedGuides: ["dispossession", "ownership-claim", "immatriculation"],
  content: {
    fr: {
      slug: "empietement-terrain-autrui-maroc", seo: { title: "Empiètement sur un terrain au Maroc : recours", description: "Bornage déplacé, construction ou empiètement au Maroc : preuves, plans, expertise, mise en demeure et actions à examiner." }, category: "Limites et empiètement",
      h1: "Empiètement sur le terrain d’autrui au Maroc : protéger sa propriété", lead: "Un mur, une clôture, une plantation ou une construction qui dépasse une limite exige de prouver à la fois le droit invoqué et l’emplacement exact de cette limite.",
      intro: ["Les litiges d’empiètement naissent souvent d’une discordance entre les actes, les plans et les repères visibles sur place. En zone rurale, les anciennes confrontations et les limites naturelles peuvent avoir changé.", "Avant d’accuser un voisin d’avoir pris une partie du terrain, il faut localiser juridiquement et techniquement la bande contestée. Le constat décrit l’état des lieux ; il ne remplace pas toujours le travail topographique ni la preuve du droit."],
      takeaways: ["L’identité de la parcelle et la limite exacte doivent être établies.", "Un constat et une expertise n’ont pas la même fonction.", "La solution peut être amiable, technique ou judiciaire selon les titres et l’occupation."],
      sections: [
        { id: "verify", title: "Comparer titres, plans et situation réelle", paragraphs: ["Pour un bien immatriculé, le titre foncier, le plan et les opérations cadastrales constituent le point de départ. Pour un terrain non immatriculé, l’analyse relie les actes, les confrontations, la possession et les relevés disponibles.", "Une différence de superficie ne permet pas seule d’identifier l’empiètement. Il faut rattacher les mesures à la parcelle exacte et contrôler les références des propriétés voisines."], bullets: ["Obtenir les documents fonciers récents.", "Conserver les anciens plans et procès-verbaux de bornage.", "Repérer les modifications physiques et leur date approximative."] },
        { id: "prove", title: "Faire constater puis mesurer utilement", paragraphs: ["Des photographies et un constat peuvent préserver l’apparence des lieux à une date donnée. Une opération technique peut ensuite comparer les limites documentaires avec les ouvrages, cultures ou clôtures présents.", "L’expert ne tranche pas à lui seul la propriété. Sa mission, les documents communiqués et la possibilité pour chaque partie de présenter ses observations sont essentiels à la valeur de l’analyse."], note: "Ne déplacez pas vous-même les bornes ou la clôture contestée avant d’avoir documenté la situation et évalué les conséquences." },
        { id: "resolve", title: "Négocier ou saisir la juridiction compétente", paragraphs: ["Si les documents permettent une solution claire, un accord précis peut fixer la limite, les travaux et les formalités foncières nécessaires. Un simple arrangement oral risque toutefois de déplacer le conflit sans le résoudre.", "À défaut d’accord, les demandes judiciaires possibles dépendent du statut du bien, des droits invoqués, de l’ouvrage réalisé et du préjudice. Il faut formuler des demandes cohérentes avec la preuve technique."], bullets: ["Adresser une mise en demeure adaptée lorsque cela est utile.", "Chiffrer et justifier le préjudice allégué.", "Prévoir l’exécution pratique et les formalités après l’accord ou le jugement."] },
      ],
      checklistTitle: "Préparer un dossier d’empiètement", checklistIntro: "Réunissez ce qui permet d’identifier la limite avant et après la modification.", checklist: ["Titre foncier ou actes de propriété des parcelles concernées.", "Plans cadastraux, croquis et procès-verbaux de bornage.", "Photographies anciennes et récentes avec dates disponibles.", "Constats, échanges avec le voisin et autorisations de construire éventuelles.", "Coordonnées des personnes connaissant l’ancienne limite."],
      faqTitle: "Questions sur l’empiètement", faqs: [
        { question: "Comment prouver qu’un voisin empiète sur mon terrain ?", answer: "Il faut rapprocher les droits et plans de la situation réelle. Un constat préserve l’état visible ; une mesure ou expertise peut localiser la limite et l’ouvrage contesté." },
        { question: "Puis-je démolir le mur construit sur mon terrain ?", answer: "Une démolition unilatérale peut créer des risques juridiques et matériels. Il faut d’abord établir la limite et utiliser la démarche amiable ou judiciaire adaptée." },
        { question: "Le cadastre prouve-t-il toujours la propriété ?", answer: "La portée d’un plan dépend du statut du bien et des documents auxquels il se rattache. Il doit être analysé avec le titre ou les actes et les opérations de bornage." },
        { question: "Un accord avec le voisin suffit-il ?", answer: "Un accord peut résoudre le conflit s’il décrit précisément la limite, les travaux et les formalités. Sa forme et sa publicité doivent être adaptées au statut foncier du bien." },
      ],
      ctaTitle: "Une limite ou une construction empiète sur votre terrain ?", ctaText: "Le cabinet rapproche les titres, les plans et les constatations pour définir une stratégie cohérente.", serviceLabel: "Foncier rural et agricole", sourcesLabel: "Sources officielles", sources: [{ label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }, { label: "ANCFCC — conservation foncière et cadastre", url: ancfcc }],
    },
    ar: {
      slug: "الترامي-على-ملك-الغير-في-المغرب", seo: { title: "الترامي على ملك الغير في المغرب: ما العمل؟", description: "دليل الترامي على ملك الغير بالمغرب: إثبات الحدود والتصاميم والمعاينة والخبرة والإنذار والمساطر الممكنة." }, category: "الحدود والتعدي",
      h1: "الترامي على ملك الغير في المغرب: كيف تحمون أرضكم؟", lead: "يستلزم تجاوز سور أو سياج أو بناء لحدود العقار إثبات الحق المدعى به وتحديد موقع الحد الفاصل بدقة.",
      intro: ["تنشأ منازعات الترامي غالباً بسبب عدم التطابق بين الرسوم والتصاميم والمعالم الموجودة في الميدان. وقد تتغير المجاورات القديمة والحدود الطبيعية، خصوصاً في المناطق القروية.", "قبل الجزم بأن الجار أخذ جزءاً من الأرض، يجب تحديد المساحة المتنازع عليها قانونياً وتقنياً. فالمعاينة تصف الحالة الظاهرة، لكنها لا تعوض دائماً القياس الطبوغرافي وإثبات الحق."],
      takeaways: ["يجب إثبات هوية القطعة وموقع الحد الفاصل.", "تختلف وظيفة المعاينة عن وظيفة الخبرة.", "قد يكون الحل رضائياً أو تقنياً أو قضائياً بحسب الرسوم والحيازة."],
      sections: [
        { id: "verify", title: "مطابقة الرسوم والتصاميم مع الواقع", paragraphs: ["في العقار المحفظ ينطلق الفحص من الرسم العقاري والتصميم والعمليات المساحية. أما العقار غير المحفظ، فتربط الدراسة بين الرسوم والحدود والحيازة والقياسات المتاحة.", "لا يكفي اختلاف المساحة وحده لتحديد الترامي، بل يجب ربط القياسات بالقطعة الصحيحة والتحقق من مراجع العقارات المجاورة."], bullets: ["الحصول على وثائق عقارية حديثة.", "حفظ التصاميم القديمة ومحاضر التحديد.", "تحديد التغييرات الميدانية وتاريخها التقريبي."] },
        { id: "prove", title: "إثبات الحالة وقياس الحدود", paragraphs: ["تساعد الصور والمعاينة على حفظ وصف المكان في تاريخ محدد. وقد يستلزم الأمر بعد ذلك عملية تقنية تقارن الحدود الواردة في الوثائق بالبناء أو الغرس أو السياج الموجود.", "لا يحسم الخبير الملكية بمفرده. وتؤثر مهمته والوثائق المقدمة إليه وتمكين الأطراف من إبداء ملاحظاتهم في قيمة النتيجة."], note: "لا تنقلوا العلامات أو السياج المتنازع عليه قبل توثيق الحالة وتقييم الآثار القانونية." },
        { id: "resolve", title: "التفاوض أو اللجوء إلى القضاء", paragraphs: ["إذا كانت الوثائق تسمح بحل واضح، يمكن لاتفاق دقيق أن يحدد الحد والأشغال والإجراءات العقارية اللازمة. أما الاتفاق الشفهي فقد يؤجل النزاع دون أن ينهيه.", "عند تعذر الاتفاق، تتوقف الطلبات القضائية على وضع العقار والحقوق المدعى بها والمنشآت والضرر. وينبغي أن تنسجم الطلبات مع الإثبات التقني."], bullets: ["توجيه إنذار مناسب عند الحاجة.", "تحديد الضرر المدعى به وإثباته.", "تنظيم تنفيذ الاتفاق أو الحكم والإجراءات اللاحقة."] },
      ],
      checklistTitle: "إعداد ملف الترامي", checklistIntro: "اجمعوا ما يساعد على تحديد الحدود قبل التغيير وبعده.", checklist: ["الرسم العقاري أو رسوم ملكية القطع المعنية.", "التصاميم ومحاضر التحديد والرسوم الطبوغرافية.", "صور قديمة وحديثة مع تواريخها إن أمكن.", "المعاينات والمراسلات ورخص البناء عند الاقتضاء.", "بيانات من يعرفون موضع الحد القديم."],
      faqTitle: "أسئلة حول الترامي على الملك", faqs: [
        { question: "كيف أثبت أن جاراً ترامى على أرضي؟", answer: "يجب مطابقة الحقوق والتصاميم مع الواقع. تحفظ المعاينة وصف الحالة، ويمكن للقياس أو الخبرة تحديد الحد والمنشأة المتنازع عليها." },
        { question: "هل يمكنني هدم السور المبني داخل أرضي؟", answer: "قد تترتب عن الهدم الفردي مخاطر قانونية ومادية. وينبغي أولاً إثبات الحد وسلوك الإجراء الرضائي أو القضائي المناسب." },
        { question: "هل يثبت التصميم المساحي الملكية دائماً؟", answer: "تتوقف قيمة التصميم على وضع العقار والوثائق المرتبط بها. لذلك يفحص مع الرسم العقاري أو رسوم الملكية وعمليات التحديد." },
        { question: "هل يكفي الاتفاق مع الجار؟", answer: "يمكن للاتفاق أن ينهي النزاع إذا حدد الحدود والأشغال والإجراءات بدقة، على أن تكون صيغته وإشهاره ملائمين للوضع القانوني للعقار." },
      ],
      ctaTitle: "هل تجاوز سياج أو بناء حدود أرضكم؟", ctaText: "يطابق المكتب الرسوم والتصاميم والمعاينات لبناء استراتيجية متماسكة.", serviceLabel: "العقار الفلاحي وأراضي الجموع", sourcesLabel: "المصادر الرسمية", sources: [{ label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }, { label: "الوكالة الوطنية للمحافظة العقارية والمسح العقاري", url: ancfcc }],
    },
  },
};

export const saleOthersPropertyGuide: GuideDefinition = {
  key: "sale-others-property", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "immobilier", relatedGuides: ["caveat", "ownership-claim", "melkiya"],
  content: {
    fr: {
      slug: "vente-bien-autrui-maroc", seo: { title: "Vente du bien d’autrui au Maroc : droits et recours", description: "Un bien a été vendu par une personne non propriétaire ? Vérifications, effets du contrat, titre foncier, bonne foi et recours au Maroc." }, category: "Vente et propriété",
      h1: "Vente du bien d’autrui au Maroc : vérifications et recours", lead: "Lorsqu’une personne vend un immeuble ou une quote-part qui ne lui appartient pas, les effets ne se déduisent pas d’une formule unique : le contrat, le statut du bien et les inscriptions doivent être examinés.",
      intro: ["Le conflit peut naître d’une fausse qualité de propriétaire, d’une succession non réglée, d’un mandat dépassé, d’une double vente ou d’une erreur sur la parcelle. Il faut identifier ce qui a réellement été vendu et par qui.", "Pour un immeuble immatriculé, la publicité foncière joue un rôle central. Pour un bien non immatriculé, la chaîne des actes, la possession et les règles contractuelles doivent être analysées ensemble."],
      takeaways: ["Vérifier l’identité du vendeur et l’étendue exacte de ses droits.", "Distinguer la validité du contrat, son opposabilité et la responsabilité des parties.", "Agir sur la base du titre, des actes et des dates, pas sur une simple copie isolée."],
      sections: [
        { id: "detect", title: "Identifier la vente et le droit qui manquait au vendeur", paragraphs: ["Un vendeur peut être totalement étranger au bien, ne détenir qu’une quote-part ou agir sans pouvoir suffisant. La réponse dépend de cette situation et de la rédaction du contrat.", "Dans une succession, un héritier ne peut pas être traité comme propriétaire exclusif de tous les biens indivis. Il faut déterminer les droits transmis et l’objet exact de l’acte."], bullets: ["Contrôler identité, capacité et procuration du vendeur.", "Comparer la désignation du bien dans tous les actes.", "Vérifier titres, réquisitions, inscriptions et successions." ] },
        { id: "effects", title: "Distinguer contrat, transfert du droit et dommages", paragraphs: ["Le Code des obligations et des contrats encadre la vente de la chose d’autrui et ses conséquences. L’analyse peut concerner l’efficacité du transfert, les possibilités de confirmation ou d’acquisition ultérieure du droit, ainsi que les restitutions et dommages éventuels.", "La bonne ou mauvaise foi des personnes, la connaissance du conflit et les inscriptions réalisées peuvent influencer certaines demandes. Aucun résultat ne doit être affirmé avant lecture de l’acte complet."], note: "La formule « vente nulle automatiquement » est souvent trop simplificatrice : le régime applicable et les demandes doivent être qualifiés à partir du dossier." },
        { id: "protect", title: "Protéger le propriétaire et sécuriser la position de l’acquéreur", paragraphs: ["Le propriétaire doit réunir ses preuves, surveiller la situation foncière et évaluer rapidement les mesures conservatoires ou judiciaires utiles. L’acquéreur doit vérifier les garanties du vendeur et les demandes possibles liées au prix payé.", "Si l’acte concerne une parcelle rurale ou non immatriculée, l’identification du terrain et la chaîne de transmission deviennent déterminantes. Une expertise peut être nécessaire si deux actes semblent viser la même assiette."], bullets: ["Obtenir un état foncier récent lorsqu’il existe.", "Conserver preuves de paiement et échanges précontractuels.", "Éviter une nouvelle cession avant clarification de la situation." ] },
      ],
      checklistTitle: "Documents à faire examiner", checklistIntro: "Le dossier doit permettre de comparer le droit du vendeur et l’engagement pris.", checklist: ["Contrat contesté et annexes.", "Titre foncier, certificat ou actes de propriété antérieurs.", "Procurations et documents successoraux.", "Preuves de paiement, messages et mises en demeure.", "Plans et éléments identifiant précisément le bien."],
      faqTitle: "Questions sur la vente du bien d’autrui", faqs: [
        { question: "La vente du bien d’autrui est-elle toujours nulle au Maroc ?", answer: "Ses effets doivent être appréciés selon le Code des obligations et des contrats, la situation du véritable titulaire, le contenu de l’acte et le statut foncier. Une réponse automatique sans examen du dossier serait imprudente." },
        { question: "Que peut faire le véritable propriétaire ?", answer: "Il peut faire vérifier ses preuves, les inscriptions et l’acte contesté afin de choisir les demandes propres à protéger ou faire reconnaître son droit. L’urgence dépend notamment des opérations déjà publiées." },
        { question: "L’acheteur de bonne foi est-il automatiquement propriétaire ?", answer: "La bonne foi ne suffit pas à elle seule pour conclure. Ses effets dépendent du statut du bien, de la publicité foncière, des actes et des règles applicables." },
        { question: "Que faire en cas de double vente du même terrain ?", answer: "Il faut comparer les actes, leurs dates, leurs auteurs, la parcelle concernée et les formalités de publicité. La priorité ne peut pas être déduite du seul ordre des signatures." },
      ],
      ctaTitle: "Un bien a été vendu sans l’accord de son propriétaire ?", ctaText: "Le cabinet examine la chaîne des droits, le contrat, les inscriptions et les paiements avant de définir les demandes possibles.", serviceLabel: "Droit immobilier", sourcesLabel: "Textes officiels", sources: [{ label: "Ministère de la Justice — Code des obligations et des contrats", url: obligationsCode }, { label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }, { label: "Ministère de la Justice — dahir sur l’immatriculation foncière", url: landRegistrationLaw }],
    },
    ar: {
      slug: "بيع-ملك-الغير-في-القانون-المغربي", seo: { title: "بيع ملك الغير في القانون المغربي: الآثار والحلول", description: "دليل بيع ملك الغير بالمغرب: فحص صفة البائع والعقد والرسم العقاري وحسن النية والطلبات الممكنة للمالك والمشتري." }, category: "البيع والملكية",
      h1: "بيع ملك الغير في القانون المغربي: الآثار والطلبات الممكنة", lead: "إذا باع شخص عقاراً أو حصة لا يملكها، فلا يمكن تحديد النتيجة بعبارة واحدة؛ إذ يجب فحص العقد ووضع العقار والتقييدات.",
      intro: ["قد ينشأ النزاع بسبب ادعاء صفة المالك أو تركة غير مصفاة أو تجاوز حدود الوكالة أو بيعين متعارضين أو خطأ في تحديد القطعة. لذلك يجب معرفة المبيع الحقيقي وصفة من باعه.", "في العقار المحفظ تكتسي التقييدات أهمية مركزية، بينما يستلزم العقار غير المحفظ تتبع الرسوم والحيازة والقواعد التعاقدية معاً."],
      takeaways: ["التحقق من هوية البائع وحدود حقوقه.", "التمييز بين العقد وانتقال الحق ومسؤولية الأطراف.", "بناء الإجراء على الرسوم والعقود والتواريخ لا على نسخة معزولة."],
      sections: [
        { id: "detect", title: "تحديد البيع والحق الذي لم يكن يملكه البائع", paragraphs: ["قد يكون البائع أجنبياً عن العقار أو مالكاً لحصة فقط أو متصرفاً دون وكالة كافية. ويختلف التعامل القانوني بحسب هذه الحالة وصياغة العقد.", "لا يعامل أحد الورثة كمالك منفرد لجميع أموال التركة المشاعة. لذلك يجب تحديد الحقوق المنتقلة إليه والمحل الدقيق للعقد."], bullets: ["التحقق من هوية البائع وأهليته ووكالته.", "مقارنة وصف العقار في جميع الوثائق.", "فحص الرسوم والمطالب والتقييدات ووثائق الإرث."] },
        { id: "effects", title: "التمييز بين العقد وانتقال الحق والتعويض", paragraphs: ["ينظم قانون الالتزامات والعقود بيع ملك الغير وآثاره. وقد يتعلق البحث بنفاذ انتقال الحق وإمكان الإقرار أو اكتساب البائع للحق لاحقاً، فضلاً عن الاسترداد والتعويض عند الاقتضاء.", "قد تؤثر معرفة الأشخاص بالنزاع وحسن أو سوء النية والتقييدات المنجزة في بعض الطلبات. ولا يمكن الجزم بالنتيجة قبل قراءة العقد كاملاً."], note: "القول ببطلان كل بيع لملك الغير بصورة آلية تبسيط غير دقيق؛ إذ يجب تكييف النظام والطلبات على ضوء الملف." },
        { id: "protect", title: "حماية المالك وتأمين مركز المشتري", paragraphs: ["على المالك جمع حججه ومراقبة الوضعية العقارية وتقييم الإجراءات التحفظية أو القضائية المناسبة بسرعة. أما المشتري، فينبغي أن يفحص ضمانات البائع والطلبات المرتبطة بالثمن المؤدى.", "إذا تعلق العقد بأرض قروية أو غير محفظة، يصبح تحديد القطعة وتسلسل انتقال الحقوق أساسياً. وقد تلزم خبرة إذا بدا أن عقدين يشملان الوعاء نفسه."], bullets: ["الحصول على شهادة عقارية حديثة عند وجود رسم عقاري.", "حفظ إثباتات الأداء والمراسلات السابقة للتعاقد.", "تجنب تفويت جديد قبل توضيح الوضعية."] },
      ],
      checklistTitle: "وثائق ينبغي فحصها", checklistIntro: "يجب أن يتيح الملف مقارنة حق البائع بالالتزام الذي تعهد به.", checklist: ["العقد المتنازع عليه ومرفقاته.", "الرسم العقاري أو الشهادة أو الرسوم السابقة.", "الوكالات ووثائق الإرث.", "إثباتات الأداء والمراسلات والإنذارات.", "التصاميم وكل ما يحدد العقار بدقة."],
      faqTitle: "أسئلة حول بيع ملك الغير", faqs: [
        { question: "هل بيع ملك الغير باطل دائماً في المغرب؟", answer: "تحدد آثاره وفق قانون الالتزامات والعقود ووضع المالك الحقيقي ومضمون العقد والنظام العقاري. ولا يصح إعطاء جواب آلي دون فحص الملف." },
        { question: "ماذا يمكن أن يفعل المالك الحقيقي؟", answer: "عليه فحص حججه والتقييدات والعقد المتنازع عليه لاختيار الطلبات المناسبة لحماية حقه أو إثباته. وتتأثر درجة الاستعجال بالعمليات التي تم إشهارها." },
        { question: "هل يصبح المشتري حسن النية مالكاً تلقائياً؟", answer: "لا تكفي حسن النية وحدها للجزم بذلك، إذ تتوقف الآثار على وضع العقار والإشهار والرسوم والقواعد القانونية المطبقة." },
        { question: "ماذا أفعل عند بيع الأرض مرتين؟", answer: "ينبغي مقارنة العقود وتواريخها وأطرافها والقطعة المقصودة وإجراءات الإشهار. ولا تستخلص الأولوية من ترتيب التوقيع وحده." },
      ],
      ctaTitle: "هل بيع العقار دون موافقة مالكه؟", ctaText: "يفحص المكتب تسلسل الحقوق والعقد والتقييدات والأداءات قبل تحديد الطلبات الممكنة.", serviceLabel: "القانون العقاري", sourcesLabel: "النصوص الرسمية", sources: [{ label: "وزارة العدل — قانون الالتزامات والعقود", url: obligationsCode }, { label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }, { label: "وزارة العدل — ظهير التحفيظ العقاري", url: landRegistrationLaw }],
    },
  },
};

export const ownershipClaimGuide: GuideDefinition = {
  key: "ownership-claim", publishedAt: "2026-09-27", updatedAt: "2026-09-27", serviceKey: "foncierRural", relatedGuides: ["melkiya", "sale-others-property", "encroachment"],
  content: {
    fr: {
      slug: "action-revendication-propriete-maroc", seo: { title: "Action en revendication de propriété au Maroc", description: "Revendiquer un terrain au Maroc : identifier le bien, prouver la propriété, répondre aux actes adverses et préparer l’expertise." }, category: "Preuve de la propriété",
      h1: "Action en revendication de propriété au Maroc : preuves et préparation", lead: "Revendiquer un immeuble suppose d’établir son droit sur une parcelle précisément identifiée et de répondre aux actes et à la possession invoqués par l’adversaire.",
      intro: ["Dire « ce terrain m’appartient » ne suffit pas devant une contestation. Le demandeur doit relier ses titres, successions ou autres modes d’acquisition au terrain effectivement occupé.", "La stratégie diffère entre immeuble immatriculé, terrain en cours d’immatriculation et bien non immatriculé. Il faut aussi distinguer une revendication de propriété d’une demande uniquement fondée sur la possession ou sur un contrat."],
      takeaways: ["La parcelle revendiquée doit être identifiable sans ambiguïté.", "La chaîne des droits doit être reconstituée jusqu’au demandeur.", "Les pièces adverses et la possession doivent être analysées, pas ignorées."],
      sections: [
        { id: "identify", title: "Identifier le bien objet de la revendication", paragraphs: ["Les noms locaux, les anciennes confrontations et les superficies approximatives peuvent désigner des terrains différents. Plans, limites, accès, références voisines et opérations de bornage permettent de rattacher les actes au terrain.", "Si la demande porte sur une partie seulement, cette emprise doit être localisée. Une expertise mal préparée ne peut pas compenser une désignation incohérente dans les actes."], bullets: ["Comparer toutes les désignations et superficies.", "Repérer les parcelles et titres voisins.", "Documenter les limites et l’occupation actuelle." ] },
        { id: "rights", title: "Reconstituer l’origine et la continuité des droits", paragraphs: ["La preuve peut impliquer des actes de propriété, ventes, donations, successions, décisions ou inscriptions. Il faut montrer comment le droit est passé jusqu’à la personne qui agit.", "Une rupture dans les actes, une différence de nom ou une succession non liquidée doit être expliquée. Les documents doivent aussi être confrontés à ceux produits par la partie adverse."], note: "La force probante de chaque document dépend du régime du bien et du contexte. Une Melkiya et un titre foncier ne produisent pas les mêmes effets." },
        { id: "litigation", title: "Formuler la demande et préparer l’expertise", paragraphs: ["La juridiction, les parties à appeler et les demandes dépendent du statut du bien et de la nature du conflit. Une demande mal définie peut laisser subsister une difficulté d’exécution même après jugement.", "Lorsque les limites ou l’identité de la parcelle sont contestées, l’expertise doit recevoir des documents complets et une mission utile. Les observations faites pendant les opérations doivent être cohérentes avec les actes invoqués."], bullets: ["Identifier tous les détenteurs et titulaires concernés.", "Présenter une chronologie lisible des droits et de l’occupation.", "Préparer les points techniques à soumettre à l’expert." ] },
      ],
      checklistTitle: "Constituer le dossier de propriété", checklistIntro: "Classez les pièces par origine du droit, identification du terrain et occupation.", checklist: ["Titre foncier, Melkiya et actes de transmission.", "Actes de succession, procurations et décisions antérieures.", "Plans, procès-verbaux, photographies et repères de limites.", "Pièces de l’adversaire déjà communiquées.", "Preuves d’exploitation, d’entretien et chronologie de la possession."],
      faqTitle: "Questions sur la revendication de propriété", faqs: [
        { question: "Quels documents prouvent la propriété d’un terrain au Maroc ?", answer: "Ils dépendent du statut du terrain : titre et inscriptions pour un immeuble immatriculé, ou ensemble d’actes, transmissions et éléments pertinents pour un bien non immatriculé. Les documents doivent correspondre à la parcelle réelle." },
        { question: "Peut-on revendiquer une partie seulement d’un terrain ?", answer: "La demande peut concerner une emprise déterminée, mais cette partie doit être localisée précisément et reliée aux droits invoqués. Les plans et mesures sont alors essentiels." },
        { question: "La possession suffit-elle pour gagner une action en propriété ?", answer: "La possession peut avoir une importance juridique, surtout selon le statut du bien, mais elle ne doit pas être isolée des actes, de sa durée, de ses caractères et des moyens adverses." },
        { question: "Pourquoi une expertise foncière est-elle ordonnée ?", answer: "Elle peut aider à identifier la parcelle, comparer les plans et matérialiser les limites. Elle éclaire les faits techniques mais ne remplace pas l’appréciation juridique du tribunal." },
      ],
      ctaTitle: "Votre propriété est contestée ?", ctaText: "Le cabinet reconstitue les droits, identifie la parcelle et prépare les questions juridiques et techniques du dossier.", serviceLabel: "Foncier rural et agricole", sourcesLabel: "Textes et organisme officiels", sources: [{ label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }, { label: "Ministère de la Justice — dahir sur l’immatriculation foncière", url: landRegistrationLaw }, { label: "ANCFCC — conservation foncière et cadastre", url: ancfcc }],
    },
    ar: {
      slug: "دعوى-الاستحقاق-في-القانون-المغربي", seo: { title: "دعوى الاستحقاق في القانون المغربي: الإثبات", description: "دليل دعوى الاستحقاق العقارية بالمغرب: تحديد الأرض وإثبات الملكية وتسلسل الحقوق والرد على حجج الخصم والخبرة." }, category: "إثبات الملكية",
      h1: "دعوى الاستحقاق في القانون المغربي: إثبات الملكية وتحديد العقار", lead: "تتطلب المطالبة بملكية عقار إثبات الحق في قطعة محددة بدقة والجواب عن الرسوم والحيازة التي يتمسك بها الطرف الآخر.",
      intro: ["لا يكفي القول إن الأرض مملوكة للمدعي عند وجود منازعة، بل يجب ربط الرسوم والإرث أو أسباب التملك الأخرى بالعقار الموجود فعلياً.", "تختلف الاستراتيجية بحسب كون العقار محفظاً أو في طور التحفيظ أو غير محفظ. كما ينبغي التمييز بين دعوى الاستحقاق ودعوى مبنية فقط على الحيازة أو على عقد."],
      takeaways: ["يجب تحديد القطعة المطلوبة دون غموض.", "ينبغي تتبع انتقال الحقوق إلى المدعي.", "يجب مناقشة حجج الخصم وحيازته وعدم الاكتفاء بتجاهلها."],
      sections: [
        { id: "identify", title: "تحديد العقار موضوع الاستحقاق", paragraphs: ["قد تشير الأسماء المحلية والحدود القديمة والمساحات التقريبية إلى قطع مختلفة. وتساعد التصاميم والحدود والمسالك ومراجع العقارات المجاورة وعمليات التحديد على ربط الرسوم بالأرض.", "إذا انصب الطلب على جزء من العقار، وجب تحديده بدقة. ولا تعوض الخبرة غير المحضرة وصفاً متناقضاً للعقار في الوثائق."], bullets: ["مقارنة جميع الأوصاف والمساحات.", "تحديد القطع والرسوم المجاورة.", "توثيق الحدود والحيازة الحالية."] },
        { id: "rights", title: "تتبع أصل الملكية وتسلسل انتقال الحقوق", paragraphs: ["قد يعتمد الإثبات على رسوم الملكية والبيوع والهبات والإرث والأحكام والتقييدات. وينبغي بيان كيفية انتقال الحق إلى الشخص الذي رفع الدعوى.", "يجب تفسير الانقطاع في الرسوم أو اختلاف الأسماء أو عدم تصفية التركة، مع مقارنة وثائق المدعي بما يدلي به الطرف الآخر."], note: "تختلف حجية الوثيقة بحسب النظام القانوني للعقار والسياق؛ فرسم الملكية لا ينتج الآثار نفسها التي ينتجها الرسم العقاري." },
        { id: "litigation", title: "صياغة الطلب والاستعداد للخبرة", paragraphs: ["تتوقف المحكمة المختصة والأطراف والطلبات على وضع العقار وطبيعة النزاع. وقد يبقى الحكم صعب التنفيذ إذا لم يحدد الطلب بصورة سليمة.", "عند النزاع في الحدود أو هوية القطعة، ينبغي تزويد الخبير بوثائق كاملة وتحديد مهمة مفيدة. كما يجب أن تنسجم الملاحظات المقدمة أثناء الخبرة مع الرسوم المعتمدة."], bullets: ["تحديد جميع الحائزين وأصحاب الحقوق المعنيين.", "عرض تسلسل واضح للحقوق والحيازة.", "إعداد النقاط التقنية المطلوب بحثها في الخبرة."] },
      ],
      checklistTitle: "إعداد ملف إثبات الملكية", checklistIntro: "رتبوا الوثائق بحسب أصل الحق وتحديد الأرض والحيازة.", checklist: ["الرسم العقاري أو رسم الملكية وعقود انتقال الحقوق.", "وثائق الإرث والوكالات والأحكام السابقة.", "التصاميم والمحاضر والصور وعلامات الحدود.", "وثائق الخصم التي تم الاطلاع عليها.", "أدلة الاستغلال والصيانة وتسلسل الحيازة."],
      faqTitle: "أسئلة حول دعوى الاستحقاق", faqs: [
        { question: "ما الوثائق التي تثبت ملكية أرض في المغرب؟", answer: "تختلف بحسب وضع الأرض: الرسم والتقييدات في العقار المحفظ، أو مجموعة الرسوم وانتقال الحقوق والعناصر ذات الصلة في العقار غير المحفظ. ويجب أن تطابق الوثائق القطعة الفعلية." },
        { question: "هل يمكن المطالبة بجزء من أرض؟", answer: "يمكن أن يتعلق الطلب بجزء محدد، لكن يجب تحديد موقعه وربطه بالحقوق المدعى بها بدقة. وتكتسي التصاميم والقياسات أهمية خاصة في هذه الحالة." },
        { question: "هل تكفي الحيازة لكسب دعوى الملكية؟", answer: "قد تكون للحيازة أهمية قانونية بحسب وضع العقار، لكنها تفحص مع الرسوم ومدتها وصفاتها وحجج الطرف الآخر، ولا ينبغي عزلها عن باقي عناصر الملف." },
        { question: "لماذا تأمر المحكمة بخبرة عقارية؟", answer: "قد تساعد الخبرة على تحديد القطعة ومقارنة التصاميم وتجسيد الحدود. وهي توضح المسائل التقنية، بينما يبقى التكييف القانوني من اختصاص المحكمة." },
      ],
      ctaTitle: "هل ينازع شخص في ملكيتكم للأرض؟", ctaText: "يتتبع المكتب أصل الحقوق ويحدد القطعة ويعد الجوانب القانونية والتقنية للملف.", serviceLabel: "العقار الفلاحي وأراضي الجموع", sourcesLabel: "النصوص والجهات الرسمية", sources: [{ label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }, { label: "وزارة العدل — ظهير التحفيظ العقاري", url: landRegistrationLaw }, { label: "الوكالة الوطنية للمحافظة العقارية والمسح العقاري", url: ancfcc }],
    },
  },
};
