import type { GuideDefinition } from "@/lib/guide-types";

const ancfccProcedure = "https://ancfcc.gov.ma/ProcedureNormale/";
const ancfccTexts = "https://www.ancfcc.gov.ma/espace-media/publications/";
const expropriationLaw = "https://www.sgg.gov.ma/Portals/1/textesconsolides/7_81.pdf";

export const immatriculationGuide: GuideDefinition = {
  key: "immatriculation",
  publishedAt: "2026-09-26",
  updatedAt: "2026-09-26",
  serviceKey: "immobilier",
  content: {
    fr: {
      slug: "titre-foncier-conservation-fonciere-maroc",
      seo: { title: "Titre foncier et conservation foncière au Maroc", description: "Comprendre le titre foncier au Maroc : immatriculation, bornage, opposition, frais et vérifications auprès de la conservation foncière." },
      category: "Immatriculation foncière",
      h1: "Titre foncier et conservation foncière au Maroc",
      lead: "De la réquisition d’immatriculation à l’établissement du titre foncier, chaque étape engage la preuve de la propriété, les limites du bien et les droits des tiers.",
      intro: [
        "L’immatriculation foncière soumet un immeuble au régime des livres fonciers et conduit, lorsque la procédure aboutit, à la création d’un titre foncier. Elle ne se résume pas au dépôt d’un formulaire : les actes, la localisation, la publicité, le bornage et les éventuelles oppositions doivent être examinés ensemble.",
        "Une difficulté peut apparaître avant le dépôt, pendant le bornage, lors d’une opposition ou à l’occasion d’une inscription ultérieure. Le bon réflexe consiste à identifier exactement le statut du terrain et l’étape de la procédure avant de choisir une démarche.",
      ],
      takeaways: [
        "Le titre foncier résulte d’une procédure d’immatriculation ; il ne se confond pas avec un acte de propriété concernant un terrain non immatriculé.",
        "Le bornage est à la fois une opération topographique, une mesure de publicité et une étape d’enquête sur place.",
        "Une opposition ou une incohérence entre les actes et le terrain doit être traitée en tenant compte des délais et des pièces disponibles.",
      ],
      sections: [
        { id: "statut", title: "Distinguer le titre foncier des autres documents", paragraphs: ["Le titre foncier identifie un immeuble immatriculé et les droits qui y sont inscrits. Un certificat de propriété récent permet de connaître la situation publiée à une date donnée, notamment les propriétaires inscrits et les charges mentionnées.", "Pour un terrain non immatriculé, l’analyse porte sur les actes invoqués, leur chaîne de transmission, la possession, les plans et la concordance avec la situation matérielle. Employer le mot « titre » pour tous les documents masque donc une différence juridique essentielle."], bullets: ["Vérifier le numéro du titre et la conservation foncière compétente.", "Comparer le certificat de propriété, l’acte et le plan.", "Rechercher les hypothèques, saisies, servitudes ou autres inscriptions utiles."] },
        { id: "procedure", title: "Les étapes de l’immatriculation foncière", paragraphs: ["Selon la présentation officielle de l’ANCFCC, la procédure ordinaire comprend notamment le dépôt et l’enrôlement de la réquisition, la publicité, le bornage, l’établissement du plan foncier puis la décision du conservateur.", "La demande doit être appuyée par les actes et documents susceptibles de faire connaître le droit invoqué. La procédure peut aboutir à l’immatriculation, mais aussi connaître une annulation, un rejet ou une transmission au tribunal lorsqu’une opposition subsiste."], bullets: ["Repérage préalable et dépôt de la réquisition.", "Publication et affichage de l’extrait avec avis de bornage.", "Bornage en présence des personnes concernées ou susceptibles de l’être.", "Décision après vérification des formalités et des oppositions."] },
        { id: "verifications", title: "Vérifier un bien avant une opération", paragraphs: ["Avant une vente, une acquisition, un partage ou une garantie, il faut rapprocher les informations de la conservation foncière de l’état réel du bien. Un numéro exact ne suffit pas si la parcelle visitée, sa superficie ou ses limites ne correspondent pas aux documents.", "La vérification porte aussi sur l’identité et la capacité des parties, l’origine de propriété, les pouvoirs du mandataire, les inscriptions et les conditions prévues dans l’acte. Une difficulté détectée tôt est généralement plus simple à traiter qu’un conflit après signature."], note: "Une consultation en ligne ou un certificat ne remplace pas l’examen de l’ensemble des actes lorsqu’une anomalie, une succession ou un litige de limites existe." },
        { id: "litiges", title: "Opposition, bornage et contestation", paragraphs: ["Une personne qui prétend disposer d’un droit sur le terrain faisant l’objet d’une réquisition peut être amenée à former une opposition selon les conditions et délais applicables. Le dossier doit préciser le droit revendiqué, son étendue et les pièces qui le soutiennent.", "Les conflits de bornage et de chevauchement exigent souvent de mettre en regard les actes, les plans cadastraux, les repères sur place et l’historique de la possession. Selon l’état de la procédure, la réponse peut être administrative, amiable, technique ou judiciaire."], bullets: ["Conserver les avis, convocations et récépissés avec leur date.", "Faire identifier précisément la parcelle et les limites discutées.", "Éviter toute démarche fondée sur un document isolé ou une simple déclaration orale."] },
      ],
      checklistTitle: "Documents utiles pour une première analyse",
      checklistIntro: "La liste exacte dépend du statut du bien et de la difficulté rencontrée. Ces pièces permettent généralement de reconstituer une première chronologie.",
      checklist: ["Certificat de propriété récent ou numéro complet du titre foncier.", "Actes de vente, donations, actes adoulaires, décisions ou autres documents invoqués.", "Plans, croquis, procès-verbaux de bornage et références cadastrales disponibles.", "Avis de publication, convocations, récépissés et correspondances avec la conservation foncière.", "Pièces relatives à la succession ou aux mandats lorsque le bien appartient à plusieurs personnes."],
      faqTitle: "Questions fréquentes sur le titre foncier",
      faqs: [
        { question: "Comment consulter un titre foncier au Maroc ?", answer: "Il faut disposer des références exactes du titre et s’adresser aux services de l’ANCFCC ou utiliser les services officiels disponibles. Pour sécuriser une opération, la consultation doit être complétée par un certificat récent et l’examen des actes." },
        { question: "Combien de temps dure une immatriculation foncière ?", answer: "Il n’existe pas une durée identique pour tous les dossiers. La publicité, le bornage, les diligences du requérant, les difficultés techniques et les oppositions éventuelles influencent la durée." },
        { question: "Que faire si les limites réelles ne correspondent pas au plan ?", answer: "Il faut identifier l’origine de l’écart, réunir les plans et actes disponibles et vérifier si une opération technique, une rectification, une expertise ou une procédure contentieuse est appropriée." },
        { question: "Le titre foncier peut-il comporter une hypothèque ou une saisie ?", answer: "Oui. Les droits et charges inscrits doivent être vérifiés sur un document récent avant toute opération. Leur effet et leur radiation éventuelle dépendent de leur nature et des justificatifs produits." },
      ],
      ctaTitle: "Une difficulté avec un titre foncier ?",
      ctaText: "Le cabinet examine les actes, les inscriptions, les plans et l’état de la procédure afin d’identifier les mesures adaptées au dossier.",
      serviceLabel: "Droit immobilier",
      sourcesLabel: "Sources institutionnelles",
      sources: [{ label: "ANCFCC — procédure ordinaire d’immatriculation", url: ancfccProcedure }, { label: "ANCFCC — textes et publications foncières", url: ancfccTexts }],
    },
    ar: {
      slug: "التحفيظ-العقاري-في-المغرب",
      seo: { title: "مسطرة التحفيظ العقاري في المغرب: من إيداع المطلب إلى تأسيس الرسم العقاري", description: "دليل مسطرة التحفيظ العقاري في المغرب: إيداع المطلب، عمليات التحديد، آجال النشر والتعليق، وحجية الرسم العقاري المطلقة وفق ظهير 12 غشت 1913 والقانون 14.07." },
      category: "التحفيظ العقاري ومساطر المحافظة",
      h1: "مسطرة التحفيظ العقاري في المغرب: من إيداع المطلب إلى تأسيس الرسم العقاري",
      lead: "تخضع مسطرة التحفيظ العقاري لمقتضيات ظهير 12 غشت 1913 المعدل والمتمم بالقانون رقم 14.07، حيث تترتب على تأسيس الرسم العقاري آثار تطهيرية حاسمة تسقط كافة الحقوق غير المقيدة.",
      intro: [
        "يهدف التحفيظ العقاري إلى إخضاع الملك العقاري للنظام العيني وإشهار الحقوق العينية المترتبة عليه، وتتوج المسطرة بقرار المحافظ بتأسيس رسم عقاري يكسب الملكية حجية مطلقة ونهائية وغير قابلة للطعن (الفصلان 1 و62 من ظهير التحفيظ العقاري).",
        "تبدأ المسطرة بإيداع مطلب التحفيظ مدعماً بأصول الرسوم وسندات التملك، وتمر عبر عمليات التحديد القانوني والهندسي برئاسة مهندس مساح طبوغرافي محلف منتدب من المحافظة العقارية، مع إشهار ونشر خلاصة المطلب بالجريدة الرسمية وتعليقها بالمحكمة والسلطة المحلية.",
      ],
      takeaways: [
        "الرسم العقاري يتمتع بحجية نهائية وتطهيرية مطلقة؛ ولا يمكن إبطاله أو الطعن فيه بأي وجه بعد تأسيسه (الفصل 62 من ظهير التحفيظ العقاري).",
        "عملية التحديد هي إجراء قانوني وإشهاري وميداني جوهري يترتب على التخلف عنه دون عذر مقبول إلغاء المطلب.",
        "أجل التعرض العادي محدد قانوناً في شهرين من تاريخ نشر الإشعار بانتهاء التحديد بالجريدة الرسمية (الفصل 24).",
      ],
      sections: [
        { id: "statut", title: "الحجية المطلقة للرسم العقاري وقاعدة التطهير", paragraphs: ["يكتسب الرسم العقاري المؤسس بمقتضى قرار المحافظ على الأملاك العقارية قوة ثبوتية قطعية؛ إذ يطهر العقار من جميع الحقوق السابقة غير المسجلة، ولا يترك للمتضرر في حال ثبوت التدليس سوى حق المطالبة بالتعويض المالي الشخصي ضد مرتكب التدليس (الفصل 64 من ظهير 1913).", "أما في العقار غير المحفظ (الملكية العدلية)، فتظل الحقوق خاضعة لقواعد الإثبات الشرعية في مدونة الحقوق العينية، وتكون الملكية قابلة للطعن والمنازعة بالاستحقاق أو الحيازة المكسبة. لذلك يُعد التحفيظ الضمانة القانونية القصوى للملكية العقارية."], bullets: ["التحقق من رقم الرسم العقاري وخلوه من التقييدات الاحتياطية أو الحجوزات أو الرهون الرسمية.", "مطابقة التصميم العقاري الطبوغرافي مع واقع البناء والحدود على الأرض.", "سحب شهادة الملكية والبيان المساحي من بوابة الوكالة الوطنية للمحافظة العقارية."] },
        { id: "procedure", title: "المراحل القانونية والإجرائية لمسطرة التحفيظ", paragraphs: ["يودع المطلب بالمحافظة العقارية المختصة مكانياً مشفوعاً بأصول الرسوم ومصاريف الوجيبة، ويعين المحافظ تاريخ عملية التحديد التي يقوم بها مهندس مساح طبوغرافي مع وضع الأنصاب والحدود المؤقتة وتحرير محضر رسمي.", "تتولى المحافظة إشهار خلاصة المطلب وتاريخ التحديد بالجريدة الرسمية وتوجيه ملخصات للتعليق بالمحكمة الابتدائية ومقر السلطة المحلية، ويفتح أجل شهرين من تاريخ نشر إشعار انتهاء التحديد بالجريدة الرسمية لتلقي التعرضات."], bullets: ["إيداع مطلب التحفيظ وسندات التملك وأداء الرسوم الواجبة.", "نشر خلاصة المطلب بالجريدة الرسمية وتوجيه الإعلانات للتعليق.", "إنجاز عملية التحديد الميداني ووضع الأنصاب بحضور المجاورين وطالب التحفيظ.", "انصرام أجل التعرضات وإصدار قرار تأسيس الرسم العقاري أو الإحالة على القضاء."] },
        { id: "verifications", title: "التدقيق القانوني للعقار قبل التعاقد والتفويت", paragraphs: ["يلزم فحص شهادة الملكية العقارية والتأكد من تطابق هوية المالك وحصصه الشائعة، وخلو الرسم من تقييد احتياطي مبني على دعوى استحقاق، أو حجز تحفظي أو تنفيذي لفائدة الخزينة أو الأغيار، أو ارتفاقات عدم البناء وحق المرور.", "يجب التأكد من مطابقة الحدود الطبوغرافية للتصميم العقاري؛ إذ إن تداخل البناء في ملك الجار أو الممر العام قد يؤدي إلى دعاوى الهدم والتعويض حتى في العقار المحفظ."], note: "حصول المشتري على شهادة عقارية خالية من التقييدات لا يعفيه من فحص العقار ميدانياً للتأكد من عدم وجود حائز فعلي أو منازعة جارية لم يتم تقييدها بعد." },
        { id: "litiges", title: "منازعات مسطرة التحفيظ والتعرضات أمام القضاء", paragraphs: ["يحق لكل ذي مصلحة ينازع في أصل الحق أو مداه أو حدوده إيداع تعرضه كتابة أو شفاهة أمام المحافظة العقارية داخل أجل شهرين من نشر انتهاء التحديد (الفصل 24)، أو تقديم تعرض استثنائي أمام المحافظ بشروط مشددة قبل تأسيس الرسم (الفصل 29).", "في حال عدم تسوية التعرض صلحاً، يحيل المحافظ الملف على المحكمة الابتدائية المختصة للبت في صحة التعرض من عدمه دون البت في أصل ملكية طالب التحفيظ، ويتحمل المتعرض عبء إثبات ادعائه بصفته مدعياً في دعوى التحفيظ."], bullets: ["احترام الآجال القانونية للتعرض وأداء الوجيبة القضائية ورسوم التوصيل داخل أجل 3 أشهر من توجيه الملف للمحكمة.", "تقديم سندات تملك ورسوم عدلية مستوفية لشروط الحيازة والإثبات الشرعي.", "طلب إجراء معاينة قضائية وخبرة طبوغرافية لتطبيق الرسوم عند تداخل الحدود."] },
      ],
      checklistTitle: "الوثائق الضرورية لملف مسطرة التحفيظ والتعرض",
      checklistIntro: "تتوقف سلامة الملف على التدقيق المستندي المسبق وجمع الرسوم الثبوتية قبل مباشرة الإجراءات لدى المحافظة العقارية.",
      checklist: ["أصول الرسوم العدلية أو العقود الرسمية المثبتة للملكية وسلسلة التفويتات.", "شهادة الملكية العقارية أو وصل إيداع مطلب التحفيظ ومراجعه.", "التصميم العقاري الطبوغرافي المنجز من طرف مهندس مساح طبوغرافي معتمد.", "محاضر التحديد المؤقت وإشعارات النشر بالجريدة الرسمية.", "رسم الإراثة والوكالات الرسمية عند تعدّد المالكين أو الورثة."],
      faqTitle: "أسئلة شائعة حول مسطرة التحفيظ العقاري بالمغرب",
      faqs: [
        { question: "ما هي القيمة القانونية للرسم العقاري بعد تأسيسه من طرف المحافظ؟", answer: "يحظى الرسم العقاري بحجية مطلقة وتطهيرية نهائية وفق الفصل 62 من ظهير التحفيظ العقاري؛ حيث يبطل كل ما عداه من الرسوم السابقة ويطهر العقار من كافة الادعاءات بالملكية، ولا يجوز الطعن فيه بأي وجه أمام القضاء حتى ولو استند الطاعن إلى رسوم ملكية صحيحة سابقة." },
        { question: "ما هو الأجل القانوني لتقديم التعرض على مطلب التحفيظ العقاري؟", answer: "الأجل العادي هو شهران يبتدئان من تاريخ نشر الإشعار بانتهاء التحديد في الجريدة الرسمية (الفصل 24)؛ ويمكن بصفة استثنائية للمحافظ قبول تعرض خارج هذا الأجل وقبل توجيه الملف للمحكمة إذا أدلى المتعرض بأسباب قاهرة تبرر تأخره وأرفق وثائق الإثبات (الفصل 29)." },
        { question: "من يتحمل عبء الإثبات في دعاوى التعرض المحالة على القضاء العقاري؟", answer: "يُعتبر المتعرض بمثابة المدعي في دعوى التحفيظ طبقاً لاجتهاد محكمة النقض المستقر، وعليه يقع عبء إثبات حقوقه وتقديم حججه ورسومه الدامغة؛ فإذا عجز عن إثبات حيازته أو صحة سنده حُكم بعدم صحة تعرضه واستمرت مسطرة التحفيظ لفائدة طالب التحفيظ." },
        { question: "ما أثر التقييد الاحتياطي (Prénotation) على الرسم العقاري؟", answer: "التقييد الاحتياطي هو إجراء تحفظي يُسجل بالرسم العقاري للحفاظ مؤقتاً على رتبة حق عيني متنازع بشأنه (الفصل 85 من ظهير 1913)؛ وتختلف مدته بين 10 أيام بناءً على سند، أو شهر بناءً على أمر رئيس المحكمة يمدد لـ 6 أشهر إذا رُفعت دعوى في الموضوع، أو طيلة سريان الدعوى إذا قُدم مقال افتتاحي للدعوى." },
      ],
      ctaTitle: "هل ترغبون في مباشرة مسطرة تحفيظ عقاركم أو مواجهة تعرض جائر؟",
      ctaText: "تفضلوا بعرض رسومكم ومستنداتكم على مكتب الأستاذ عبد الرزاق الرويسي لدراسة الملف وتأمين ملكيتكم وصيانتها طبقاً لظهير التحفيظ العقاري.",
      serviceLabel: "القانون العقاري والتحفيظ",
      sourcesLabel: "المصادر الرسمية",
      sources: [{ label: "الوكالة الوطنية للمحافظة العقارية — المسطرة العادية", url: "https://www.ancfcc.gov.ma/arnos-m%C3%A9tiers/conservation-fonci%C3%A8re-cadastre/procedure-normale/" }, { label: "الوكالة الوطنية للمحافظة العقارية — النصوص والمنشورات", url: ancfccTexts }],
    },
  },
};

export const expropriationGuide: GuideDefinition = {
  key: "expropriation", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "administratif",
  content: {
    fr: {
      slug: "expropriation-indemnisation-maroc",
      seo: { title: "Expropriation et indemnisation au Maroc", description: "Procédure d’expropriation au Maroc, indemnité, expertise, prise de possession et recours : les points à vérifier pour défendre ses droits." },
      category: "Expropriation",
      h1: "Expropriation au Maroc : procédure, indemnité et recours",
      lead: "Une expropriation pour cause d’utilité publique suit une procédure encadrée. La propriété, la consistance du bien, les délais et l’évaluation de l’indemnité doivent être documentés avec précision.",
      intro: ["La loi n° 7-81 organise l’expropriation pour cause d’utilité publique et l’occupation temporaire. Le dossier comporte une phase administrative et peut donner lieu à une phase judiciaire, notamment pour le transfert de propriété, la prise de possession et la fixation de l’indemnité.", "Le propriétaire ou titulaire de droits doit suivre les actes de procédure et réunir sans attendre les éléments relatifs au bien et à sa valeur. Une réponse tardive ou un dossier incomplet peut compliquer la discussion sur les droits concernés et l’indemnisation."],
      takeaways: ["L’utilité publique, la cessibilité, le transfert de propriété et l’indemnité sont des questions distinctes.", "L’estimation doit être étayée par la situation juridique, les caractéristiques et l’usage du bien.", "Les notifications et dates de procédure doivent être conservées et vérifiées dès leur réception."],
      sections: [
        { id: "procedure", title: "Comprendre les phases de l’expropriation", paragraphs: ["La procédure commence par des actes administratifs destinés à établir l’utilité publique et à identifier les biens concernés. Leur contenu, leur publication et leur portée doivent être lus en fonction du projet et de la parcelle.", "Lorsque l’accord n’aboutit pas, le juge peut être saisi des demandes prévues par la loi. Il faut alors distinguer les mesures relatives à la possession, au transfert de propriété et à l’indemnité."], bullets: ["Identifier l’acte déclaratif et le plan du projet.", "Vérifier si toute la parcelle ou seulement une partie est concernée.", "Conserver les notifications et les références de la procédure."] },
        { id: "rights", title: "Établir la propriété et les droits concernés", paragraphs: ["L’indemnisation suppose d’identifier les propriétaires et autres titulaires de droits. Le titre foncier, les actes, la succession ou les droits d’occupation doivent être clarifiés, notamment lorsqu’un bien est indivis ou non immatriculé.", "Pour une terre agricole, il faut aussi documenter l’exploitation, les plantations, les constructions autorisées, l’accès et les conséquences de l’emprise sur la partie restante."], note: "Un conflit entre héritiers ou une chaîne de propriété incomplète doit être traité parallèlement, sans perdre de vue les échéances propres à l’expropriation." },
        { id: "indemnity", title: "Discuter l’indemnité sur des éléments vérifiables", paragraphs: ["La contestation d’une évaluation ne peut reposer sur une estimation abstraite. Les références pertinentes, la superficie, la destination du terrain, les équipements et les éléments effectivement affectés doivent être réunis.", "Une expertise peut devenir déterminante. Il convient alors de préparer les documents et observations permettant de décrire le bien, son environnement et les préjudices juridiquement pris en compte."], bullets: ["Actes et documents fonciers.", "Plans d’emprise et mesures de la surface concernée.", "Éléments objectifs de valeur et caractéristiques de l’exploitation.", "Constats, photographies et justificatifs des aménagements existants."] },
        { id: "reaction", title: "Réagir à une notification ou à une prise de possession", paragraphs: ["Dès réception d’un avis, d’une offre ou d’un acte judiciaire, il faut vérifier sa nature, la juridiction ou l’administration concernée et le délai utile. Toutes les correspondances doivent être datées et conservées.", "L’objectif d’une première analyse est de déterminer les droits à faire valoir, les documents manquants et la voie adaptée : observations, négociation, expertise, intervention dans la procédure ou recours." ] },
      ],
      checklistTitle: "Préparer un dossier d’expropriation",
      checklistIntro: "La qualité du dossier dépend autant de la preuve des droits que de la description exacte du bien et de l’emprise.",
      checklist: ["Titre foncier, certificat de propriété, actes ou documents de propriété.", "Actes de succession et identité des ayants droit, le cas échéant.", "Avis, arrêtés, notifications, offres et actes judiciaires reçus.", "Plan de la parcelle et plan d’emprise du projet.", "Photographies, autorisations, éléments d’exploitation et références utiles à l’évaluation."],
      faqTitle: "Questions fréquentes sur l’expropriation",
      faqs: [
        { question: "Peut-on contester le montant proposé ?", answer: "Une offre peut être discutée lorsque les éléments du dossier le justifient. Il faut alors produire une argumentation documentée sur les droits, la consistance du bien et les éléments pertinents pour son évaluation." },
        { question: "Que se passe-t-il si le terrain appartient à plusieurs héritiers ?", answer: "Les droits et qualités des héritiers doivent être établis. L’indivision ne fait pas disparaître la procédure d’expropriation, mais elle impose d’identifier les ayants droit et de coordonner la défense de leurs intérêts." },
        { question: "Une partie seulement du terrain peut-elle être expropriée ?", answer: "Oui, une emprise peut ne concerner qu’une partie du bien. Il faut alors vérifier sa délimitation et examiner les conséquences sur la partie restante selon les circonstances du dossier." },
        { question: "Faut-il attendre la prise de possession pour consulter ?", answer: "Non. Une analyse précoce permet de vérifier les actes, les délais, la parcelle visée et les éléments d’évaluation avant que la procédure n’avance davantage." },
      ],
      ctaTitle: "Un terrain concerné par une expropriation ?", ctaText: "Présentez les notifications, les actes et le plan disponibles afin d’identifier les délais et les premières mesures utiles.", serviceLabel: "Droit administratif",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "SGG — loi n° 7-81 sur l’expropriation et l’occupation temporaire", url: expropriationLaw }],
    },
    ar: {
      slug: "نزع-الملكية-والتعويض",
      seo: { title: "نزع الملكية للمنفعة العامة والتعويض القضائي في القانون المغربي", description: "دليل مسطرة نزع الملكية للمنفعة العامة بالمغرب: مقرر التخلي، دعوى نقل الملكية وتحديد التعويض، والطعن في الاعتداء المادي وفق القانون 7.81 واجتهادات محكمة النقض." },
      category: "نزع الملكية والقضاء الإداري",
      h1: "نزع الملكية للمنفعة العامة والتعويض القضائي في المغرب",
      lead: "تخضع مسطرة نزع الملكية للمنفعة العامة لمقتضيات القانون رقم 7.81، حيث يضمن الدستور المغربي صيانة الملكية الخاصة وعدم نزعها إلا طبقاً للإجراءات القانونية وبمقابل تعويض عادل ومسبق.",
      intro: [
        "ينظم القانون رقم 7.81 نزع الملكية لأجل المنفعة العامة والاحتلال المؤقت؛ وتمر المسطرة عبر مرحلتين: مرحلة إدارية تبدأ بإعلان المنفعة العامة ومقرر التخلي والبحث الإداري وإشهار المشروع، ومرحلة قضائية أمام المحكمة الإدارية للبت في نقل الملكية والإذن بالحيازة وتحديد التعويض العادل.",
        "يتعين على المالك فحص قرارات التخلي والآجال المسقطة، والاعتراض على تقييمات اللجنة الإدارية للتقويم المجحفة، وطلب خبرة قضائية منصفة تعكس القيمة التجارية الحقيقية للعقار والمغروسات وفقدان الاستغلال.",
      ],
      takeaways: [
        "لا تنتقل الملكية إلى الجهة النازعة للملكية إلا بصدور حكم قضائي نهائي عن المحكمة الإدارية وأداء أو إيداع التعويض بصندوق الإيداع والتدبير.",
        "يحق للمالك المطالبة بنزع ملكية مجموع العقار إذا أدى اقتطاع الجزء إلى جعله غير صالح للاستعمال المقصود منه (الفصل 23 من القانون 7.81).",
        "استيلاء الإدارة على العقار دون سلوك مسطرة القانون 7.81 يشكل اعتداءً مادياً موجباً للتعويض الكامل والشامل عن الحرمان من الملكية.",
      ],
      sections: [
        { id: "procedure", title: "المراحل الإدارية والقضائية لمسطرة نزع الملكية", paragraphs: ["تبدأ المرحلة الإدارية بنشر مرسوم إعلان المنفعة العامة بالجريدة الرسمية، يليه مقرر التخلي الذي يحدد القطع المعنية بالنزع والبحث العلني الممتد لشهرين لتلقي ملاحظات المالكين والتعويضات المقترحة من اللجنة الإدارية للتقويم.", "عند عدم حصول الاتفاق بالتراضي، ترفع الإدارة مقالاً أمام قاضي نزع الملكية بالمحكمة الإدارية للمطالبة بالإذن في الحيازة مقابل إيداع التعويض الاحتياطي، ونقل الملكية وتحديد التعويض النهائي بعد إجراء خبرة قضائية."], bullets: ["تحديد المقرر المرتبط بالمنفعة العامة وتصميم المشروع.", "التحقق مما إذا كان النزع يشمل كامل القطعة أو جزءاً منها.", "الاحتفاظ بالتبليغات ومراجع المسطرة."] },
        { id: "rights", title: "حصر الأضرار وإثبات صفة المالك وذوي الحقوق", paragraphs: ["يلزم الإدلاء بشهادة الملكية العقارية أو الرسوم العدلية الصحيحة لإثبات الصفة والمشروعية، مع استيفاء وثائق الإراثة وتحديد أنصبة الورثة عند الشياع لسحب التعويضات دون تعقيد.", "يشمل التعويض القانوني كافة عناصر الضرر المادي المباشر: قيمة الأرض العارية، المنشآت والمباني، المغروسات والآبار وشبكات الري، فضلاً عن تعويض فقدان الأصل التجاري والحرمان من الاستغلال الفلاحي."], note: "يجب معالجة النزاع بين الورثة أو النقص في تسلسل الملكية بالتوازي مع تتبع آجال مسطرة نزع الملكية." },
        { id: "indemnity", title: "مناقشة التعويض ومعايير الخبرة القضائية الإدارية", paragraphs: ["تعتمد المحكمة الإدارية في تحديد التعويض على مقتضيات الفصل 20 من القانون 7.81، الذي ينص على تقدير قيمة العقار يوم صدور مقرر التخلي دون أخذ البناءات أو الغرس المحدثة بعده بنية المضاربة بعين الاعتبار.", "يتم تكليف خبير قضائي عقاري محلف لإجراء معاينة ميدانية والاعتماد على أسعار السوق الحقيقية والمعاملات المجاورة، ويحق للمحامي مناقشة تقرير الخبرة وتقديم مذكرات تعقيبية لإصلاح أي إجحاف في التقييم."], bullets: ["الرسوم والعقود والوثائق العقارية.", "تصاميم الوعاء والمساحة المشمولة بالنزع.", "العناصر الموضوعية للقيمة وخصائص الاستغلال.", "المعاينات والصور ووثائق التجهيزات الموجودة."] },
        { id: "reaction", title: "دعاوى الاعتداء المادي ومواجهة وضع يد الإدارة الجائر", paragraphs: ["إذا أقدمت الإدارة على احتلال عقار أو شق طريق فوقه دون استصدار مقرر التخلي وإيداع التعويض طبقاً للقانون، فإن تصرفها يُكيف قانوناً بـ 'الاعتداء المادي' (Voie de fait).", "يخول الاعتداء المادي للمالك اللجوء إلى القضاء الإداري لطلب التعويض الكامل استناداً إلى قيمة العقار وقت صدور الحكم القضائي، مع المطالبة بتعويض مستقل عن الحرمان من الاستغلال طيلة مدة الاستيلاء."] },
      ],
      checklistTitle: "الوثائق الضرورية لملف نزع الملكية والتعويض",
      checklistIntro: "تتوقف قوة الملف على إثبات الحقوق وعلى الوصف الدقيق للعقار والمساحة المشمولة بالمشروع لضمان التعويض العادل.",
      checklist: ["الرسم العقاري أو شهادة الملكية أو الرسوم العدلية الأصلية للملكية.", "نسخة من مقرر التخلي وإعلان المنفعة العامة المنشورين بالجريدة الرسمية.", "تصميم الوعاء العقاري وتصميم الجزء المشمول بنزع الملكية المقتطع.", "تقارير معاينة منجز بواسطة مفوض قضائي تثبت واقع العقار والمغروسات والتجهيزات.", "رسم الإراثة والوكالات عند تعدّد الورثة والشركاء على الشياع."],
      faqTitle: "أسئلة شائعة حول نزع الملكية والتعويض بالمغرب",
      faqs: [
        { question: "هل يحق للمالك رفض مقرر نزع الملكية للمنفعة العامة؟", answer: "لا يحق للمالك منع نزع الملكية إذا ثبتت المنفعة العامة الحقيقية لمشروع عمومي (طرق، سدود، منشآت عامة)؛ لكن يحق له الطعن بالإلغاء في مشروعية مرسوم المنفعة العامة أو مقرر التخلي أمام القضاء الإداري للشطط في استعمال السلطة، أو مناقشة مدى جدية المنفعة العامة، والاعتراض الحازم على قيمة التعويض المعروض." },
        { question: "كيف يتم تحديد قيمة التعويض المالي عن نزع الملكية بالمحكمة الإدارية؟", answer: "تأمر المحكمة الإدارية بندب خبير عقاري محلف يقوم بمعاينة العقار وتحديد قيمته بناءً على موقعه، طبيعته، تجهيزاته، وأسعار المعاملات العقارية المشابهة في المنطقة وفق مقتضيات الفصل 20 من القانون 7.81؛ ويحق للطرفين مناقشة تقرير الخبير وطلب خبرة مضادة عند الاقتضاء." },
        { question: "ما هو الأجل المحدد للإدارة لرفع دعوى نقل الملكية بعد مقرر التخلي؟", answer: "تحدد مدة صلاحية مقرر إعلان المنفعة العامة في سنتين ومقرر التخلي في سنتين من تاريخ نشره بالجريدة الرسمية؛ ويتعين على الإدارة إيداع مقال نقل الملكية داخل هذا الأجل، وإلا سقطت صلاحية المقرر واستعاد المالك كامل حريته في التصرف في ملكه." },
        { question: "ما الفرق بين نزع الملكية والاعتداء المادي من طرف الإدارة؟", answer: "نزع الملكية مسطرة قانونية منظمة بالقانون 7.81 تتضمن إشهاراً وبحثاً إدارياً وأداء تعويض مسبق؛ أما الاعتداء المادي فهو استيلاء فعلي للإدارة على عقار مواطن دون سند أو مسطرة، ويختص القضاء الإداري بالحكم بتعويض يراعي القيمة الحالية للعقار والتعويض عن الحرمان من الانتفاع." },
      ],
      ctaTitle: "هل صدر مقرر نزع ملكية لعقاركم أو تعرضتم لاعتداء مادي من الإدارة؟",
      ctaText: "بادروا بعرض الإشعارات والرسوم على مكتب الأستاذ عبد الرزاق الرويسي لمؤازرتكم أمام القضاء الإداري وضمان تحصيل تعويض عادل ومنصف.",
      serviceLabel: "القضاء الإداري والتعويض",
      sourcesLabel: "المصادر الرسمية",
      sources: [{ label: "الأمانة العامة للحكومة — القانون رقم 7.81 المتعلق بنزع الملكية", url: expropriationLaw }],
    },
  },
};

export const oppositionGuide: GuideDefinition = {
  key: "opposition", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "immobilier",
  content: {
    fr: {
      slug: "opposition-immatriculation-fonciere-maroc", seo: { title: "Opposition à l’immatriculation foncière au Maroc", description: "Opposition à une réquisition d’immatriculation au Maroc : droit revendiqué, délais, preuves, bornage et phase judiciaire." }, category: "Contentieux de l’immatriculation",
      h1: "Opposition à une immatriculation foncière au Maroc", lead: "Former ou défendre une opposition exige d’identifier le droit revendiqué, la parcelle concernée, les preuves disponibles et l’étape exacte de la procédure.",
      intro: ["La publicité et le bornage d’une réquisition permettent aux personnes qui prétendent détenir un droit sur l’immeuble de se manifester. L’opposition ne doit pas être réduite à une contestation générale : elle porte sur un droit déterminé et doit être soutenue par des éléments précis.", "La stratégie varie selon que l’opposition concerne la totalité du terrain, une limite, un droit réel ou une quote-part. Elle dépend également du moment où la difficulté est découverte et de l’état administratif ou judiciaire de la procédure."],
      takeaways: ["L’objet de l’opposition et l’étendue du droit revendiqué doivent être clairement définis.", "Les actes, la possession et les limites matérielles doivent être reliés à la parcelle visée.", "Les délais et formalités ne se déduisent pas d’une information générale : ils doivent être vérifiés dans le dossier."],
      sections: [
        { id: "object", title: "Déterminer ce qui est réellement contesté", paragraphs: ["Une opposition peut concerner la propriété de tout ou partie de l’immeuble, une limite ou un autre droit susceptible d’être affecté par l’immatriculation. La première étape consiste à décrire ce droit sans ambiguïté.", "Il faut ensuite relier la prétention aux références de la réquisition, au plan et à la zone effectivement concernée. Une confusion entre deux parcelles ou entre une limite physique et une limite juridique fragilise la compréhension du dossier."], bullets: ["Référence exacte de la réquisition.", "Nature et origine du droit revendiqué.", "Surface ou limite concernée.", "Identité et qualité des personnes impliquées."] },
        { id: "proof", title: "Réunir les preuves et reconstituer la chronologie", paragraphs: ["Les actes de propriété, contrats, documents successoraux, plans, constats et éléments de possession doivent être classés par date. L’objectif est de montrer comment le droit revendiqué s’est constitué et à quelle parcelle il se rapporte.", "Pour une terre rurale, les limites peuvent être décrites par des repères anciens qui ont changé. Une confrontation technique et juridique des documents avec le terrain peut alors être nécessaire."], note: "Une attestation isolée ou une occupation récente ne doit pas être présentée comme suffisante sans analyse de l’ensemble des éléments." },
        { id: "process", title: "De la conservation foncière au tribunal", paragraphs: ["L’opposition intervient d’abord dans le cadre de la procédure d’immatriculation. Lorsque le différend n’est pas résolu et que les conditions sont réunies, le dossier peut être transmis à la juridiction compétente.", "La phase judiciaire exige de présenter les demandes, les moyens et les pièces de façon cohérente. La décision rendue s’insère ensuite dans la suite de la procédure d’immatriculation."], bullets: ["Suivre les notifications et convocations.", "Vérifier la transmission et les références judiciaires.", "Conserver une copie ordonnée de chaque pièce déposée."] },
        { id: "defence", title: "Répondre à une opposition dirigée contre son terrain", paragraphs: ["Le requérant doit examiner la nature du droit invoqué par l’opposant et les pièces produites. La réponse peut nécessiter de compléter la preuve de propriété, de clarifier les limites ou de contester la qualité et les prétentions adverses.", "Une solution amiable peut être examinée lorsqu’elle repose sur une délimitation claire et protège les droits en présence. À défaut, le dossier doit être préparé pour la procédure compétente." ] },
      ],
      checklistTitle: "Pièces à rassembler", checklistIntro: "Une opposition se prépare à partir du dossier réel de la réquisition, et non d’un modèle générique.",
      checklist: ["Récépissé et référence de la réquisition d’immatriculation.", "Avis de bornage, convocations et procès-verbal disponible.", "Actes, contrats, documents de succession et décisions invoqués.", "Plans, photographies et repères permettant d’identifier les limites.", "Copie de l’opposition, notifications et actes judiciaires éventuels."],
      faqTitle: "Questions sur l’opposition à l’immatriculation",
      faqs: [
        { question: "Qui peut former une opposition ?", answer: "La qualité dépend du droit prétendu sur l’immeuble en cours d’immatriculation. Elle doit être appréciée à partir des documents et de la nature exacte de la revendication." },
        { question: "Peut-on s’opposer uniquement sur une partie du terrain ?", answer: "Une contestation peut porter sur une partie ou une limite, mais cette emprise doit être identifiée avec précision et rattachée au droit invoqué." },
        { question: "Que devient l’opposition si aucun accord n’est trouvé ?", answer: "Selon l’état de la procédure et les conditions légales, le différend peut être transmis à la juridiction compétente. Les parties doivent alors soutenir leurs prétentions par des moyens et pièces organisés." },
        { question: "Une opposition abusive comporte-t-elle un risque ?", answer: "Le régime de l’immatriculation prévoit des conséquences pour certaines oppositions reconnues abusives, vexatoires ou de mauvaise foi. La pertinence d’une opposition doit donc être évaluée sérieusement avant d’agir." },
      ],
      ctaTitle: "Une opposition bloque la procédure ?", ctaText: "Le cabinet analyse la réquisition, le droit invoqué, les limites et les pièces afin de préparer une réponse adaptée à l’étape du dossier.", serviceLabel: "Droit immobilier",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "ANCFCC — procédure ordinaire d’immatriculation", url: ancfccProcedure }, { label: "ANCFCC — recueil des textes sur l’immatriculation", url: ancfccTexts }],
    },
    ar: {
      slug: "التعرض-على-مطلب-التحفيظ",
      seo: { title: "التعرض على مطلب التحفيظ العقاري في القانون المغربي: المساطر والآجال وعبء الإثبات", description: "دليل مسطرة التعرض على مطلب التحفيظ بالمغرب: آجال التعرض، التعرض الاستثنائي، أداء الرسوم القضائية، والإثبات أمام المحكمة وفق الفصل 24 وما بعده من ظهير 1913." },
      category: "منازعات التحفيظ العقاري",
      h1: "التعرض على مطلب التحفيظ العقاري في المغرب: القواعد والآجال والإثبات",
      lead: "يُعتبر التعرض الوسيلة القانونية الوحيدة التي خولها المشرع للأغيار لصيانة حقوقهم العينية في مواجهة طالب التحفيظ قبل تأسيس الرسم العقاري النهائي المطهِّر.",
      intro: [
        "يشكل نشر مطلب التحفيظ وإجراء التحديد القانوني فرصة للأغيار الذين يدعون حقاً عينياً على العقار لتقديم تعرضهم أمام المحافظة العقارية (الفصل 24 من ظهير التحفيظ العقاري)، بهدف منع تأسيس الرسم العقاري أو المطالبة باستثناء حقوقهم.",
        "يتطلب تقديم التعرض أو الدفاع في مواجهته تدقيقاً في موضوع النزاع (ملكية كلية، شياع، ارتفاق، أو حدود)، واحترام الآجال المسقطة، والتأكد من أداء الرسوم القضائية وحقوق المرافعة داخل الآجال تحت طائلة إلغاء التعرض بقوة القانون.",
      ],
      takeaways: [
        "أجل التعرض العادي هو شهران من تاريخ نشر انتهاء التحديد بالجريدة الرسمية، ولا يُقبل بعده إلا التعرض الاستثنائي بشروط الفصل 29.",
        "يلزم المتعرض بأداء الرسوم القضائية ورسم المرافعة داخل أجل 3 أشهر من تاريخ إنذاره من طرف المحافظ تحت طائلة إلغاء التعرض (الفصل 32).",
        "المتعرض يُعد مدعياً في دعوى التحفيظ العقاري، ويتحمل عبء الإثبات بحجج ورسوم أقوى من حجة طالب التحفيظ الحائز.",
      ],
      sections: [
        { id: "object", title: "تحديد موضوع التعرض والصفة القانونية للمتعرض", paragraphs: ["قد ينصب التعرض على ملكية مجموع العقار موضوع المطلب، أو على جزء مفرز منه، أو على حصة شائعة ناتجة عن إرث أو شراء، أو على حق عيني كالانتفاع أو الارتفاق أو الرهن، أو على مجرد تحديد الحدود.", "يتعين على المتعرض بيان صفته ومصلحته ومركزه القانوني بدقة وإرفاق كافة سندات التملك والرسوم العدلية والمستندات الثبوتية المؤيدة لادعائه طبقاً للفصل 25 من ظهير التحفيظ العقاري."], bullets: ["رقم مطلب التحفيظ واسم العقار وموقعه بدقة.", "طبيعة الحق المتنازع بشأنه ومستنده القانوني.", "بيان مساحة وحدود الجزء المشمول بالتعرض على التصميم.", "هوية وصفة المتعرض والأطراف المعنية."] },
        { id: "proof", title: "وسائل الإثبات وترجيح الرسوم أمام قضاء التحفيظ", paragraphs: ["تخضع رسوم الملكية العدلية لقواعد الترجيح الفقهية ومدونة الحقوق العينية (المادة 241)؛ حيث تُرجح البينة المستوفية لشروط الملك التام (واضع اليد، المتصرف، هادئاً، منسوباً لأصل الملك، ومستوفياً للمدة المشترطة).", "عند تدافع الحجج، تطلب المحكمة إجراء خبرة طبوغرافية لتطبيق الرسوم على أرض الواقع وتحديد معالم العقار ومقارنتها بالحدود المادية والتصاميم العقارية المعتمدة."], note: "مجرد تقديم شهادة إدارية أو إشهاد عدلي باللفيف لا يكفي لإثبات الملكية في مواجهة حائز بسند رسمي ما لم يستوفِ شروط رسم الملكية الشرعي الكامل." },
        { id: "process", title: "مسار النزاع: من المحافظة العقارية إلى المحكمة الابتدائية ومحكمة النقض", paragraphs: ["يحاول المحافظ إجراء صلح بين طالب التحفيظ والمتعرض؛ فإذا تعذر الصلح يحيل المحافظ الملف على المحكمة الابتدائية المختصة للبت في صحة التعرض من عدمه دون الحكم بالملكية لطالب التحفيظ.", "تبت المحكمة الابتدائية في حدود ما هو مدعى به في التعرض، وتقبل أحكامها الاستئناف أمام غرفة المشورة أو الغرفة العقارية بمحكمة الاستئناف، ثم الطعن بالنقض أمام محكمة النقض."], bullets: ["أداء الرسوم القضائية وحقوق المرافعة داخل أجل 3 أشهر تحت طائلة إلغاء التعرض (الفصل 32).", "تتبع إحالة الملف على كتابة ضبط المحكمة وتعيين القاضي المقرر.", "حضور عمليات الوقوف على عين المكان والمعاينة القضائية التي تأمر بها المحكمة."] },
        { id: "defence", title: "استراتيجية طالب التحفيظ في مواجهة التعرضات الكيدية", paragraphs: ["يحق لطالب التحفيظ منازعة صفة المتعرض والدفع ببطلان سنده وعدم استيفائه لشروط الحيازة أو عدم انطباق رسومه على العقار موضوع المطلب، أو الدفع بعدم أداء الرسوم القضائية لإسقاط التعرض إدارياً.", "إذا ثبت للمحكمة أن التعرض كان كيدياً أو تعسفياً وصادراً عن سوء نية، يحكم على المتعرض بغرامة مدنية لفائدة الوكالة الوطنية للمحافظة العقارية، مع حفظ حق طالب التحفيظ في المطالبة بالتعويض عن الضرر الناتج عن عرقلة التحفيظ (الفصل 48 من ظهير 1913)."] },
      ],
      checklistTitle: "الوثائق الأساسية لإقامة ومواجهة التعرض",
      checklistIntro: "يُعد التعرض انطلاقاً من وثائق مطلب التحفيظ الفعلية لضمان قبوله شكلاً وموضوعاً وتفادي الإلغاء.",
      checklist: ["وصل إيداع التعرض المتضمن لتاريخه ومراجعه بالمحافظة العقارية.", "أصول الرسوم العدلية أو العقود الرسمية المؤيدة للتعرض وسلسلة التملك.", "محضر التحديد المؤقت والتصميم الطبوغرافي المنجز من طرف المحافظة.", "وصل أداء الرسوم القضائية وحقوق المرافعة لدى صندوق كتابة الضبط.", "المقالات والمذكرات الجوابية وتقارير الخبرات القضائية السابقة إن وجدت."],
      faqTitle: "أسئلة شائعة حول التعرض على مطلب التحفيظ بالمغرب",
      faqs: [
        { question: "ما هو الأجل الحاسم لأداء الرسوم القضائية بعد إحالة التعرض على القضاء؟", answer: "ينص الفصل 32 من ظهير التحفيظ العقاري المعدل بالقانون 14.07 على أنه يتعين على المتعرض أداء الوجيبة القضائية وحقوق المرافعة داخل أجل 3 أشهر من تاريخ تبليغه بالإنذار؛ فإذا لم يؤدها داخل هذا الأجل اعتبر تعرضه لاغياً بقوة القانون وأمر المحافظ بمواصلة التحفيظ دون الرجوع إلى القضاء." },
        { question: "هل يمكن تقديم تعرض استثنائي بعد انصرام أجل الشهرين القانوني؟", answer: "نعم، يجوز بصورة استثنائية للمحافظ على الأملاك العقارية قبول تعرض خارج الأجل طبقاً للفصل 29، شريطة تقديمه قبل توجيه الملف إلى كتابة ضبط المحكمة الابتدائية، مع إدلاء المتعرض بالوثائق والمستندات الدامغة وتبرير الأسباب القاهرة التي منعته من تقديم التعرض داخل الأجل القانوني." },
        { question: "ما هو الدور المحدد للمحكمة عند البت في ملف التحفيظ العقاري؟", answer: "ينحصر اختصاص المحكمة في البت في وجود الحق المدعى به من طرف المتعرض ومدى صحته ونطاقه، ولا تحكم المحكمة أبداً بتمليك العقار لطالب التحفيظ؛ فإذا قضت بصحة التعرض كلياً أو جزئياً فإن المحافظ يمتثل للحكم بتعديل المطلب أو إلغائه، وإذا قضت بعدم صحته يستمر المحافظ في إجراءات تأسيس الرسم العقاري." },
        { question: "ما هي عواقب التعرض التعسفي الصادر بسوء نية لابتزاز طالب التحفيظ؟", answer: "ينص الفصل 48 من ظهير التحفيظ العقاري على أن كل تعرض يثبت أنه تعسفي أو كيدي يعاقب صاحبه بغرامة مدنية لصالح الوكالة لا تقل عن 10% من قيمة العقار، بالإضافة إلى حق طالب التحفيظ في مقاضاة المتعرض للمطالبة بتعويضات مدنية كاملة عن تعطيل استغلال العقار أو ضياع فرصة البيع." },
      ],
      ctaTitle: "هل رُفع تعرض جائر ضد مطلبكم أو ترغبون في قيد تعرض لحماية عقاركم؟",
      ctaText: "تواصلوا مع مكتب الأستاذ عبد الرزاق الرويسي بالمحمدية لتدقيق الوثائق والمساطر ونيابة قانونية محكمة أمام المحافظة العقارية وقضاء التحفيظ.",
      serviceLabel: "القانون العقاري وقضاء التحفيظ",
      sourcesLabel: "المصادر الرسمية",
      sources: [{ label: "الوكالة الوطنية للمحافظة العقارية — المسطرة العادية", url: "https://www.ancfcc.gov.ma/arnos-m%C3%A9tiers/conservation-fonci%C3%A8re-cadastre/procedure-normale/" }, { label: "الوكالة الوطنية للمحافظة العقارية — النصوص القانونية", url: ancfccTexts }],
    },
  },
};
