import type { GuideDefinition } from "@/lib/guide-types";

const propertyLawPortal = "https://adala.justice.gov.ma/resources/25";
const ancfccProcedure = "https://ancfcc.gov.ma/ProcedureNormale/";
const realRightsCode = "https://adala.justice.gov.ma/api/uploads/2024/03/05/Code%20des%20droits%20r%C3%A9els-1709645301691.pdf";
const civilProcedureCode = "https://adala.justice.gov.ma/api/uploads/2024/02/28/Code%20de%20proc%C3%A9dure%20civile-1709129409071.pdf";

export const soulaliyatesGuide: GuideDefinition = {
  key: "soulaliyates", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "foncierRural",
  content: {
    fr: {
      slug: "terres-collectives-soulaliyates-maroc", seo: { title: "Terres collectives et soulaliyates au Maroc", description: "Comprendre les terres collectives et soulaliyates au Maroc : ayants droit, jouissance, délimitation, contestations et documents utiles." }, category: "Foncier rural",
      h1: "Terres collectives et soulaliyates au Maroc", lead: "Le statut collectif ne se traite pas comme une propriété privée ordinaire. La communauté, les ayants droit, la tutelle administrative et la situation de chaque parcelle doivent être distingués.",
      intro: ["Les terres des collectivités soulaliyates sont soumises à un cadre particulier, notamment la loi n° 62-17 relative à la tutelle administrative et à la gestion de leurs biens et la loi n° 63-17 concernant leur délimitation administrative.", "Une contestation peut porter sur la qualité d’ayant droit, une décision de jouissance, une limite, une indemnité ou l’utilisation d’une parcelle. Avant toute démarche, il faut identifier le texte applicable et l’autorité ou la juridiction compétente."],
      takeaways: ["Une terre soulaliyate ne se confond pas avec un bien privé détenu en indivision.", "La qualité d’ayant droit et le droit de jouissance doivent être établis selon le régime applicable.", "Délimitation administrative, immatriculation et contestation d’une décision obéissent à des procédures différentes."],
      sections: [
        { id: "status", title: "Identifier le statut de la terre", paragraphs: ["La dénomination employée localement ne suffit pas à établir le statut juridique. Il faut vérifier les documents administratifs, les plans, les décisions, l’existence d’une délimitation et l’identité de la collectivité concernée.", "Cette qualification détermine les règles de gestion, les personnes habilitées à intervenir et les voies de contestation. Elle évite d’appliquer par erreur les règles ordinaires de vente ou de partage d’un bien privé."], bullets: ["Nom de la collectivité soulaliyate et localisation exacte.", "Décisions, listes d’ayants droit et documents de jouissance.", "Plans de délimitation, références foncières et actes administratifs."] },
        { id: "beneficiaries", title: "Ayants droit, jouissance et transmission", paragraphs: ["La qualité d’ayant droit et l’attribution d’une jouissance ne doivent pas être confondues avec un titre privé librement cessible. Les listes, décisions et conditions prévues par les textes et leurs mesures d’application doivent être vérifiées.", "En cas de décès, de désaccord familial ou de contestation d’une liste, il faut examiner la situation concrète, les notifications et les recours disponibles plutôt que présumer une transmission identique à celle d’un bien privé."], note: "La loi n° 62-17 et son décret d’application prévoient des règles propres, notamment pour la jouissance et certaines contestations. Les délais doivent être vérifiés sur la décision reçue." },
        { id: "disputes", title: "Délimitation, indemnisation et contestations", paragraphs: ["La délimitation administrative vise à préciser les limites, la superficie et la consistance des terres concernées. Une contestation exige de rapprocher les actes publiés, le plan et les droits invoqués.", "Lorsqu’un projet, une cession autorisée ou une opération donne lieu à une indemnité, l’identification des bénéficiaires et la traçabilité de la décision sont centrales. La voie appropriée dépend de l’auteur de l’acte et du type de droit contesté."], bullets: ["Lire la décision et identifier son auteur.", "Vérifier la date de notification ou de publication.", "Rassembler les documents établissant la qualité et la parcelle concernée.", "Distinguer recours administratif, contentieux et discussion sur l’indemnité."] },
      ],
      checklistTitle: "Éléments à apporter", checklistIntro: "Le dossier doit permettre d’identifier la collectivité, la parcelle, la décision contestée et la qualité de la personne concernée.",
      checklist: ["Carte d’identité et documents d’état civil utiles.", "Liste ou décision relative aux ayants droit ou à la jouissance.", "Plan, décision de délimitation et références de la parcelle.", "Notifications, procès-verbaux et correspondances avec les autorités.", "Documents relatifs à une indemnité, une occupation ou une exploitation."],
      faqTitle: "Questions sur les terres soulaliyates",
      faqs: [
        { question: "Les terres collectives et soulaliyates désignent-elles la même réalité ?", answer: "Dans l’usage marocain, les deux expressions sont souvent rapprochées. Il faut néanmoins se référer au statut juridique, à la collectivité concernée et aux documents officiels plutôt qu’à la seule appellation locale." },
        { question: "Un ayant droit peut-il vendre librement sa part ?", answer: "Le droit reconnu dans une terre soulaliyate ne fonctionne pas comme une quote-part ordinaire dans un bien privé. Toute opération doit être appréciée au regard du régime spécial et des autorisations éventuellement nécessaires." },
        { question: "Comment contester une décision concernant la jouissance ?", answer: "Il faut examiner la décision, son auteur, sa notification et les règles applicables. Les modalités et délais peuvent varier ; une analyse immédiate des pièces est recommandée." },
      ],
      ctaTitle: "Un différend sur une terre soulaliyate ?", ctaText: "Le cabinet étudie la qualité invoquée, les décisions, les plans et les notifications afin d’identifier la voie adaptée.", serviceLabel: "Foncier rural et agricole",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "Portail juridique du ministère de la Justice — matière foncière", url: propertyLawPortal }, { label: "Loi n° 62-17 et textes d’application", url: "https://adala.justice.gov.ma/api/uploads/2024/06/21/%D8%B8%D9%87%D9%8A%D8%B1%20%D8%B4%D8%B1%D9%8A%D9%81%20%D8%A8%D9%80%D8%AA%D9%86%D9%81%D9%8A%D8%B0%20%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%B1%D9%82%D9%85%D9%84%D9%8A%D8%A9%20%D9%88%D8%AA%D8%AF%D8%A8%D9%8A%D8%B1%20%D8%A3%D9%85%D9%84%D8%A7%D9%83%D9%87%D8%A7-1718966509679.pdf" }],
    },
    ar: {
      slug: "أراضي-الجموع-والأراضي-السلالية", seo: { title: "أراضي الجموع والأراضي السلالية في المغرب", description: "دليل أراضي الجموع والجماعات السلالية بالمغرب: ذوو الحقوق والانتفاع والتحديد الإداري والطعون والوثائق الضرورية." }, category: "العقار الفلاحي",
      h1: "أراضي الجموع وأراضي الجماعات السلالية في المغرب", lead: "تخضع أملاك الجماعات السلالية لنظام خاص يختلف عن الملكية الخاصة، ويقتضي التمييز بين الجماعة وذوي الحقوق والانتفاع والوصاية الإدارية.",
      intro: ["ينظم القانون رقم 62.17 الوصاية الإدارية على الجماعات السلالية وتدبير أملاكها، بينما يؤطر القانون رقم 63.17 التحديد الإداري لهذه الأراضي. لذلك لا يمكن معالجة النزاع وفق قواعد العقار الخاص وحدها.", "قد يتعلق الملف بصفة ذي حق أو الانتفاع أو حدود الأرض أو التعويض أو استغلال قطعة معينة. وتبدأ الدراسة بتحديد النص المطبق والجهة الإدارية أو القضائية المختصة."],
      takeaways: ["أرض الجماعة السلالية لا تطابق عقاراً خاصاً مملوكاً على الشياع.", "ينبغي إثبات صفة ذي الحق وحق الانتفاع وفق النظام الخاص.", "التحديد الإداري والتحفيظ والطعن في القرار مساطر مختلفة."],
      sections: [
        { id: "status", title: "تحديد الوضع القانوني للأرض", paragraphs: ["لا يكفي الاسم المتداول محلياً لتحديد طبيعة الأرض. بل يجب فحص القرارات واللوائح والتصاميم وعمليات التحديد وهوية الجماعة السلالية المعنية.", "يترتب على هذا التكييف تحديد قواعد التدبير والجهات المخول لها التدخل وطرق المنازعة، كما يمنع تطبيق قواعد بيع أو قسمة الملك الخاص في غير محلها."], bullets: ["اسم الجماعة السلالية والموقع الدقيق للأرض.", "قرارات ولوائح ذوي الحقوق ووثائق الانتفاع.", "تصاميم التحديد والمراجع العقارية والقرارات الإدارية."] },
        { id: "beneficiaries", title: "ذوو الحقوق والانتفاع وانتقال الاستفادة", paragraphs: ["لا تعني صفة ذي الحق أو الاستفادة من الانتفاع وجود ملكية خاصة قابلة للتفويت بحرية. لذلك يجب التحقق من اللوائح والقرارات والشروط المنصوص عليها في القانون ونصوصه التطبيقية.", "عند الوفاة أو الخلاف العائلي أو الاعتراض على لائحة، ينبغي فحص الوضع الفعلي والتبليغات وطرق الطعن، دون افتراض انتقال الحق بالطريقة نفسها المطبقة على الملك الخاص."], note: "يتضمن القانون رقم 62.17 ومرسومه التطبيقي قواعد خاصة بالانتفاع وبعض الطعون، وينبغي فحص الأجل انطلاقاً من القرار والتبليغ." },
        { id: "disputes", title: "التحديد والتعويض والمنازعات", paragraphs: ["يرمي التحديد الإداري إلى ضبط حدود الأرض ومساحتها ومشتملاتها. وتقتضي المنازعة مطابقة القرارات المنشورة والتصميم والحقوق التي يتمسك بها المعني بالأمر.", "عندما يترتب عن مشروع أو تفويت مأذون فيه أو عملية أخرى تعويض، يصبح تحديد المستفيدين وتتبع القرار أمراً أساسياً. وتتحدد وسيلة الطعن بحسب الجهة المصدرة للقرار وطبيعة الحق محل النزاع."], bullets: ["قراءة القرار وتحديد الجهة التي أصدرته.", "التحقق من تاريخ التبليغ أو النشر.", "جمع الوثائق المثبتة للصفة والقطعة المعنية.", "التمييز بين التظلم الإداري والدعوى والنزاع حول التعويض."] },
      ],
      checklistTitle: "وثائق تساعد على دراسة الملف", checklistIntro: "يجب أن تسمح الوثائق بتحديد الجماعة والقطعة والقرار المتنازع بشأنه وصفة الشخص المعني.",
      checklist: ["بطاقة التعريف ووثائق الحالة المدنية المفيدة.", "لائحة أو مقرر يتعلق بذوي الحقوق أو الانتفاع.", "التصميم ومقرر التحديد ومراجع القطعة.", "التبليغات والمحاضر والمراسلات مع السلطات.", "الوثائق المرتبطة بالتعويض أو الاستغلال أو الاحتلال."],
      faqTitle: "أسئلة حول أراضي الجموع",
      faqs: [
        { question: "هل أراضي الجموع والأراضي السلالية شيء واحد؟", answer: "يستعمل التعبيران غالباً للدلالة على المجال نفسه في المغرب، لكن العبرة بالوضع القانوني للجماعة وبالوثائق الرسمية، لا بالتسمية المحلية وحدها." },
        { question: "هل يمكن لذي الحق بيع حصته بحرية؟", answer: "لا يعمل الحق في أرض جماعة سلالية كحصة عادية في عقار خاص. ويجب فحص كل عملية في ضوء النظام الخاص والتراخيص التي قد يتطلبها." },
        { question: "كيف يمكن الطعن في مقرر يتعلق بالانتفاع؟", answer: "ينبغي فحص القرار والجهة التي أصدرته وتاريخ تبليغه والقواعد المطبقة، لأن طرق الطعن وآجالها تختلف بحسب الحالة." },
      ],
      ctaTitle: "هل لديكم نزاع بشأن أرض جماعية؟", ctaText: "يفحص المكتب الصفة والقرارات والتصاميم والتبليغات لتحديد المسطرة المناسبة.", serviceLabel: "العقار الفلاحي وأراضي الجموع",
      sourcesLabel: "المصادر الرسمية", sources: [{ label: "البوابة القانونية لوزارة العدل — المادة العقارية", url: propertyLawPortal }, { label: "القانون رقم 62.17 المتعلق بالجماعات السلالية", url: "https://adala.justice.gov.ma/api/uploads/2024/06/21/%D8%B8%D9%87%D9%8A%D8%B1%20%D8%B4%D8%B1%D9%8A%D9%81%20%D8%A8%D9%80%D8%AA%D9%86%D9%81%D9%8A%D8%B0%20%D8%A7%D9%84%D9%82%D8%A7%D9%86%D9%88%D9%86%20%D8%B1%D9%82%D9%85%D9%84%D9%8A%D8%A9%20%D9%88%D8%AA%D8%AF%D8%A8%D9%8A%D8%B1%20%D8%A3%D9%85%D9%84%D8%A7%D9%83%D9%87%D8%A7-1718966509679.pdf" }],
    },
  },
};

export const indivisionGuide: GuideDefinition = {
  key: "indivision", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "succession",
  content: {
    fr: {
      slug: "sortie-indivision-maroc", seo: { title: "Sortie d’indivision au Maroc : accord ou partage", description: "Sortie d’indivision au Maroc : accord entre indivisaires, partage judiciaire, expertise, licitation et cas des terres agricoles héritées." }, category: "Indivision et succession",
      h1: "Sortie d’indivision au Maroc : accord, partage et licitation", lead: "Lorsqu’un bien appartient à plusieurs personnes, la solution dépend des titres, des quotes-parts, de la possibilité d’un partage matériel et de la position de chaque indivisaire.",
      intro: ["L’indivision apparaît fréquemment après une succession, mais elle peut aussi résulter d’un achat ou d’un autre transfert. Chaque dossier exige d’identifier le bien, l’origine des droits et les quotes-parts avant de rechercher un accord ou un partage judiciaire.", "Pour une ferme ou une terre agricole, diviser matériellement le terrain n’est pas toujours possible ou pertinent. L’accès, la superficie, l’exploitation, les règles foncières et la valeur de l’ensemble doivent être examinés."],
      takeaways: ["La sortie amiable suppose un accord clair sur les biens, les quotes-parts et son exécution.", "Le partage judiciaire peut conduire à une expertise et, si le bien n’est pas commodément partageable, à une licitation.", "Un héritier qui occupe ou exploite seul le bien ne fait pas disparaître les droits des autres."],
      sections: [
        { id: "audit", title: "Établir l’origine et l’étendue de l’indivision", paragraphs: ["Il faut reconstituer comment chaque personne est devenue titulaire d’un droit : succession, acquisition, donation ou jugement. Les actes, le titre foncier et les documents d’hérédité doivent aboutir à une liste cohérente des indivisaires et de leurs quotes-parts.", "Les dettes, améliorations, revenus, occupations et conventions antérieures peuvent aussi influencer la négociation ou les comptes entre les parties."], bullets: ["Identifier tous les biens concernés.", "Établir la qualité et la quote-part de chaque indivisaire.", "Vérifier les inscriptions, charges et procédures en cours."] },
        { id: "agreement", title: "Construire une sortie amiable exécutable", paragraphs: ["Un accord peut prévoir un partage matériel, l’attribution du bien à l’un avec compensation, une vente ou une organisation provisoire de la jouissance. Il doit être juridiquement réalisable et suffisamment précis pour être mis en œuvre.", "Pour un terrain, la faisabilité technique et administrative de la division doit être vérifiée avant de signer. Un simple plan entre les membres de la famille ne suffit pas toujours à rendre le partage opposable."], note: "Une médiation utile ne cherche pas seulement un accord de principe ; elle anticipe les actes, formalités, paiements et délais nécessaires à son exécution." },
        { id: "court", title: "Partage judiciaire et vente par licitation", paragraphs: ["À défaut d’accord, un indivisaire peut envisager une demande en partage. Le tribunal apprécie la situation du bien et peut recourir à une expertise pour examiner sa divisibilité et sa valeur.", "Si un partage permettant à chacun de recevoir ses droits n’est pas possible, la vente par licitation peut être ordonnée selon les conditions de la procédure. Cette perspective doit être expliquée aux héritiers avant d’engager ou de prolonger le conflit."], bullets: ["Préparer les titres et documents d’hérédité.", "Identifier les personnes à appeler à la procédure.", "Documenter la consistance, l’exploitation et la valeur du bien."] },
      ],
      checklistTitle: "Préparer une sortie d’indivision", checklistIntro: "La première analyse doit permettre de savoir qui détient quoi, sur quel bien et avec quelles difficultés pratiques.",
      checklist: ["Titre foncier, actes de propriété ou documents relatifs au bien non immatriculé.", "Acte d’hérédité et documents identifiant tous les héritiers.", "Plans, références cadastrales et éléments sur l’accès ou l’exploitation.", "Conventions, échanges et propositions de partage déjà discutées.", "Justificatifs des dépenses, revenus ou occupations contestés."],
      faqTitle: "Questions sur la sortie d’indivision",
      faqs: [
        { question: "Un seul héritier peut-il bloquer le partage ?", answer: "Un désaccord peut empêcher un partage amiable, mais il n’exclut pas l’étude d’une procédure judiciaire. La solution dépend des droits établis et de la nature du bien." },
        { question: "Une ferme peut-elle être divisée entre les héritiers ?", answer: "Cela dépend de sa configuration, de l’accès, des règles applicables et de la possibilité de créer des lots utilisables. Une expertise technique peut être nécessaire." },
        { question: "Qu’est-ce qu’une vente par licitation ?", answer: "Il s’agit d’une vente ordonnée dans le cadre du partage lorsque le bien ne peut pas être partagé de manière permettant à chacun de recevoir ses droits. Ses modalités dépendent de la procédure applicable." },
      ],
      ctaTitle: "Une indivision empêche l’usage ou la vente du bien ?", ctaText: "Le cabinet examine les droits de chacun, la divisibilité du bien et les possibilités d’accord ou de partage judiciaire.", serviceLabel: "Successions et héritage",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "Ministère de la Justice — Code de procédure civile", url: civilProcedureCode }, { label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }],
    },
    ar: {
      slug: "الخروج-من-الشياع-في-القانون-المغربي", seo: { title: "الخروج من الشياع في القانون المغربي", description: "الخروج من الشياع في المغرب: الاتفاق والقسمة القضائية والخبرة والبيع بالمزاد وقسمة الأراضي الفلاحية بين الورثة." }, category: "الشياع والتركات",
      h1: "الخروج من الشياع في القانون المغربي", lead: "عندما يملك عدة أشخاص عقاراً واحداً، تتحدد الحلول بحسب الرسوم وحصص الشركاء وقابلية العقار للقسمة وموقف كل شريك.",
      intro: ["تنشأ حالة الشياع غالباً عن الإرث، وقد تنتج كذلك عن شراء مشترك أو انتقال آخر للملكية. وتبدأ الدراسة بتحديد العقار وأصل الحقوق وحصص كل شريك قبل بحث الاتفاق أو القسمة القضائية.", "في الضيعات والأراضي الفلاحية قد لا تكون القسمة العينية ممكنة أو ملائمة. لذلك ينبغي فحص المسالك والمساحة وطريقة الاستغلال والنظام القانوني وقيمة العقار كوحدة واحدة."],
      takeaways: ["تقتضي القسمة الرضائية اتفاقاً واضحاً على العقارات والحصص وكيفية التنفيذ.", "قد تستلزم القسمة القضائية خبرة، وقد تنتهي بالبيع بالمزاد إذا تعذرت القسمة العينية.", "استغلال شريك واحد للعقار لا يلغي حقوق باقي الشركاء."],
      sections: [
        { id: "audit", title: "تحديد أصل الشياع وحصص الشركاء", paragraphs: ["ينبغي تتبع كيفية انتقال الحق إلى كل شريك، سواء عن طريق الإرث أو الشراء أو الهبة أو الحكم. ويجب أن تؤدي الرسوم والعقود والرسم العقاري ووثائق الإرث إلى تحديد منسجم للشركاء وحصصهم.", "كما قد تؤثر الديون والتحسينات والمداخيل والاستغلال والاتفاقات السابقة في التفاوض أو في الحسابات بين الأطراف."], bullets: ["حصر جميع العقارات المعنية.", "إثبات صفة كل شريك وحصته على الشياع.", "فحص التقييدات والتحملات والدعاوى الجارية."] },
        { id: "agreement", title: "إعداد قسمة رضائية قابلة للتنفيذ", paragraphs: ["يمكن أن يتضمن الاتفاق قسمة عينية أو إسناد العقار إلى أحد الشركاء مقابل تعويض أو بيعه أو تنظيم الانتفاع به مؤقتاً. ويجب أن يكون الاتفاق جائزاً من الناحية القانونية ودقيقاً بما يكفي لتنفيذه.", "بالنسبة إلى الأراضي، ينبغي التحقق من الإمكانات التقنية والإدارية للتقسيم قبل التوقيع. فالتصميم المتفق عليه داخل الأسرة لا يجعل القسمة نافذة بالضرورة."], note: "لا تقتصر الوساطة المفيدة على اتفاق مبدئي، بل تحدد العقود والإجراءات والمبالغ والآجال اللازمة لتنفيذه." },
        { id: "court", title: "القسمة القضائية والبيع بالمزاد", paragraphs: ["عند تعذر الاتفاق، يمكن لأحد الشركاء دراسة رفع دعوى القسمة. وتفحص المحكمة وضعية العقار، وقد تأمر بخبرة لتحديد قابليته للقسمة وقيمته.", "إذا تعذرت قسمة العقار بما يسمح لكل طرف بالانتفاع بحقه، فقد يتم اللجوء إلى البيع بالمزاد وفق المسطرة. وينبغي توضيح هذه النتيجة المحتملة للورثة قبل إطالة النزاع."], bullets: ["إعداد الرسوم ووثائق الإرث.", "تحديد جميع الأشخاص الواجب إدخالهم في الدعوى.", "توثيق طبيعة العقار واستغلاله وقيمته."] },
      ],
      checklistTitle: "إعداد ملف الخروج من الشياع", checklistIntro: "يجب أن تبين الدراسة الأولى أصحاب الحقوق والعقار المعني والصعوبات التي تمنع الاتفاق أو الاستغلال.",
      checklist: ["الرسم العقاري أو رسوم الملكية والعقود الخاصة بالعقار غير المحفظ.", "رسم الإراثة والوثائق التي تحدد جميع الورثة.", "التصاميم والمراجع المساحية ووضعية المسلك والاستغلال.", "الاتفاقات والمراسلات ومقترحات القسمة السابقة.", "ما يثبت المصاريف أو المداخيل أو الاستغلال محل النزاع."],
      faqTitle: "أسئلة حول الخروج من الشياع",
      faqs: [
        { question: "هل يستطيع وارث واحد منع القسمة؟", answer: "قد يمنع الخلاف القسمة الرضائية، لكنه لا يحول دون دراسة القسمة القضائية. ويتوقف الحل على الحقوق الثابتة وطبيعة العقار." },
        { question: "هل يمكن تقسيم ضيعة فلاحية بين الورثة؟", answer: "يتوقف ذلك على شكلها ومسالكها والقواعد المطبقة وإمكان إنشاء أجزاء قابلة للاستغلال، وقد تكون الخبرة التقنية ضرورية." },
        { question: "ما المقصود بالبيع بالمزاد في إطار القسمة؟", answer: "هو بيع يتم في إطار مسطرة القسمة عندما يتعذر تقسيم العقار بما يضمن حقوق كل شريك، وتحدد إجراءاته وفق القواعد المسطرية المطبقة." },
      ],
      ctaTitle: "هل تعطل حالة الشياع استغلال العقار؟", ctaText: "يفحص المكتب حقوق الشركاء وقابلية العقار للقسمة وفرص الاتفاق أو اللجوء إلى القضاء.", serviceLabel: "الميراث والتركات",
      sourcesLabel: "المصادر الرسمية", sources: [{ label: "وزارة العدل — قانون المسطرة المدنية", url: civilProcedureCode }, { label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }],
    },
  },
};

export const melkiyaGuide: GuideDefinition = {
  key: "melkiya", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "immobilier",
  content: {
    fr: {
      slug: "melkiya-terrain-non-titre-maroc", seo: { title: "Melkiya et terrain non titré au Maroc", description: "Melkiya, terrain non immatriculé et titre foncier au Maroc : preuve de propriété, chaîne des actes, possession, vente et litiges." }, category: "Propriété non immatriculée",
      h1: "Melkiya et terrain non titré au Maroc", lead: "Pour un bien non immatriculé, la preuve de la propriété repose sur un ensemble d’actes et de faits qu’il faut rattacher à la même parcelle et à une chaîne de transmission cohérente.",
      intro: ["La Melkiya est couramment invoquée pour établir la propriété d’un immeuble non immatriculé. Elle ne doit pas être assimilée au titre foncier, qui naît de la procédure d’immatriculation et organise la publicité des droits inscrits.", "Avant une vente, une succession ou un litige, il faut vérifier ce que prouve exactement chaque document, l’identité du bien, ses limites et la continuité entre les titulaires successifs."],
      takeaways: ["La Melkiya et le titre foncier sont deux documents de nature différente.", "La chaîne des actes doit conduire sans rupture apparente jusqu’au titulaire actuel.", "La possession et les limites réelles doivent être comparées aux descriptions et plans disponibles."],
      sections: [
        { id: "difference", title: "Melkiya et titre foncier : la différence essentielle", paragraphs: ["Un titre foncier est établi après immatriculation et contient les droits publiés sur le bien. Une Melkiya est un acte utilisé parmi les éléments permettant d’établir la propriété d’un immeuble non immatriculé.", "Cette différence influe sur les vérifications, les formalités de transfert et les voies de contestation. La simple mention « Melkiya » ne renseigne pas, à elle seule, sur la force de toute la chaîne documentaire."], bullets: ["Identifier la nature et la date de chaque acte.", "Vérifier les personnes mentionnées et leur qualité.", "Comparer les limites décrites avec la parcelle occupée."] },
        { id: "transfer", title: "Sécuriser la transmission d’un terrain non titré", paragraphs: ["Il faut reconstituer les transmissions antérieures, vérifier les procurations et successions et rechercher d’éventuelles contradictions entre les actes. L’acheteur doit aussi comprendre les risques liés à l’absence d’un titre foncier.", "Lorsque plusieurs héritiers ou occupants sont concernés, l’accord d’une seule personne ne suffit pas nécessairement. Les droits de chacun et les actes indispensables doivent être déterminés avant l’engagement."], note: "Un prix attractif ou une longue occupation ne corrige pas automatiquement une rupture dans les actes ou un conflit de limites." },
        { id: "disputes", title: "Litiges de possession, limites et double vente", paragraphs: ["Les conflits portent souvent sur l’identité de la parcelle, l’empiètement, la possession, la validité d’un acte ou des ventes concurrentes. La chronologie documentaire et l’état des lieux deviennent alors centraux.", "Selon la situation, des constats, une expertise, une procédure immobilière ou une immatriculation peuvent être envisagés. Le choix dépend de l’objectif poursuivi et des preuves disponibles."], bullets: ["Photographier les limites et repères actuels.", "Réunir les actes originaux et éviter les copies non vérifiables.", "Identifier les voisins, occupants et transactions antérieures."] },
      ],
      checklistTitle: "Vérifier un terrain non immatriculé", checklistIntro: "L’analyse doit relier les documents aux personnes et à la parcelle réellement concernée.",
      checklist: ["Melkiya et actes de transmission successifs.", "Actes d’hérédité, procurations et pièces d’identité utiles.", "Plans, croquis, superficie et description des limites.", "Éléments de possession, constats et quittances disponibles.", "Promesses, actes de vente ou différends antérieurs concernant la parcelle."],
      faqTitle: "Questions sur la Melkiya",
      faqs: [
        { question: "Une Melkiya est-elle un titre foncier ?", answer: "Non. La Melkiya est un acte invoqué pour établir la propriété d’un bien non immatriculé, tandis que le titre foncier résulte de l’immatriculation et contient les droits inscrits." },
        { question: "Peut-on acheter un terrain non titré ?", answer: "Une opération peut être envisagée, mais elle nécessite une vérification renforcée de la propriété, des limites, des transmissions, de la possession et des risques de contestation." },
        { question: "Comment réagir si deux actes portent sur le même terrain ?", answer: "Il faut comparer leur date, leur contenu, les personnes concernées, la chaîne des droits et la parcelle réelle. Une analyse juridique et parfois technique est indispensable avant d’agir." },
      ],
      ctaTitle: "Un doute sur une Melkiya ou un terrain non titré ?", ctaText: "Le cabinet rapproche les actes, la possession, les limites et l’historique des transmissions afin d’évaluer la situation.", serviceLabel: "Droit immobilier",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "Ministère de la Justice — Code des droits réels", url: realRightsCode }, { label: "ANCFCC — procédure d’immatriculation", url: ancfccProcedure }],
    },
    ar: {
      slug: "العقار-غير-المحفظ-ورسم-الملكية", seo: { title: "العقار غير المحفظ ورسم الملكية في المغرب", description: "دليل العقار غير المحفظ ورسم الملكية بالمغرب: إثبات الملكية وتسلسل العقود والحيازة والحدود والبيع والمنازعات." }, category: "العقار غير المحفظ",
      h1: "العقار غير المحفظ ورسم الملكية في المغرب", lead: "يقتضي إثبات ملكية العقار غير المحفظ دراسة الرسوم والوقائع وربطها بالقطعة نفسها وبسلسلة واضحة لانتقال الحقوق.",
      intro: ["يُستند إلى رسم الملكية في إثبات ملكية العقار غير المحفظ، لكنه لا يطابق الرسم العقاري الذي ينتج عن مسطرة التحفيظ وتُقيد فيه الحقوق.", "قبل البيع أو القسمة أو النزاع، ينبغي تحديد ما تثبته كل وثيقة والتحقق من العقار وحدوده واستمرار انتقال الحق بين أصحابه المتعاقبين."],
      takeaways: ["رسم الملكية والرسم العقاري وثيقتان مختلفتان من حيث الطبيعة والآثار.", "ينبغي أن تقود سلسلة الرسوم والعقود إلى المالك الحالي دون انقطاع ظاهر.", "تجب مطابقة الحيازة والحدود الفعلية مع الأوصاف والتصاميم المتوفرة."],
      sections: [
        { id: "difference", title: "الفرق بين رسم الملكية والرسم العقاري", paragraphs: ["يُنشأ الرسم العقاري بعد التحفيظ ويتضمن الحقوق المقيدة على العقار. أما رسم الملكية فهو وثيقة يُستند إليها ضمن عناصر إثبات ملكية عقار غير محفظ.", "يؤثر هذا الفرق في التحقق من الوضعية وفي إجراءات نقل الملكية وطرق المنازعة. ولا تكفي تسمية الوثيقة لمعرفة قوة مجموع الحجج وتسلسلها."], bullets: ["تحديد طبيعة كل وثيقة وتاريخها.", "التحقق من الأشخاص المذكورين وصفاتهم.", "مطابقة الحدود الموصوفة مع القطعة المستغلة فعلاً."] },
        { id: "transfer", title: "تأمين انتقال ملكية العقار غير المحفظ", paragraphs: ["ينبغي تتبع عمليات الانتقال السابقة والتحقق من الوكالات والإرث والبحث عن أي تناقض بين الوثائق. كما يجب أن يدرك المشتري المخاطر المرتبطة بعدم وجود رسم عقاري.", "إذا تعدد الورثة أو المستغلون، فقد لا تكفي موافقة شخص واحد. لذلك تحدد حقوق الجميع والعقود اللازمة قبل الالتزام."], note: "لا يصحح الثمن المنخفض أو طول مدة الاستغلال تلقائياً انقطاع سلسلة العقود أو النزاع حول الحدود." },
        { id: "disputes", title: "نزاعات الحيازة والحدود والتفويت المتعدد", paragraphs: ["تدور المنازعات غالباً حول هوية القطعة أو التعدي أو الحيازة أو صحة عقد أو وجود تفويتات متعارضة. ويصبح ترتيب الوثائق ومعاينة الوضع الفعلي أمراً أساسياً.", "قد تقتضي الحالة معاينة أو خبرة أو دعوى عقارية أو مباشرة التحفيظ. ويتحدد الاختيار بحسب الهدف والأدلة المتوفرة."], bullets: ["توثيق الحدود والعلامات الحالية بالصور.", "جمع الأصول وتجنب الاعتماد على نسخ مجهولة المصدر.", "تحديد المجاورين والمستغلين والتصرفات السابقة."] },
      ],
      checklistTitle: "فحص العقار غير المحفظ", checklistIntro: "يجب أن تربط الدراسة بين الوثائق والأشخاص والقطعة الموجودة فعلياً.",
      checklist: ["رسم الملكية وعقود انتقال الحق المتتابعة.", "رسم الإراثة والوكالات ووثائق الهوية المفيدة.", "التصاميم والمساحة ووصف الحدود.", "أدلة الحيازة والمعاينات والوصولات المتوفرة.", "الوعود أو العقود أو النزاعات السابقة المتعلقة بالقطعة."],
      faqTitle: "أسئلة حول رسم الملكية",
      faqs: [
        { question: "هل رسم الملكية هو الرسم العقاري؟", answer: "لا. يُستند إلى رسم الملكية لإثبات ملكية عقار غير محفظ، بينما ينتج الرسم العقاري عن التحفيظ ويتضمن الحقوق المقيدة." },
        { question: "هل يمكن شراء عقار غير محفظ؟", answer: "يمكن بحث العملية، لكنها تتطلب فحصاً دقيقاً للملكية والحدود وتسلسل انتقال الحقوق والحيازة ومخاطر المنازعة." },
        { question: "ماذا أفعل إذا وُجد عقدان يتعلقان بالأرض نفسها؟", answer: "ينبغي مقارنة التاريخ والمضمون والأطراف وتسلسل الحقوق والقطعة الفعلية، ثم إجراء دراسة قانونية وتقنية عند الحاجة قبل اختيار المسطرة." },
      ],
      ctaTitle: "هل توجد صعوبة في رسم الملكية أو حدود الأرض؟", ctaText: "يطابق المكتب الرسوم والحيازة والحدود وتسلسل انتقال الحقوق لتقييم الوضعية.", serviceLabel: "القانون العقاري",
      sourcesLabel: "المصادر الرسمية", sources: [{ label: "وزارة العدل — مدونة الحقوق العينية", url: realRightsCode }, { label: "الوكالة الوطنية للمحافظة العقارية — مسطرة التحفيظ", url: ancfccProcedure }],
    },
  },
};

export const agriculturalRegistrationGuide: GuideDefinition = {
  key: "agricultural-registration", publishedAt: "2026-09-26", updatedAt: "2026-09-26", serviceKey: "foncierRural",
  content: {
    fr: {
      slug: "immatriculation-terrain-agricole-maroc", seo: { title: "Immatriculation d’un terrain agricole au Maroc", description: "Immatriculer un terrain agricole au Maroc : statut, Melkiya, bornage, opposition, indivision, coût et documents à préparer." }, category: "Terres agricoles",
      h1: "Immatriculation d’un terrain agricole au Maroc", lead: "Avant de déposer une réquisition, il faut clarifier le statut de la terre, l’origine des droits, les limites exploitées et les personnes susceptibles de les contester.",
      intro: ["Une terre agricole peut relever de situations très différentes : propriété privée immatriculée ou non, indivision successorale, terre collective, domaine ou autre régime particulier. La procédure utile dépend d’abord de cette qualification.", "Dans les zones rurales, les actes anciens, les successions non régularisées et les limites matérialisées par des repères variables rendent le bornage particulièrement important."],
      takeaways: ["Le caractère agricole ne détermine pas à lui seul le statut juridique de la terre.", "Les actes et la possession doivent être reliés à des limites identifiables.", "Une indivision ou une opposition doit être anticipée avant que la procédure ne se bloque."],
      sections: [
        { id: "status", title: "Qualifier la terre avant toute démarche", paragraphs: ["La première vérification porte sur la nature du bien et sur les documents qui fondent la propriété ou la jouissance. Une terre soulaliyate, un terrain privé non immatriculé et une parcelle issue d’une succession ne suivent pas les mêmes règles.", "Il faut aussi rechercher si une procédure, une délimitation administrative, une expropriation ou un titre voisin concerne déjà l’assiette."], bullets: ["Identifier le régime foncier.", "Reconstituer l’origine des droits et successions.", "Repérer les titres, réquisitions ou délimitations proches."] },
        { id: "boundary", title: "Préparer le repérage et le bornage", paragraphs: ["Les limites décrites dans les actes doivent être rapprochées du terrain et des plans disponibles. Les chemins, cours d’eau, arbres ou noms de voisins anciens peuvent avoir changé.", "Le bornage permet de recueillir les observations sur place et de matérialiser l’assiette revendiquée. Les désaccords doivent être notés et documentés avec précision."], note: "Une superficie mentionnée dans un acte ne dispense pas d’identifier la parcelle réelle et ses confrontations." },
        { id: "cost", title: "Frais, délais et difficultés fréquentes", paragraphs: ["Les frais dépendent de la formalité, de la valeur ou de la superficie selon les cas, des opérations techniques et des pièces nécessaires. Les barèmes officiels en vigueur doivent être consultés au moment de la démarche.", "La durée varie notamment selon la publicité, le bornage, les diligences du requérant, les difficultés techniques et les oppositions. Un dossier préparé n’élimine pas tous les délais, mais réduit les incohérences évitables."], bullets: ["Vérifier les tarifs officiels actualisés.", "Prévoir les coûts techniques et documentaires éventuels.", "Conserver chaque récépissé, convocation et preuve de diligence."] },
      ],
      checklistTitle: "Préparer l’immatriculation d’une terre agricole", checklistIntro: "Les pièces doivent expliquer l’origine du droit, la parcelle exacte et les personnes concernées.",
      checklist: ["Melkiya, actes de transmission et documents successoraux.", "Pièces d’identité, procurations et informations sur les copropriétaires.", "Plan, croquis, superficie et repères de limites.", "Éléments relatifs à l’exploitation et à l’accès à la parcelle.", "Informations sur les voisins, oppositions ou procédures antérieures."],
      faqTitle: "Questions sur l’immatriculation agricole",
      faqs: [
        { question: "Combien coûte l’immatriculation d’un terrain agricole ?", answer: "Le montant dépend des droits de conservation, de la situation du bien et des opérations techniques ou documents nécessaires. Il faut consulter les tarifs officiels applicables au dossier au moment du dépôt." },
        { question: "Peut-on immatriculer une terre agricole héritée ?", answer: "Une démarche peut être envisagée après avoir identifié tous les héritiers, les droits transmis, les actes disponibles et la parcelle. Les désaccords et ruptures documentaires doivent être traités." },
        { question: "Que faire si un voisin conteste la limite ?", answer: "Il faut confronter les actes, plans et repères du terrain, consigner précisément le désaccord et évaluer la voie technique, amiable ou contentieuse adaptée à l’état de la procédure." },
      ],
      ctaTitle: "Vous préparez l’immatriculation d’une terre agricole ?", ctaText: "Le cabinet vérifie le statut, les actes, les successions et les limites avant d’orienter la démarche.", serviceLabel: "Foncier rural et agricole",
      sourcesLabel: "Sources institutionnelles", sources: [{ label: "ANCFCC — procédure ordinaire d’immatriculation", url: ancfccProcedure }, { label: "Ministère de la Justice — matière foncière", url: propertyLawPortal }],
    },
    ar: {
      slug: "تحفيظ-أرض-فلاحية-بالمغرب", seo: { title: "تحفيظ أرض فلاحية بالمغرب: الوثائق والمسطرة", description: "تحفيظ الأرض الفلاحية بالمغرب: الوضع القانوني ورسم الملكية والتحديد والتعرض والشياع والتكاليف والوثائق المطلوبة." }, category: "العقار الفلاحي",
      h1: "تحفيظ أرض فلاحية بالمغرب", lead: "قبل إيداع مطلب التحفيظ، ينبغي تحديد الوضع القانوني للأرض وأصل الحقوق والحدود المستغلة والأشخاص الذين قد ينازعون فيها.",
      intro: ["قد تكون الأرض الفلاحية ملكاً خاصاً محفظاً أو غير محفظ، أو عقاراً موروثاً على الشياع، أو أرضاً جماعية أو خاضعة لنظام آخر. لذلك تتوقف المسطرة المناسبة أولاً على هذا التكييف.", "في المناطق القروية تزيد أهمية التحديد بسبب الرسوم القديمة والتركات غير المسواة والحدود التي تعتمد أحياناً على معالم تغيرت مع الزمن."],
      takeaways: ["الاستعمال الفلاحي لا يحدد وحده النظام القانوني للأرض.", "ينبغي ربط الرسوم والحيازة بحدود يمكن تحديدها ميدانياً.", "من الأفضل توقع الشياع أو التعرض قبل أن تتعطل المسطرة."],
      sections: [
        { id: "status", title: "تحديد طبيعة الأرض قبل مباشرة الإجراءات", paragraphs: ["ينصب الفحص الأول على طبيعة العقار والوثائق التي تثبت الملكية أو الانتفاع. ولا تخضع أرض جماعية وأرض خاصة غير محفظة وقطعة موروثة للقواعد نفسها.", "ينبغي كذلك البحث عما إذا كانت الأرض معنية بمسطرة سابقة أو تحديد إداري أو نزع ملكية أو تداخل مع رسم مجاور."], bullets: ["تحديد النظام العقاري.", "تتبع أصل الحقوق والتركات.", "البحث عن الرسوم والمطالب وعمليات التحديد القريبة."] },
        { id: "boundary", title: "الاستعداد للتعيين والتحديد", paragraphs: ["تُقارن الحدود الواردة في الرسوم بوضع الأرض والتصاميم المتاحة. فقد تتغير المسالك أو مجاري المياه أو الأشجار أو أسماء المجاورين المذكورين في الوثائق القديمة.", "يسمح التحديد بتلقي الملاحظات في الميدان وتجسيد وعاء العقار المطلوب تحفيظه. وينبغي توثيق كل خلاف حول الحدود بدقة."], note: "لا تعفي المساحة الواردة في الرسم من تحديد القطعة الفعلية وحدودها والمجاورين." },
        { id: "cost", title: "التكاليف والمدة والصعوبات الشائعة", paragraphs: ["تختلف التكاليف بحسب الإجراء وقيمة العقار أو مساحته عند الاقتضاء والأعمال التقنية والوثائق المطلوبة. لذلك يجب الرجوع إلى التعريفات الرسمية السارية عند مباشرة الطلب.", "تتأثر المدة بالإشهار والتحديد والإجراءات المطلوبة من صاحب المطلب والصعوبات التقنية والتعرضات. ولا يلغي إعداد الملف جميع الآجال، لكنه يقلل الأخطاء التي يمكن تفاديها."], bullets: ["التحقق من التعريفات الرسمية المحينة.", "تقدير المصاريف التقنية والوثائقية المحتملة.", "حفظ الوصولات والاستدعاءات وما يثبت تتبع المسطرة."] },
      ],
      checklistTitle: "إعداد ملف تحفيظ أرض فلاحية", checklistIntro: "ينبغي أن توضح الوثائق أصل الحق والقطعة المعنية والأشخاص المرتبطين بها.",
      checklist: ["رسم الملكية وعقود انتقال الحقوق ووثائق الإرث.", "وثائق الهوية والوكالات وبيانات الشركاء.", "التصميم والمساحة والعلامات المحددة للحدود.", "معطيات الاستغلال والمسلك المؤدي إلى الأرض.", "المعلومات المتعلقة بالمجاورين أو التعرضات أو المساطر السابقة."],
      faqTitle: "أسئلة حول تحفيظ الأرض الفلاحية",
      faqs: [
        { question: "ما تكلفة تحفيظ أرض فلاحية بالمغرب؟", answer: "تتوقف التكلفة على وجيبات المحافظة ووضعية العقار والأعمال التقنية والوثائق اللازمة. وينبغي الرجوع إلى التعريفات الرسمية المطبقة عند إيداع الملف." },
        { question: "هل يمكن تحفيظ أرض فلاحية موروثة؟", answer: "يمكن دراسة ذلك بعد تحديد جميع الورثة والحقوق المنتقلة والرسوم المتوفرة والقطعة المعنية، مع معالجة الخلافات أو النقص في الوثائق." },
        { question: "ماذا أفعل إذا اعترض جار على الحدود؟", answer: "ينبغي مقارنة الرسوم والتصاميم بالعلامات الميدانية وتوثيق الخلاف، ثم تقييم الحل التقني أو الرضائي أو القضائي بحسب مرحلة المسطرة." },
      ],
      ctaTitle: "هل تستعدون لتحفيظ أرض فلاحية؟", ctaText: "يفحص المكتب الوضع القانوني والرسوم والتركات والحدود قبل توجيه المسطرة.", serviceLabel: "العقار الفلاحي وأراضي الجموع",
      sourcesLabel: "المصادر الرسمية", sources: [{ label: "الوكالة الوطنية للمحافظة العقارية — المسطرة العادية", url: "https://www.ancfcc.gov.ma/arnos-m%C3%A9tiers/conservation-fonci%C3%A8re-cadastre/procedure-normale/" }, { label: "وزارة العدل — المادة العقارية", url: propertyLawPortal }],
    },
  },
};
